// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user_info

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInfo struct {
	UserList             []*UserInfo_User `protobuf:"bytes,1,rep,name=user_list,json=userList,proto3" json:"user_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserList() []*UserInfo_User {
	if m != nil {
		return m.UserList
	}
	return nil
}

type UserInfo_User struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Age                  uint32   `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Graduate             string   `protobuf:"bytes,3,opt,name=graduate,proto3" json:"graduate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo_User) Reset()         { *m = UserInfo_User{} }
func (m *UserInfo_User) String() string { return proto.CompactTextString(m) }
func (*UserInfo_User) ProtoMessage()    {}
func (*UserInfo_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0, 0}
}

func (m *UserInfo_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo_User.Unmarshal(m, b)
}
func (m *UserInfo_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo_User.Marshal(b, m, deterministic)
}
func (m *UserInfo_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo_User.Merge(m, src)
}
func (m *UserInfo_User) XXX_Size() int {
	return xxx_messageInfo_UserInfo_User.Size(m)
}
func (m *UserInfo_User) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo_User proto.InternalMessageInfo

func (m *UserInfo_User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInfo_User) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserInfo_User) GetGraduate() string {
	if m != nil {
		return m.Graduate
	}
	return ""
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "user_info.UserInfo")
	proto.RegisterType((*UserInfo_User)(nil), "user_info.UserInfo.User")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0xb1, 0xe3, 0x33, 0xf3, 0xd2, 0xf2, 0x95,
	0x26, 0x33, 0x72, 0x71, 0x84, 0x16, 0xa7, 0x16, 0x79, 0xe6, 0xa5, 0xe5, 0x0b, 0x99, 0x72, 0x41,
	0x64, 0x72, 0x32, 0x8b, 0x4b, 0x24, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x24, 0xf4, 0xe0, 0x6a,
	0xf5, 0x60, 0xea, 0xc0, 0x8c, 0x20, 0x0e, 0x90, 0x84, 0x4f, 0x66, 0x71, 0x89, 0x54, 0x00, 0x17,
	0x0b, 0x48, 0x44, 0x48, 0x8a, 0x0b, 0x2c, 0x96, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8,
	0xc1, 0x19, 0x04, 0xe7, 0x0b, 0x09, 0x70, 0x31, 0x27, 0xa6, 0xa7, 0x4a, 0x30, 0x29, 0x30, 0x6a,
	0xf0, 0x06, 0x81, 0x98, 0x20, 0xd5, 0xe9, 0x45, 0x89, 0x29, 0xa5, 0x89, 0x25, 0xa9, 0x12, 0xcc,
	0x10, 0xd5, 0x30, 0x7e, 0x12, 0x1b, 0xd8, 0x9d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x10,
	0xbc, 0x4b, 0x89, 0xb5, 0x00, 0x00, 0x00,
}
