// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auto_c2s.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type C2S struct {
	Key                         string                       `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	GamerLoginC2S               *GamerLoginC2S               `protobuf:"bytes,2,opt,name=gamerLoginC2S" json:"gamerLoginC2S,omitempty"`
	GamerLoginGetDataC2S        *GamerLoginGetDataC2S        `protobuf:"bytes,3,opt,name=gamerLoginGetDataC2S" json:"gamerLoginGetDataC2S,omitempty"`
	ServerTimeC2S               *ServerTimeC2S               `protobuf:"bytes,4,opt,name=serverTimeC2S" json:"serverTimeC2S,omitempty"`
	GamerSubChatChannelC2S      *GamerSubChatChannelC2S      `protobuf:"bytes,5,opt,name=gamerSubChatChannelC2S" json:"gamerSubChatChannelC2S,omitempty"`
	GamerChangeNameC2S          *GamerChangeNameC2S          `protobuf:"bytes,6,opt,name=gamerChangeNameC2S" json:"gamerChangeNameC2S,omitempty"`
	GamerBuyItemC2S             *GamerBuyItemC2S             `protobuf:"bytes,7,opt,name=gamerBuyItemC2S" json:"gamerBuyItemC2S,omitempty"`
	GamerGetBackpackC2S         *GamerGetBackpackC2S         `protobuf:"bytes,8,opt,name=gamerGetBackpackC2S" json:"gamerGetBackpackC2S,omitempty"`
	GamerSellItemC2S            *GamerSellItemC2S            `protobuf:"bytes,9,opt,name=gamerSellItemC2S" json:"gamerSellItemC2S,omitempty"`
	GamerUseItemC2S             *GamerUseItemC2S             `protobuf:"bytes,10,opt,name=gamerUseItemC2S" json:"gamerUseItemC2S,omitempty"`
	GamerCompoundItemC2S        *GamerCompoundItemC2S        `protobuf:"bytes,11,opt,name=gamerCompoundItemC2S" json:"gamerCompoundItemC2S,omitempty"`
	GamerSplitItemC2S           *GamerSplitItemC2S           `protobuf:"bytes,12,opt,name=gamerSplitItemC2S" json:"gamerSplitItemC2S,omitempty"`
	GamerFriendChatC2S          *GamerFriendChatC2S          `protobuf:"bytes,13,opt,name=gamerFriendChatC2S" json:"gamerFriendChatC2S,omitempty"`
	GamerWorldChatC2S           *GamerWorldChatC2S           `protobuf:"bytes,14,opt,name=gamerWorldChatC2S" json:"gamerWorldChatC2S,omitempty"`
	GamerTestChatC2S            *GamerTestChatC2S            `protobuf:"bytes,15,opt,name=gamerTestChatC2S" json:"gamerTestChatC2S,omitempty"`
	GamerClubRequestC2S         *GamerClubRequestC2S         `protobuf:"bytes,16,opt,name=gamerClubRequestC2S" json:"gamerClubRequestC2S,omitempty"`
	GamerNewFriendReqC2S        *GamerNewFriendReqC2S        `protobuf:"bytes,17,opt,name=gamerNewFriendReqC2S" json:"gamerNewFriendReqC2S,omitempty"`
	GamerDelFriendC2S           *GamerDelFriendC2S           `protobuf:"bytes,18,opt,name=gamerDelFriendC2S" json:"gamerDelFriendC2S,omitempty"`
	GamerProcessFriendReqC2S    *GamerProcessFriendReqC2S    `protobuf:"bytes,19,opt,name=gamerProcessFriendReqC2S" json:"gamerProcessFriendReqC2S,omitempty"`
	GamerGetMailC2S             *GamerGetMailC2S             `protobuf:"bytes,20,opt,name=gamerGetMailC2S" json:"gamerGetMailC2S,omitempty"`
	GamerDelMailC2S             *GamerDelMailC2S             `protobuf:"bytes,21,opt,name=gamerDelMailC2S" json:"gamerDelMailC2S,omitempty"`
	GamerDelHaveReadMailC2S     *GamerDelHaveReadMailC2S     `protobuf:"bytes,22,opt,name=gamerDelHaveReadMailC2S" json:"gamerDelHaveReadMailC2S,omitempty"`
	GamerOneKeyRcvMailRewardC2S *GamerOneKeyRcvMailRewardC2S `protobuf:"bytes,23,opt,name=gamerOneKeyRcvMailRewardC2S" json:"gamerOneKeyRcvMailRewardC2S,omitempty"`
	GamerChangeMailStateC2S     *GamerChangeMailStateC2S     `protobuf:"bytes,24,opt,name=gamerChangeMailStateC2S" json:"gamerChangeMailStateC2S,omitempty"`
	GamerNewHeroC2S             *GamerNewHeroC2S             `protobuf:"bytes,25,opt,name=gamerNewHeroC2S" json:"gamerNewHeroC2S,omitempty"`
	GamerUpgradeHeroC2S         *GamerUpgradeHeroC2S         `protobuf:"bytes,26,opt,name=gamerUpgradeHeroC2S" json:"gamerUpgradeHeroC2S,omitempty"`
	GamerChoseHeroC2S           *GamerChoseHeroC2S           `protobuf:"bytes,27,opt,name=gamerChoseHeroC2S" json:"gamerChoseHeroC2S,omitempty"`
	GamerPVPSyncC2S             *GamerPVPSyncC2S             `protobuf:"bytes,28,opt,name=gamerPVPSyncC2S" json:"gamerPVPSyncC2S,omitempty"`
	GamerPVPStateSyncC2S        *GamerPVPStateSyncC2S        `protobuf:"bytes,29,opt,name=gamerPVPStateSyncC2S" json:"gamerPVPStateSyncC2S,omitempty"`
	GamerGetRealTimeRankC2S     *GamerGetRealTimeRankC2S     `protobuf:"bytes,30,opt,name=gamerGetRealTimeRankC2S" json:"gamerGetRealTimeRankC2S,omitempty"`
	GamerCheckPVPBattleC2S      *GamerCheckPVPBattleC2S      `protobuf:"bytes,31,opt,name=gamerCheckPVPBattleC2S" json:"gamerCheckPVPBattleC2S,omitempty"`
	GamerUploadWXInfoC2S        *GamerUploadWXInfoC2S        `protobuf:"bytes,32,opt,name=gamerUploadWXInfoC2S" json:"gamerUploadWXInfoC2S,omitempty"`
	RoomListC2S                 *RoomListC2S                 `protobuf:"bytes,33,opt,name=roomListC2S" json:"roomListC2S,omitempty"`
	GamerNewRoomC2S             *GamerNewRoomC2S             `protobuf:"bytes,34,opt,name=gamerNewRoomC2S" json:"gamerNewRoomC2S,omitempty"`
	GamerAddRoomC2S             *GamerAddRoomC2S             `protobuf:"bytes,35,opt,name=gamerAddRoomC2S" json:"gamerAddRoomC2S,omitempty"`
	GamerLeaveRoomC2S           *GamerLeaveRoomC2S           `protobuf:"bytes,36,opt,name=gamerLeaveRoomC2S" json:"gamerLeaveRoomC2S,omitempty"`
	GamerChangeReadyInRoomC2S   *GamerChangeReadyInRoomC2S   `protobuf:"bytes,37,opt,name=gamerChangeReadyInRoomC2S" json:"gamerChangeReadyInRoomC2S,omitempty"`
	GamerMatchC2S               *GamerMatchC2S               `protobuf:"bytes,38,opt,name=gamerMatchC2S" json:"gamerMatchC2S,omitempty"`
	GamerCancelMatchC2S         *GamerCancelMatchC2S         `protobuf:"bytes,39,opt,name=gamerCancelMatchC2S" json:"gamerCancelMatchC2S,omitempty"`
	GamerGetRewardC2S           *GamerGetRewardC2S           `protobuf:"bytes,40,opt,name=gamerGetRewardC2S" json:"gamerGetRewardC2S,omitempty"`
	GamerUseIconC2S             *GamerUseIconC2S             `protobuf:"bytes,41,opt,name=gamerUseIconC2S" json:"gamerUseIconC2S,omitempty"`
	GamerExtractGashaponC2S     *GamerExtractGashaponC2S     `protobuf:"bytes,42,opt,name=gamerExtractGashaponC2S" json:"gamerExtractGashaponC2S,omitempty"`
	GamerGetAllowanceC2S        *GamerGetAllowanceC2S        `protobuf:"bytes,43,opt,name=gamerGetAllowanceC2S" json:"gamerGetAllowanceC2S,omitempty"`
	GetActivityRewardC2S        *GetActivityRewardC2S        `protobuf:"bytes,44,opt,name=getActivityRewardC2S" json:"getActivityRewardC2S,omitempty"`
	GMC2S                       *GMC2S                       `protobuf:"bytes,45,opt,name=gMC2S" json:"gMC2S,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}                     `json:"-"`
	XXX_unrecognized            []byte                       `json:"-"`
	XXX_sizecache               int32                        `json:"-"`
}

func (m *C2S) Reset()         { *m = C2S{} }
func (m *C2S) String() string { return proto.CompactTextString(m) }
func (*C2S) ProtoMessage()    {}
func (*C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_auto_c2s_cbceee1732e76bb1, []int{0}
}
func (m *C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S.Unmarshal(m, b)
}
func (m *C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S.Marshal(b, m, deterministic)
}
func (dst *C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S.Merge(dst, src)
}
func (m *C2S) XXX_Size() int {
	return xxx_messageInfo_C2S.Size(m)
}
func (m *C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_C2S proto.InternalMessageInfo

func (m *C2S) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *C2S) GetGamerLoginC2S() *GamerLoginC2S {
	if m != nil {
		return m.GamerLoginC2S
	}
	return nil
}

func (m *C2S) GetGamerLoginGetDataC2S() *GamerLoginGetDataC2S {
	if m != nil {
		return m.GamerLoginGetDataC2S
	}
	return nil
}

func (m *C2S) GetServerTimeC2S() *ServerTimeC2S {
	if m != nil {
		return m.ServerTimeC2S
	}
	return nil
}

func (m *C2S) GetGamerSubChatChannelC2S() *GamerSubChatChannelC2S {
	if m != nil {
		return m.GamerSubChatChannelC2S
	}
	return nil
}

func (m *C2S) GetGamerChangeNameC2S() *GamerChangeNameC2S {
	if m != nil {
		return m.GamerChangeNameC2S
	}
	return nil
}

func (m *C2S) GetGamerBuyItemC2S() *GamerBuyItemC2S {
	if m != nil {
		return m.GamerBuyItemC2S
	}
	return nil
}

func (m *C2S) GetGamerGetBackpackC2S() *GamerGetBackpackC2S {
	if m != nil {
		return m.GamerGetBackpackC2S
	}
	return nil
}

func (m *C2S) GetGamerSellItemC2S() *GamerSellItemC2S {
	if m != nil {
		return m.GamerSellItemC2S
	}
	return nil
}

func (m *C2S) GetGamerUseItemC2S() *GamerUseItemC2S {
	if m != nil {
		return m.GamerUseItemC2S
	}
	return nil
}

func (m *C2S) GetGamerCompoundItemC2S() *GamerCompoundItemC2S {
	if m != nil {
		return m.GamerCompoundItemC2S
	}
	return nil
}

func (m *C2S) GetGamerSplitItemC2S() *GamerSplitItemC2S {
	if m != nil {
		return m.GamerSplitItemC2S
	}
	return nil
}

func (m *C2S) GetGamerFriendChatC2S() *GamerFriendChatC2S {
	if m != nil {
		return m.GamerFriendChatC2S
	}
	return nil
}

func (m *C2S) GetGamerWorldChatC2S() *GamerWorldChatC2S {
	if m != nil {
		return m.GamerWorldChatC2S
	}
	return nil
}

func (m *C2S) GetGamerTestChatC2S() *GamerTestChatC2S {
	if m != nil {
		return m.GamerTestChatC2S
	}
	return nil
}

func (m *C2S) GetGamerClubRequestC2S() *GamerClubRequestC2S {
	if m != nil {
		return m.GamerClubRequestC2S
	}
	return nil
}

func (m *C2S) GetGamerNewFriendReqC2S() *GamerNewFriendReqC2S {
	if m != nil {
		return m.GamerNewFriendReqC2S
	}
	return nil
}

func (m *C2S) GetGamerDelFriendC2S() *GamerDelFriendC2S {
	if m != nil {
		return m.GamerDelFriendC2S
	}
	return nil
}

func (m *C2S) GetGamerProcessFriendReqC2S() *GamerProcessFriendReqC2S {
	if m != nil {
		return m.GamerProcessFriendReqC2S
	}
	return nil
}

func (m *C2S) GetGamerGetMailC2S() *GamerGetMailC2S {
	if m != nil {
		return m.GamerGetMailC2S
	}
	return nil
}

func (m *C2S) GetGamerDelMailC2S() *GamerDelMailC2S {
	if m != nil {
		return m.GamerDelMailC2S
	}
	return nil
}

func (m *C2S) GetGamerDelHaveReadMailC2S() *GamerDelHaveReadMailC2S {
	if m != nil {
		return m.GamerDelHaveReadMailC2S
	}
	return nil
}

func (m *C2S) GetGamerOneKeyRcvMailRewardC2S() *GamerOneKeyRcvMailRewardC2S {
	if m != nil {
		return m.GamerOneKeyRcvMailRewardC2S
	}
	return nil
}

func (m *C2S) GetGamerChangeMailStateC2S() *GamerChangeMailStateC2S {
	if m != nil {
		return m.GamerChangeMailStateC2S
	}
	return nil
}

func (m *C2S) GetGamerNewHeroC2S() *GamerNewHeroC2S {
	if m != nil {
		return m.GamerNewHeroC2S
	}
	return nil
}

func (m *C2S) GetGamerUpgradeHeroC2S() *GamerUpgradeHeroC2S {
	if m != nil {
		return m.GamerUpgradeHeroC2S
	}
	return nil
}

func (m *C2S) GetGamerChoseHeroC2S() *GamerChoseHeroC2S {
	if m != nil {
		return m.GamerChoseHeroC2S
	}
	return nil
}

func (m *C2S) GetGamerPVPSyncC2S() *GamerPVPSyncC2S {
	if m != nil {
		return m.GamerPVPSyncC2S
	}
	return nil
}

func (m *C2S) GetGamerPVPStateSyncC2S() *GamerPVPStateSyncC2S {
	if m != nil {
		return m.GamerPVPStateSyncC2S
	}
	return nil
}

func (m *C2S) GetGamerGetRealTimeRankC2S() *GamerGetRealTimeRankC2S {
	if m != nil {
		return m.GamerGetRealTimeRankC2S
	}
	return nil
}

func (m *C2S) GetGamerCheckPVPBattleC2S() *GamerCheckPVPBattleC2S {
	if m != nil {
		return m.GamerCheckPVPBattleC2S
	}
	return nil
}

func (m *C2S) GetGamerUploadWXInfoC2S() *GamerUploadWXInfoC2S {
	if m != nil {
		return m.GamerUploadWXInfoC2S
	}
	return nil
}

func (m *C2S) GetRoomListC2S() *RoomListC2S {
	if m != nil {
		return m.RoomListC2S
	}
	return nil
}

func (m *C2S) GetGamerNewRoomC2S() *GamerNewRoomC2S {
	if m != nil {
		return m.GamerNewRoomC2S
	}
	return nil
}

func (m *C2S) GetGamerAddRoomC2S() *GamerAddRoomC2S {
	if m != nil {
		return m.GamerAddRoomC2S
	}
	return nil
}

func (m *C2S) GetGamerLeaveRoomC2S() *GamerLeaveRoomC2S {
	if m != nil {
		return m.GamerLeaveRoomC2S
	}
	return nil
}

func (m *C2S) GetGamerChangeReadyInRoomC2S() *GamerChangeReadyInRoomC2S {
	if m != nil {
		return m.GamerChangeReadyInRoomC2S
	}
	return nil
}

func (m *C2S) GetGamerMatchC2S() *GamerMatchC2S {
	if m != nil {
		return m.GamerMatchC2S
	}
	return nil
}

func (m *C2S) GetGamerCancelMatchC2S() *GamerCancelMatchC2S {
	if m != nil {
		return m.GamerCancelMatchC2S
	}
	return nil
}

func (m *C2S) GetGamerGetRewardC2S() *GamerGetRewardC2S {
	if m != nil {
		return m.GamerGetRewardC2S
	}
	return nil
}

func (m *C2S) GetGamerUseIconC2S() *GamerUseIconC2S {
	if m != nil {
		return m.GamerUseIconC2S
	}
	return nil
}

func (m *C2S) GetGamerExtractGashaponC2S() *GamerExtractGashaponC2S {
	if m != nil {
		return m.GamerExtractGashaponC2S
	}
	return nil
}

func (m *C2S) GetGamerGetAllowanceC2S() *GamerGetAllowanceC2S {
	if m != nil {
		return m.GamerGetAllowanceC2S
	}
	return nil
}

func (m *C2S) GetGetActivityRewardC2S() *GetActivityRewardC2S {
	if m != nil {
		return m.GetActivityRewardC2S
	}
	return nil
}

func (m *C2S) GetGMC2S() *GMC2S {
	if m != nil {
		return m.GMC2S
	}
	return nil
}

func init() {
	proto.RegisterType((*C2S)(nil), "C2S")
}

func init() { proto.RegisterFile("auto_c2s.proto", fileDescriptor_auto_c2s_cbceee1732e76bb1) }

var fileDescriptor_auto_c2s_cbceee1732e76bb1 = []byte{
	// 933 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x56, 0xdd, 0x53, 0xdc, 0x36,
	0x10, 0x1f, 0x4a, 0x43, 0x1b, 0x41, 0x08, 0x08, 0x12, 0x0e, 0x42, 0x5b, 0x9a, 0x7e, 0xd1, 0xaf,
	0x7b, 0xb8, 0xf6, 0xa9, 0x33, 0x9d, 0x29, 0x98, 0xc6, 0x61, 0x0a, 0xe4, 0x66, 0x1d, 0x92, 0x3c,
	0xb5, 0x23, 0x7c, 0xdb, 0x3b, 0x0f, 0x3e, 0xfb, 0x62, 0xeb, 0xa0, 0xf7, 0x17, 0xf7, 0xdf, 0xe8,
	0x48, 0x3a, 0xcb, 0x6b, 0x59, 0xee, 0xdb, 0xdd, 0xef, 0x6b, 0x56, 0xab, 0x95, 0x25, 0xb6, 0x29,
	0xe6, 0x32, 0xff, 0x2b, 0x1e, 0x94, 0xfd, 0x59, 0x91, 0xcb, 0xfc, 0x60, 0x23, 0x4e, 0x13, 0xcc,
	0xa4, 0xf9, 0xf7, 0xfc, 0xdf, 0x3d, 0xb6, 0x1a, 0x0c, 0x22, 0xbe, 0xc5, 0x56, 0x6f, 0x71, 0xd1,
	0x5b, 0x39, 0x5a, 0x39, 0x7e, 0x08, 0xea, 0x27, 0xff, 0x99, 0x3d, 0x1a, 0x8b, 0x29, 0x16, 0x17,
	0xf9, 0x38, 0xc9, 0x82, 0x41, 0xd4, 0xfb, 0xe0, 0x68, 0xe5, 0x78, 0x7d, 0xb0, 0xd9, 0x0f, 0x29,
	0x0a, 0x4d, 0x11, 0x3f, 0x67, 0xbb, 0x35, 0x10, 0xa2, 0x3c, 0x13, 0x52, 0x28, 0xf3, 0xaa, 0x36,
	0x3f, 0x21, 0xe6, 0x9a, 0x04, 0xaf, 0x45, 0x15, 0x50, 0x62, 0x71, 0x87, 0xc5, 0xeb, 0x64, 0x8a,
	0x2a, 0xe3, 0xc3, 0x65, 0x01, 0x11, 0x45, 0xa1, 0x29, 0xe2, 0xaf, 0xd8, 0x53, 0x9d, 0x16, 0xcd,
	0x6f, 0x82, 0x89, 0x90, 0xc1, 0x44, 0x64, 0x19, 0xa6, 0xca, 0xfe, 0x40, 0xdb, 0xf7, 0x4c, 0x09,
	0x2d, 0x1a, 0x3a, 0x6c, 0x3c, 0x60, 0x5c, 0x33, 0x0a, 0x1a, 0xe3, 0x95, 0x30, 0xb5, 0xac, 0xe9,
	0xb0, 0x1d, 0x13, 0xd6, 0xa0, 0xc0, 0x23, 0xe7, 0xbf, 0xb0, 0xc7, 0x1a, 0x3d, 0x9d, 0x2f, 0xce,
	0x25, 0x4e, 0x55, 0xc2, 0x47, 0x3a, 0x61, 0xcb, 0x24, 0xd4, 0x38, 0xb8, 0x42, 0xfe, 0x82, 0xed,
	0x68, 0x28, 0x44, 0x79, 0x2a, 0xe2, 0xdb, 0x99, 0x88, 0x6f, 0x95, 0xff, 0x63, 0xed, 0xdf, 0x35,
	0xfe, 0x26, 0x07, 0x3e, 0x03, 0xff, 0x95, 0x6d, 0x99, 0x25, 0x62, 0x9a, 0x56, 0x45, 0x3c, 0xd4,
	0x21, 0xdb, 0xcb, 0x9e, 0xd4, 0x04, 0xb4, 0xa4, 0x76, 0x09, 0xd7, 0x25, 0x56, 0x6e, 0x46, 0x97,
	0x50, 0xe3, 0xe0, 0x0a, 0xed, 0x54, 0x04, 0xf9, 0x74, 0x96, 0xcf, 0xb3, 0x51, 0x15, 0xb0, 0x4e,
	0xa7, 0xc2, 0x21, 0xc1, 0x6b, 0xe1, 0xbf, 0xb1, 0x6d, 0x53, 0xda, 0x2c, 0x4d, 0x64, 0x95, 0xb3,
	0xa1, 0x73, 0xf8, 0x72, 0x19, 0x84, 0x81, 0xb6, 0xd8, 0x6e, 0xe8, 0x8b, 0x22, 0xc1, 0x6c, 0xa4,
	0x77, 0x7b, 0x10, 0xf5, 0x1e, 0xd1, 0x0d, 0x6d, 0x50, 0xe0, 0x91, 0xdb, 0x32, 0xde, 0xe6, 0x45,
	0x6a, 0x33, 0x36, 0x69, 0x19, 0x94, 0x81, 0xb6, 0xd8, 0x6e, 0xc7, 0x6b, 0x2c, 0x65, 0x15, 0xf0,
	0x98, 0x6e, 0x07, 0x21, 0xa0, 0x25, 0xb5, 0x53, 0x11, 0xa4, 0xf3, 0x1b, 0xc0, 0xf7, 0x73, 0x45,
	0x0d, 0xa2, 0xde, 0x16, 0x9d, 0x8a, 0x26, 0x07, 0x3e, 0x83, 0xdd, 0x9a, 0x2b, 0xbc, 0x37, 0x2b,
	0x04, 0x7c, 0xaf, 0x82, 0xb6, 0xe9, 0xd6, 0x38, 0x24, 0x78, 0x2d, 0xb6, 0x27, 0x67, 0x98, 0x2e,
	0x9b, 0x35, 0x88, 0x7a, 0x9c, 0xf6, 0x84, 0x32, 0xd0, 0x16, 0xf3, 0x6b, 0xd6, 0xd3, 0xe0, 0xb0,
	0xc8, 0x63, 0x2c, 0xcb, 0x46, 0x41, 0x3b, 0x3a, 0x68, 0xdf, 0x04, 0x79, 0x04, 0xd0, 0x69, 0xb5,
	0xa3, 0x1b, 0xa2, 0xbc, 0x14, 0x89, 0xfe, 0x18, 0xec, 0xd2, 0xd1, 0xad, 0x71, 0x70, 0x85, 0xd6,
	0x7b, 0x86, 0x69, 0xe5, 0x7d, 0x42, 0xbd, 0x35, 0x0e, 0xae, 0x90, 0x03, 0xdb, 0xab, 0xa0, 0x97,
	0xe2, 0x0e, 0x01, 0xc5, 0xa8, 0xca, 0x78, 0xaa, 0x33, 0x7a, 0x36, 0xc3, 0xe1, 0xa1, 0xcb, 0xc8,
	0xff, 0x64, 0xcf, 0x34, 0xf5, 0x2a, 0xc3, 0x3f, 0x70, 0x01, 0xf1, 0x9d, 0x22, 0x00, 0xef, 0x45,
	0xa1, 0xdb, 0xbd, 0xa7, 0x73, 0x0f, 0x4d, 0xae, 0x5f, 0x03, 0xff, 0x17, 0x60, 0x6b, 0x36, 0xdf,
	0x2f, 0xc5, 0x45, 0x52, 0x48, 0xfd, 0xcd, 0xeb, 0xd1, 0x9a, 0xdb, 0x3c, 0x74, 0x19, 0x6d, 0x0f,
	0xaf, 0xf0, 0xfe, 0x25, 0x16, 0xb9, 0xca, 0xda, 0xa7, 0x3d, 0xac, 0x71, 0x70, 0x85, 0x76, 0xce,
	0xaf, 0x67, 0xe3, 0x42, 0x8c, 0xb0, 0xf2, 0x1f, 0xd0, 0x39, 0x6f, 0x72, 0xe0, 0x33, 0xd8, 0xe1,
	0x0c, 0x26, 0x79, 0x69, 0x53, 0x9e, 0xd1, 0xe1, 0xa4, 0x0c, 0xb4, 0xc5, 0x76, 0x15, 0xc3, 0x37,
	0xc3, 0x68, 0x91, 0xc5, 0xca, 0x7f, 0x48, 0x57, 0x51, 0xe3, 0xe0, 0x0a, 0xed, 0x29, 0x53, 0x90,
	0xea, 0x4a, 0x15, 0xf0, 0x09, 0x3d, 0x65, 0x0e, 0x09, 0x5e, 0x8b, 0xdd, 0xa0, 0x10, 0x25, 0xa0,
	0x48, 0xd5, 0xbd, 0x07, 0x22, 0xd3, 0x57, 0xc2, 0xa7, 0x74, 0x83, 0xda, 0x3c, 0x74, 0x19, 0xed,
	0xa5, 0x19, 0x4c, 0x30, 0xbe, 0x1d, 0xbe, 0x19, 0x9e, 0x0a, 0x29, 0x53, 0xbd, 0xe7, 0x9f, 0xd1,
	0x4b, 0xb3, 0x45, 0x43, 0x87, 0xcd, 0xae, 0xf7, 0x7a, 0x96, 0xe6, 0x62, 0xf4, 0xf6, 0xdd, 0x79,
	0xf6, 0xb7, 0x6e, 0xf8, 0x11, 0x5d, 0xaf, 0x43, 0x82, 0xd7, 0xc2, 0xfb, 0x6c, 0xbd, 0xc8, 0xf3,
	0xe9, 0x45, 0x62, 0x3e, 0x70, 0x9f, 0xeb, 0x84, 0x8d, 0x3e, 0xd4, 0x18, 0x50, 0x01, 0x1d, 0x36,
	0xa5, 0x51, 0x9e, 0xe7, 0xce, 0xb0, 0x2d, 0x71, 0x70, 0x85, 0xd6, 0x7b, 0x32, 0x1a, 0x55, 0xde,
	0x2f, 0xa8, 0xb7, 0xc6, 0xc1, 0x15, 0xda, 0x01, 0xbb, 0x40, 0x75, 0x62, 0x97, 0xee, 0x2f, 0xe9,
	0x80, 0x51, 0x06, 0xda, 0x62, 0xfe, 0x8e, 0xed, 0x93, 0x13, 0xa4, 0x0e, 0xfd, 0xe2, 0x3c, 0xab,
	0x92, 0xbe, 0xd2, 0x49, 0x07, 0xf4, 0xf0, 0x35, 0x15, 0xd0, 0x6d, 0xb6, 0x6f, 0xb9, 0x4b, 0x21,
	0xe3, 0x89, 0x4a, 0xfb, 0x9a, 0xbe, 0xe5, 0x2a, 0x14, 0x9a, 0xa2, 0xfa, 0x8a, 0x11, 0x59, 0xac,
	0x3e, 0x6a, 0x4b, 0xef, 0x37, 0x8d, 0x2b, 0xa6, 0xc1, 0x81, 0xcf, 0x60, 0x3b, 0xa3, 0x07, 0xaf,
	0xfa, 0x50, 0x1d, 0xd3, 0xce, 0x50, 0x06, 0xda, 0xe2, 0xc6, 0xdb, 0x23, 0xce, 0xf5, 0x6b, 0xf4,
	0x5b, 0xf7, 0xed, 0x61, 0x70, 0x70, 0x85, 0xf6, 0xbc, 0xfc, 0xfe, 0x8f, 0x2c, 0x44, 0x2c, 0x43,
	0x51, 0x4e, 0xc4, 0xcc, 0x64, 0x7c, 0x47, 0xcf, 0x4b, 0x9b, 0x87, 0x2e, 0xa3, 0x1d, 0xef, 0x10,
	0xe5, 0x49, 0x9a, 0xe6, 0xf7, 0x6a, 0xbd, 0x2a, 0xf0, 0x7b, 0x3a, 0xde, 0x0e, 0x09, 0x5e, 0x8b,
	0x8e, 0x42, 0x79, 0x12, 0xcb, 0xe4, 0x2e, 0x91, 0x8b, 0xba, 0x3f, 0x3f, 0x54, 0x51, 0x1e, 0x12,
	0xbc, 0x16, 0x7e, 0xc8, 0x1e, 0x8c, 0x2f, 0x95, 0xf7, 0x47, 0xed, 0x5d, 0xeb, 0x87, 0xea, 0x1f,
	0x18, 0xf0, 0x66, 0x4d, 0x3f, 0xf8, 0x7f, 0xfa, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x16, 0xbf, 0x91,
	0x97, 0x10, 0x0c, 0x00, 0x00,
}
