// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auto_s2c.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type S2C struct {
	Error                           int32                            `protobuf:"varint,1,opt,name=error" json:"error,omitempty"`
	Key                             string                           `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	GamerLoginS2C                   *GamerLoginS2C                   `protobuf:"bytes,3,opt,name=gamerLoginS2C" json:"gamerLoginS2C,omitempty"`
	GamerLoginGetDataS2C            *GamerLoginGetDataS2C            `protobuf:"bytes,4,opt,name=gamerLoginGetDataS2C" json:"gamerLoginGetDataS2C,omitempty"`
	ServerTimeS2C                   *ServerTimeS2C                   `protobuf:"bytes,5,opt,name=serverTimeS2C" json:"serverTimeS2C,omitempty"`
	GamerNotifyLoginOtherS2C        *GamerNotifyLoginOtherS2C        `protobuf:"bytes,6,opt,name=gamerNotifyLoginOtherS2C" json:"gamerNotifyLoginOtherS2C,omitempty"`
	GamerSubChatChannelS2C          *GamerSubChatChannelS2C          `protobuf:"bytes,7,opt,name=gamerSubChatChannelS2C" json:"gamerSubChatChannelS2C,omitempty"`
	GamerChangeNameS2C              *GamerChangeNameS2C              `protobuf:"bytes,8,opt,name=gamerChangeNameS2C" json:"gamerChangeNameS2C,omitempty"`
	GamerNotifyExpLevelS2C          *GamerNotifyExpLevelS2C          `protobuf:"bytes,9,opt,name=gamerNotifyExpLevelS2C" json:"gamerNotifyExpLevelS2C,omitempty"`
	GamerBuyItemS2C                 *GamerBuyItemS2C                 `protobuf:"bytes,10,opt,name=gamerBuyItemS2C" json:"gamerBuyItemS2C,omitempty"`
	GamerGetBackpackS2C             *GamerGetBackpackS2C             `protobuf:"bytes,11,opt,name=gamerGetBackpackS2C" json:"gamerGetBackpackS2C,omitempty"`
	GamerNotifyItemS2C              *GamerNotifyItemS2C              `protobuf:"bytes,12,opt,name=gamerNotifyItemS2C" json:"gamerNotifyItemS2C,omitempty"`
	GamerSellItemS2C                *GamerSellItemS2C                `protobuf:"bytes,13,opt,name=gamerSellItemS2C" json:"gamerSellItemS2C,omitempty"`
	GamerUseItemS2C                 *GamerUseItemS2C                 `protobuf:"bytes,14,opt,name=gamerUseItemS2C" json:"gamerUseItemS2C,omitempty"`
	GamerCompoundItemS2C            *GamerCompoundItemS2C            `protobuf:"bytes,15,opt,name=gamerCompoundItemS2C" json:"gamerCompoundItemS2C,omitempty"`
	GamerSplitItemS2C               *GamerSplitItemS2C               `protobuf:"bytes,16,opt,name=gamerSplitItemS2C" json:"gamerSplitItemS2C,omitempty"`
	GamerNotifyItemChangeS2C        *GamerNotifyItemChangeS2C        `protobuf:"bytes,17,opt,name=gamerNotifyItemChangeS2C" json:"gamerNotifyItemChangeS2C,omitempty"`
	GamerFriendChatS2C              *GamerFriendChatS2C              `protobuf:"bytes,18,opt,name=gamerFriendChatS2C" json:"gamerFriendChatS2C,omitempty"`
	GamerWorldChatS2C               *GamerWorldChatS2C               `protobuf:"bytes,19,opt,name=gamerWorldChatS2C" json:"gamerWorldChatS2C,omitempty"`
	GamerTestChatS2C                *GamerTestChatS2C                `protobuf:"bytes,20,opt,name=gamerTestChatS2C" json:"gamerTestChatS2C,omitempty"`
	GamerClubRequestS2C             *GamerClubRequestS2C             `protobuf:"bytes,21,opt,name=gamerClubRequestS2C" json:"gamerClubRequestS2C,omitempty"`
	GamerNotifyNewChatS2C           *GamerNotifyNewChatS2C           `protobuf:"bytes,22,opt,name=gamerNotifyNewChatS2C" json:"gamerNotifyNewChatS2C,omitempty"`
	GamerNewFriendReqS2C            *GamerNewFriendReqS2C            `protobuf:"bytes,23,opt,name=gamerNewFriendReqS2C" json:"gamerNewFriendReqS2C,omitempty"`
	GamerDelFriendS2C               *GamerDelFriendS2C               `protobuf:"bytes,24,opt,name=gamerDelFriendS2C" json:"gamerDelFriendS2C,omitempty"`
	GamerNotifyNewFriendReqS2C      *GamerNotifyNewFriendReqS2C      `protobuf:"bytes,25,opt,name=gamerNotifyNewFriendReqS2C" json:"gamerNotifyNewFriendReqS2C,omitempty"`
	GamerProcessFriendReqS2C        *GamerProcessFriendReqS2C        `protobuf:"bytes,26,opt,name=gamerProcessFriendReqS2C" json:"gamerProcessFriendReqS2C,omitempty"`
	GamerNotifyNewFriendS2C         *GamerNotifyNewFriendS2C         `protobuf:"bytes,27,opt,name=gamerNotifyNewFriendS2C" json:"gamerNotifyNewFriendS2C,omitempty"`
	GamerNotifyDelFriendS2C         *GamerNotifyDelFriendS2C         `protobuf:"bytes,28,opt,name=gamerNotifyDelFriendS2C" json:"gamerNotifyDelFriendS2C,omitempty"`
	GamerNotifyMailS2C              *GamerNotifyMailS2C              `protobuf:"bytes,29,opt,name=gamerNotifyMailS2C" json:"gamerNotifyMailS2C,omitempty"`
	GamerNotifyNewMailS2C           *GamerNotifyNewMailS2C           `protobuf:"bytes,30,opt,name=gamerNotifyNewMailS2C" json:"gamerNotifyNewMailS2C,omitempty"`
	GamerGetMailS2C                 *GamerGetMailS2C                 `protobuf:"bytes,31,opt,name=gamerGetMailS2C" json:"gamerGetMailS2C,omitempty"`
	GamerDelMailS2C                 *GamerDelMailS2C                 `protobuf:"bytes,32,opt,name=gamerDelMailS2C" json:"gamerDelMailS2C,omitempty"`
	GamerDelHaveReadMailS2C         *GamerDelHaveReadMailS2C         `protobuf:"bytes,33,opt,name=gamerDelHaveReadMailS2C" json:"gamerDelHaveReadMailS2C,omitempty"`
	GamerOneKeyRcvMailRewardS2C     *GamerOneKeyRcvMailRewardS2C     `protobuf:"bytes,34,opt,name=gamerOneKeyRcvMailRewardS2C" json:"gamerOneKeyRcvMailRewardS2C,omitempty"`
	GamerChangeMailStateS2C         *GamerChangeMailStateS2C         `protobuf:"bytes,35,opt,name=gamerChangeMailStateS2C" json:"gamerChangeMailStateS2C,omitempty"`
	GamerNewHeroS2C                 *GamerNewHeroS2C                 `protobuf:"bytes,36,opt,name=gamerNewHeroS2C" json:"gamerNewHeroS2C,omitempty"`
	GamerUpgradeHeroS2C             *GamerUpgradeHeroS2C             `protobuf:"bytes,37,opt,name=gamerUpgradeHeroS2C" json:"gamerUpgradeHeroS2C,omitempty"`
	GamerChoseHeroS2C               *GamerChoseHeroS2C               `protobuf:"bytes,38,opt,name=gamerChoseHeroS2C" json:"gamerChoseHeroS2C,omitempty"`
	GamerPVPSyncS2C                 *GamerPVPSyncS2C                 `protobuf:"bytes,39,opt,name=gamerPVPSyncS2C" json:"gamerPVPSyncS2C,omitempty"`
	GamerNotifyGamerMiniS2C         *GamerNotifyGamerMiniS2C         `protobuf:"bytes,40,opt,name=gamerNotifyGamerMiniS2C" json:"gamerNotifyGamerMiniS2C,omitempty"`
	GamerNotifyPVPSyncS2C           *GamerNotifyPVPSyncS2C           `protobuf:"bytes,41,opt,name=gamerNotifyPVPSyncS2C" json:"gamerNotifyPVPSyncS2C,omitempty"`
	GamerNotifyNewPVPResultS2C      *GamerNotifyNewPVPResultS2C      `protobuf:"bytes,42,opt,name=gamerNotifyNewPVPResultS2C" json:"gamerNotifyNewPVPResultS2C,omitempty"`
	GamerPVPStateSyncS2C            *GamerPVPStateSyncS2C            `protobuf:"bytes,43,opt,name=gamerPVPStateSyncS2C" json:"gamerPVPStateSyncS2C,omitempty"`
	GamerNotifyPVPStateSyncS2C      *GamerNotifyPVPStateSyncS2C      `protobuf:"bytes,44,opt,name=gamerNotifyPVPStateSyncS2C" json:"gamerNotifyPVPStateSyncS2C,omitempty"`
	GamerNotifyIconChangeS2C        *GamerNotifyIconChangeS2C        `protobuf:"bytes,45,opt,name=gamerNotifyIconChangeS2C" json:"gamerNotifyIconChangeS2C,omitempty"`
	GamerNotifyDiamonChangeS2C      *GamerNotifyDiamonChangeS2C      `protobuf:"bytes,46,opt,name=gamerNotifyDiamonChangeS2C" json:"gamerNotifyDiamonChangeS2C,omitempty"`
	GamerNotifyEnergyChangeS2C      *GamerNotifyEnergyChangeS2C      `protobuf:"bytes,47,opt,name=gamerNotifyEnergyChangeS2C" json:"gamerNotifyEnergyChangeS2C,omitempty"`
	GamerNotifyExpChangeS2C         *GamerNotifyExpChangeS2C         `protobuf:"bytes,48,opt,name=gamerNotifyExpChangeS2C" json:"gamerNotifyExpChangeS2C,omitempty"`
	GamerGetRealTimeRankS2C         *GamerGetRealTimeRankS2C         `protobuf:"bytes,49,opt,name=gamerGetRealTimeRankS2C" json:"gamerGetRealTimeRankS2C,omitempty"`
	GamerCheckPVPBattleS2C          *GamerCheckPVPBattleS2C          `protobuf:"bytes,50,opt,name=gamerCheckPVPBattleS2C" json:"gamerCheckPVPBattleS2C,omitempty"`
	GamerUploadWXInfoS2C            *GamerUploadWXInfoS2C            `protobuf:"bytes,51,opt,name=gamerUploadWXInfoS2C" json:"gamerUploadWXInfoS2C,omitempty"`
	RoomListS2C                     *RoomListS2C                     `protobuf:"bytes,52,opt,name=roomListS2C" json:"roomListS2C,omitempty"`
	GamerNewRoomS2C                 *GamerNewRoomS2C                 `protobuf:"bytes,53,opt,name=gamerNewRoomS2C" json:"gamerNewRoomS2C,omitempty"`
	GamerAddRoomS2C                 *GamerAddRoomS2C                 `protobuf:"bytes,54,opt,name=gamerAddRoomS2C" json:"gamerAddRoomS2C,omitempty"`
	GamerNotifyAddRoomS2C           *GamerNotifyAddRoomS2C           `protobuf:"bytes,55,opt,name=gamerNotifyAddRoomS2C" json:"gamerNotifyAddRoomS2C,omitempty"`
	GamerLeaveRoomS2C               *GamerLeaveRoomS2C               `protobuf:"bytes,56,opt,name=gamerLeaveRoomS2C" json:"gamerLeaveRoomS2C,omitempty"`
	GamerNotifyLeaveRoomS2C         *GamerNotifyLeaveRoomS2C         `protobuf:"bytes,57,opt,name=gamerNotifyLeaveRoomS2C" json:"gamerNotifyLeaveRoomS2C,omitempty"`
	GamerNotifyRoomStateChangeS2C   *GamerNotifyRoomStateChangeS2C   `protobuf:"bytes,58,opt,name=gamerNotifyRoomStateChangeS2C" json:"gamerNotifyRoomStateChangeS2C,omitempty"`
	GamerNotifyRoomInfoChangeS2C    *GamerNotifyRoomInfoChangeS2C    `protobuf:"bytes,59,opt,name=gamerNotifyRoomInfoChangeS2C" json:"gamerNotifyRoomInfoChangeS2C,omitempty"`
	GamerChangeReadyInRoomS2C       *GamerChangeReadyInRoomS2C       `protobuf:"bytes,60,opt,name=gamerChangeReadyInRoomS2C" json:"gamerChangeReadyInRoomS2C,omitempty"`
	GamerNotifyChangeReadyInRoomS2C *GamerNotifyChangeReadyInRoomS2C `protobuf:"bytes,61,opt,name=gamerNotifyChangeReadyInRoomS2C" json:"gamerNotifyChangeReadyInRoomS2C,omitempty"`
	GamerMatchS2C                   *GamerMatchS2C                   `protobuf:"bytes,62,opt,name=gamerMatchS2C" json:"gamerMatchS2C,omitempty"`
	GamerCancelMatchS2C             *GamerCancelMatchS2C             `protobuf:"bytes,63,opt,name=gamerCancelMatchS2C" json:"gamerCancelMatchS2C,omitempty"`
	GamerNotifyMatchInfoS2C         *GamerNotifyMatchInfoS2C         `protobuf:"bytes,64,opt,name=gamerNotifyMatchInfoS2C" json:"gamerNotifyMatchInfoS2C,omitempty"`
	GamerGetRewardS2C               *GamerGetRewardS2C               `protobuf:"bytes,65,opt,name=gamerGetRewardS2C" json:"gamerGetRewardS2C,omitempty"`
	GamerUseIconS2C                 *GamerUseIconS2C                 `protobuf:"bytes,66,opt,name=gamerUseIconS2C" json:"gamerUseIconS2C,omitempty"`
	GamerNotifyGashaponInfoS2C      *GamerNotifyGashaponInfoS2C      `protobuf:"bytes,67,opt,name=gamerNotifyGashaponInfoS2C" json:"gamerNotifyGashaponInfoS2C,omitempty"`
	GamerExtractGashaponS2C         *GamerExtractGashaponS2C         `protobuf:"bytes,68,opt,name=gamerExtractGashaponS2C" json:"gamerExtractGashaponS2C,omitempty"`
	GamerGetAllowanceS2C            *GamerGetAllowanceS2C            `protobuf:"bytes,69,opt,name=gamerGetAllowanceS2C" json:"gamerGetAllowanceS2C,omitempty"`
	GamerNotifyActivitiesS2C        *GamerNotifyActivitiesS2C        `protobuf:"bytes,70,opt,name=gamerNotifyActivitiesS2C" json:"gamerNotifyActivitiesS2C,omitempty"`
	GetActivityRewardS2C            *GetActivityRewardS2C            `protobuf:"bytes,71,opt,name=getActivityRewardS2C" json:"getActivityRewardS2C,omitempty"`
	GMS2C                           *GMS2C                           `protobuf:"bytes,72,opt,name=gMS2C" json:"gMS2C,omitempty"`
	XXX_NoUnkeyedLiteral            struct{}                         `json:"-"`
	XXX_unrecognized                []byte                           `json:"-"`
	XXX_sizecache                   int32                            `json:"-"`
}

func (m *S2C) Reset()         { *m = S2C{} }
func (m *S2C) String() string { return proto.CompactTextString(m) }
func (*S2C) ProtoMessage()    {}
func (*S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_auto_s2c_2c61ec7e96d17e57, []int{0}
}
func (m *S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C.Unmarshal(m, b)
}
func (m *S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C.Marshal(b, m, deterministic)
}
func (dst *S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C.Merge(dst, src)
}
func (m *S2C) XXX_Size() int {
	return xxx_messageInfo_S2C.Size(m)
}
func (m *S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_S2C proto.InternalMessageInfo

func (m *S2C) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *S2C) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *S2C) GetGamerLoginS2C() *GamerLoginS2C {
	if m != nil {
		return m.GamerLoginS2C
	}
	return nil
}

func (m *S2C) GetGamerLoginGetDataS2C() *GamerLoginGetDataS2C {
	if m != nil {
		return m.GamerLoginGetDataS2C
	}
	return nil
}

func (m *S2C) GetServerTimeS2C() *ServerTimeS2C {
	if m != nil {
		return m.ServerTimeS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyLoginOtherS2C() *GamerNotifyLoginOtherS2C {
	if m != nil {
		return m.GamerNotifyLoginOtherS2C
	}
	return nil
}

func (m *S2C) GetGamerSubChatChannelS2C() *GamerSubChatChannelS2C {
	if m != nil {
		return m.GamerSubChatChannelS2C
	}
	return nil
}

func (m *S2C) GetGamerChangeNameS2C() *GamerChangeNameS2C {
	if m != nil {
		return m.GamerChangeNameS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyExpLevelS2C() *GamerNotifyExpLevelS2C {
	if m != nil {
		return m.GamerNotifyExpLevelS2C
	}
	return nil
}

func (m *S2C) GetGamerBuyItemS2C() *GamerBuyItemS2C {
	if m != nil {
		return m.GamerBuyItemS2C
	}
	return nil
}

func (m *S2C) GetGamerGetBackpackS2C() *GamerGetBackpackS2C {
	if m != nil {
		return m.GamerGetBackpackS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyItemS2C() *GamerNotifyItemS2C {
	if m != nil {
		return m.GamerNotifyItemS2C
	}
	return nil
}

func (m *S2C) GetGamerSellItemS2C() *GamerSellItemS2C {
	if m != nil {
		return m.GamerSellItemS2C
	}
	return nil
}

func (m *S2C) GetGamerUseItemS2C() *GamerUseItemS2C {
	if m != nil {
		return m.GamerUseItemS2C
	}
	return nil
}

func (m *S2C) GetGamerCompoundItemS2C() *GamerCompoundItemS2C {
	if m != nil {
		return m.GamerCompoundItemS2C
	}
	return nil
}

func (m *S2C) GetGamerSplitItemS2C() *GamerSplitItemS2C {
	if m != nil {
		return m.GamerSplitItemS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyItemChangeS2C() *GamerNotifyItemChangeS2C {
	if m != nil {
		return m.GamerNotifyItemChangeS2C
	}
	return nil
}

func (m *S2C) GetGamerFriendChatS2C() *GamerFriendChatS2C {
	if m != nil {
		return m.GamerFriendChatS2C
	}
	return nil
}

func (m *S2C) GetGamerWorldChatS2C() *GamerWorldChatS2C {
	if m != nil {
		return m.GamerWorldChatS2C
	}
	return nil
}

func (m *S2C) GetGamerTestChatS2C() *GamerTestChatS2C {
	if m != nil {
		return m.GamerTestChatS2C
	}
	return nil
}

func (m *S2C) GetGamerClubRequestS2C() *GamerClubRequestS2C {
	if m != nil {
		return m.GamerClubRequestS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyNewChatS2C() *GamerNotifyNewChatS2C {
	if m != nil {
		return m.GamerNotifyNewChatS2C
	}
	return nil
}

func (m *S2C) GetGamerNewFriendReqS2C() *GamerNewFriendReqS2C {
	if m != nil {
		return m.GamerNewFriendReqS2C
	}
	return nil
}

func (m *S2C) GetGamerDelFriendS2C() *GamerDelFriendS2C {
	if m != nil {
		return m.GamerDelFriendS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyNewFriendReqS2C() *GamerNotifyNewFriendReqS2C {
	if m != nil {
		return m.GamerNotifyNewFriendReqS2C
	}
	return nil
}

func (m *S2C) GetGamerProcessFriendReqS2C() *GamerProcessFriendReqS2C {
	if m != nil {
		return m.GamerProcessFriendReqS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyNewFriendS2C() *GamerNotifyNewFriendS2C {
	if m != nil {
		return m.GamerNotifyNewFriendS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyDelFriendS2C() *GamerNotifyDelFriendS2C {
	if m != nil {
		return m.GamerNotifyDelFriendS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyMailS2C() *GamerNotifyMailS2C {
	if m != nil {
		return m.GamerNotifyMailS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyNewMailS2C() *GamerNotifyNewMailS2C {
	if m != nil {
		return m.GamerNotifyNewMailS2C
	}
	return nil
}

func (m *S2C) GetGamerGetMailS2C() *GamerGetMailS2C {
	if m != nil {
		return m.GamerGetMailS2C
	}
	return nil
}

func (m *S2C) GetGamerDelMailS2C() *GamerDelMailS2C {
	if m != nil {
		return m.GamerDelMailS2C
	}
	return nil
}

func (m *S2C) GetGamerDelHaveReadMailS2C() *GamerDelHaveReadMailS2C {
	if m != nil {
		return m.GamerDelHaveReadMailS2C
	}
	return nil
}

func (m *S2C) GetGamerOneKeyRcvMailRewardS2C() *GamerOneKeyRcvMailRewardS2C {
	if m != nil {
		return m.GamerOneKeyRcvMailRewardS2C
	}
	return nil
}

func (m *S2C) GetGamerChangeMailStateS2C() *GamerChangeMailStateS2C {
	if m != nil {
		return m.GamerChangeMailStateS2C
	}
	return nil
}

func (m *S2C) GetGamerNewHeroS2C() *GamerNewHeroS2C {
	if m != nil {
		return m.GamerNewHeroS2C
	}
	return nil
}

func (m *S2C) GetGamerUpgradeHeroS2C() *GamerUpgradeHeroS2C {
	if m != nil {
		return m.GamerUpgradeHeroS2C
	}
	return nil
}

func (m *S2C) GetGamerChoseHeroS2C() *GamerChoseHeroS2C {
	if m != nil {
		return m.GamerChoseHeroS2C
	}
	return nil
}

func (m *S2C) GetGamerPVPSyncS2C() *GamerPVPSyncS2C {
	if m != nil {
		return m.GamerPVPSyncS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyGamerMiniS2C() *GamerNotifyGamerMiniS2C {
	if m != nil {
		return m.GamerNotifyGamerMiniS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyPVPSyncS2C() *GamerNotifyPVPSyncS2C {
	if m != nil {
		return m.GamerNotifyPVPSyncS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyNewPVPResultS2C() *GamerNotifyNewPVPResultS2C {
	if m != nil {
		return m.GamerNotifyNewPVPResultS2C
	}
	return nil
}

func (m *S2C) GetGamerPVPStateSyncS2C() *GamerPVPStateSyncS2C {
	if m != nil {
		return m.GamerPVPStateSyncS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyPVPStateSyncS2C() *GamerNotifyPVPStateSyncS2C {
	if m != nil {
		return m.GamerNotifyPVPStateSyncS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyIconChangeS2C() *GamerNotifyIconChangeS2C {
	if m != nil {
		return m.GamerNotifyIconChangeS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyDiamonChangeS2C() *GamerNotifyDiamonChangeS2C {
	if m != nil {
		return m.GamerNotifyDiamonChangeS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyEnergyChangeS2C() *GamerNotifyEnergyChangeS2C {
	if m != nil {
		return m.GamerNotifyEnergyChangeS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyExpChangeS2C() *GamerNotifyExpChangeS2C {
	if m != nil {
		return m.GamerNotifyExpChangeS2C
	}
	return nil
}

func (m *S2C) GetGamerGetRealTimeRankS2C() *GamerGetRealTimeRankS2C {
	if m != nil {
		return m.GamerGetRealTimeRankS2C
	}
	return nil
}

func (m *S2C) GetGamerCheckPVPBattleS2C() *GamerCheckPVPBattleS2C {
	if m != nil {
		return m.GamerCheckPVPBattleS2C
	}
	return nil
}

func (m *S2C) GetGamerUploadWXInfoS2C() *GamerUploadWXInfoS2C {
	if m != nil {
		return m.GamerUploadWXInfoS2C
	}
	return nil
}

func (m *S2C) GetRoomListS2C() *RoomListS2C {
	if m != nil {
		return m.RoomListS2C
	}
	return nil
}

func (m *S2C) GetGamerNewRoomS2C() *GamerNewRoomS2C {
	if m != nil {
		return m.GamerNewRoomS2C
	}
	return nil
}

func (m *S2C) GetGamerAddRoomS2C() *GamerAddRoomS2C {
	if m != nil {
		return m.GamerAddRoomS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyAddRoomS2C() *GamerNotifyAddRoomS2C {
	if m != nil {
		return m.GamerNotifyAddRoomS2C
	}
	return nil
}

func (m *S2C) GetGamerLeaveRoomS2C() *GamerLeaveRoomS2C {
	if m != nil {
		return m.GamerLeaveRoomS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyLeaveRoomS2C() *GamerNotifyLeaveRoomS2C {
	if m != nil {
		return m.GamerNotifyLeaveRoomS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyRoomStateChangeS2C() *GamerNotifyRoomStateChangeS2C {
	if m != nil {
		return m.GamerNotifyRoomStateChangeS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyRoomInfoChangeS2C() *GamerNotifyRoomInfoChangeS2C {
	if m != nil {
		return m.GamerNotifyRoomInfoChangeS2C
	}
	return nil
}

func (m *S2C) GetGamerChangeReadyInRoomS2C() *GamerChangeReadyInRoomS2C {
	if m != nil {
		return m.GamerChangeReadyInRoomS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyChangeReadyInRoomS2C() *GamerNotifyChangeReadyInRoomS2C {
	if m != nil {
		return m.GamerNotifyChangeReadyInRoomS2C
	}
	return nil
}

func (m *S2C) GetGamerMatchS2C() *GamerMatchS2C {
	if m != nil {
		return m.GamerMatchS2C
	}
	return nil
}

func (m *S2C) GetGamerCancelMatchS2C() *GamerCancelMatchS2C {
	if m != nil {
		return m.GamerCancelMatchS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyMatchInfoS2C() *GamerNotifyMatchInfoS2C {
	if m != nil {
		return m.GamerNotifyMatchInfoS2C
	}
	return nil
}

func (m *S2C) GetGamerGetRewardS2C() *GamerGetRewardS2C {
	if m != nil {
		return m.GamerGetRewardS2C
	}
	return nil
}

func (m *S2C) GetGamerUseIconS2C() *GamerUseIconS2C {
	if m != nil {
		return m.GamerUseIconS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyGashaponInfoS2C() *GamerNotifyGashaponInfoS2C {
	if m != nil {
		return m.GamerNotifyGashaponInfoS2C
	}
	return nil
}

func (m *S2C) GetGamerExtractGashaponS2C() *GamerExtractGashaponS2C {
	if m != nil {
		return m.GamerExtractGashaponS2C
	}
	return nil
}

func (m *S2C) GetGamerGetAllowanceS2C() *GamerGetAllowanceS2C {
	if m != nil {
		return m.GamerGetAllowanceS2C
	}
	return nil
}

func (m *S2C) GetGamerNotifyActivitiesS2C() *GamerNotifyActivitiesS2C {
	if m != nil {
		return m.GamerNotifyActivitiesS2C
	}
	return nil
}

func (m *S2C) GetGetActivityRewardS2C() *GetActivityRewardS2C {
	if m != nil {
		return m.GetActivityRewardS2C
	}
	return nil
}

func (m *S2C) GetGMS2C() *GMS2C {
	if m != nil {
		return m.GMS2C
	}
	return nil
}

func init() {
	proto.RegisterType((*S2C)(nil), "S2C")
}

func init() { proto.RegisterFile("auto_s2c.proto", fileDescriptor_auto_s2c_2c61ec7e96d17e57) }

var fileDescriptor_auto_s2c_2c61ec7e96d17e57 = []byte{
	// 1351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x58, 0x79, 0x53, 0xdb, 0x46,
	0x14, 0x1f, 0x9a, 0x92, 0x36, 0x0b, 0x21, 0xb0, 0x5c, 0xe6, 0x4a, 0x68, 0x7a, 0x91, 0x1e, 0x6e,
	0x4b, 0xd2, 0x2b, 0x6d, 0xda, 0x80, 0x0d, 0x86, 0x29, 0x87, 0xe7, 0x11, 0x48, 0x66, 0x3a, 0xd3,
	0xce, 0x22, 0x6f, 0x6c, 0x15, 0x59, 0x72, 0xe4, 0x35, 0xe0, 0x4f, 0xd8, 0xaf, 0xd5, 0xd9, 0x95,
	0xb5, 0x7a, 0x7b, 0xc8, 0xfd, 0x0f, 0xde, 0xef, 0xd0, 0xdb, 0xb7, 0x6f, 0x9f, 0x56, 0x26, 0x33,
	0x6c, 0x20, 0x92, 0xbf, 0xfb, 0xdb, 0x41, 0xb5, 0x97, 0x26, 0x22, 0x59, 0x9d, 0x0e, 0xa2, 0x90,
	0xc7, 0x22, 0xfb, 0xef, 0xf1, 0xbf, 0x4f, 0xc8, 0x9d, 0xb3, 0xed, 0x1a, 0x5d, 0x20, 0x93, 0x3c,
	0x4d, 0x93, 0xb4, 0x32, 0xb1, 0x39, 0xb1, 0x35, 0x09, 0xd9, 0x3f, 0x74, 0x96, 0xdc, 0xb9, 0xe2,
	0xc3, 0xca, 0x7b, 0x9b, 0x13, 0x5b, 0xf7, 0x40, 0xfe, 0x49, 0x9f, 0x91, 0xfb, 0x6d, 0xd6, 0xe5,
	0xe9, 0x51, 0xd2, 0x0e, 0xe3, 0xb3, 0xed, 0x5a, 0xe5, 0xce, 0xe6, 0xc4, 0xd6, 0xd4, 0xf6, 0x4c,
	0xb5, 0x81, 0xa3, 0x60, 0x92, 0xe8, 0x21, 0x59, 0x28, 0x02, 0x0d, 0x2e, 0xea, 0x4c, 0x30, 0x29,
	0x7e, 0x5f, 0x89, 0x17, 0x91, 0xb8, 0x00, 0xc1, 0x2b, 0x91, 0x09, 0xf4, 0x79, 0x7a, 0xcd, 0xd3,
	0x57, 0x61, 0x97, 0x4b, 0x8f, 0xc9, 0x51, 0x02, 0x67, 0x38, 0x0a, 0x26, 0x89, 0x9e, 0x93, 0x8a,
	0x72, 0x3b, 0x49, 0x44, 0xf8, 0x76, 0xa8, 0x3c, 0x4f, 0x45, 0x87, 0xa7, 0xd2, 0xe0, 0xae, 0x32,
	0x58, 0xc9, 0x92, 0xf0, 0x10, 0xa0, 0x54, 0x4a, 0x4f, 0xc9, 0x92, 0xc2, 0xce, 0x06, 0x97, 0xb5,
	0x0e, 0x13, 0xb5, 0x0e, 0x8b, 0x63, 0x1e, 0x49, 0xd3, 0x0f, 0x94, 0xe9, 0x72, 0x66, 0xea, 0xc0,
	0x50, 0x22, 0xa3, 0x35, 0x42, 0x15, 0x22, 0x43, 0x6d, 0x7e, 0xc2, 0xb2, 0x25, 0x7e, 0xa8, 0xcc,
	0xe6, 0x33, 0x33, 0x03, 0x02, 0x0f, 0x5d, 0x67, 0x95, 0x65, 0xbc, 0x77, 0xdb, 0x3b, 0xe2, 0xd7,
	0x59, 0x56, 0xf7, 0x70, 0x56, 0x0e, 0x0c, 0x25, 0x32, 0xfa, 0x9c, 0x3c, 0x50, 0xc8, 0xee, 0x60,
	0x78, 0x28, 0x78, 0x57, 0x3a, 0x11, 0xe5, 0x34, 0x9b, 0x39, 0x15, 0x71, 0xb0, 0x89, 0x74, 0x9f,
	0xcc, 0xab, 0x50, 0x83, 0x8b, 0x5d, 0x16, 0x5c, 0xf5, 0x58, 0x70, 0x25, 0xf5, 0x53, 0x4a, 0xbf,
	0x90, 0xe9, 0x4d, 0x0c, 0x7c, 0x02, 0x5d, 0x99, 0x2c, 0xbb, 0x3c, 0x8d, 0x69, 0x5c, 0x19, 0x03,
	0x02, 0x0f, 0x9d, 0xbe, 0x20, 0xb3, 0x59, 0xe1, 0x79, 0x14, 0xe5, 0x16, 0xf7, 0x95, 0xc5, 0xdc,
	0x68, 0xa7, 0x0a, 0x00, 0x1c, 0xaa, 0xae, 0xc3, 0x79, 0x9f, 0xe7, 0xea, 0x19, 0x5c, 0x87, 0x22,
	0x0e, 0x36, 0x51, 0x1f, 0x81, 0x5a, 0xd2, 0xed, 0x25, 0x83, 0xb8, 0x95, 0x1b, 0x3c, 0xc0, 0x47,
	0xc0, 0x02, 0xc1, 0x2b, 0xa1, 0x2f, 0xc9, 0x5c, 0x96, 0x5a, 0x2f, 0x0a, 0x45, 0xee, 0x33, 0xab,
	0x7c, 0xe8, 0x68, 0x19, 0x08, 0x01, 0x97, 0x6c, 0x1d, 0x07, 0x19, 0xcd, 0x3a, 0x48, 0x1a, 0xcd,
	0xb9, 0xc7, 0xc1, 0x20, 0x40, 0xa9, 0x54, 0xef, 0xd1, 0x7e, 0x1a, 0xf2, 0xb8, 0x25, 0x5b, 0x5b,
	0x1a, 0x52, 0xbc, 0x47, 0x06, 0x04, 0x1e, 0xba, 0x5e, 0xdd, 0xeb, 0x24, 0x8d, 0xb4, 0xc7, 0x3c,
	0x5e, 0x1d, 0x46, 0xc0, 0x25, 0xeb, 0x5d, 0x7e, 0xc5, 0xfb, 0x22, 0x37, 0x58, 0xc0, 0xbb, 0x8c,
	0x00, 0x70, 0xa8, 0xba, 0x63, 0x6b, 0xd1, 0xe0, 0x12, 0xf8, 0xbb, 0x01, 0xef, 0x2b, 0x87, 0x45,
	0xdc, 0xb1, 0x26, 0x06, 0x3e, 0x01, 0x3d, 0x22, 0x8b, 0xa8, 0x52, 0x27, 0xfc, 0x26, 0xcf, 0x65,
	0x49, 0x39, 0x2d, 0xe1, 0x0a, 0x17, 0x28, 0xf8, 0x45, 0xba, 0x7f, 0x4e, 0xf8, 0x4d, 0x56, 0x2f,
	0xe0, 0xef, 0xa4, 0xd9, 0x32, 0xee, 0x1f, 0x0b, 0x04, 0xaf, 0x44, 0x57, 0xb8, 0xce, 0xa3, 0x2c,
	0x2e, 0x7d, 0x2a, 0xb8, 0xc2, 0x18, 0x01, 0x97, 0x4c, 0xff, 0x24, 0xab, 0x66, 0x96, 0x46, 0x4a,
	0x2b, 0xca, 0x6a, 0xcd, 0x5a, 0x9f, 0x91, 0xd8, 0x18, 0xb9, 0x6e, 0xce, 0x66, 0x9a, 0x04, 0xbc,
	0xdf, 0x37, 0xac, 0x57, 0x71, 0x73, 0x7a, 0x08, 0x50, 0x2a, 0xa5, 0x40, 0x96, 0x7d, 0x0f, 0x95,
	0xae, 0x6b, 0xca, 0xb5, 0xe2, 0x4d, 0x58, 0x9a, 0x96, 0x09, 0x2d, 0x4f, 0xa3, 0x9e, 0xeb, 0xae,
	0xa7, 0x51, 0xd5, 0x32, 0xa1, 0x35, 0xe8, 0x8e, 0x59, 0xa8, 0x26, 0xf7, 0x86, 0x3b, 0xe8, 0x46,
	0x10, 0x78, 0xe8, 0x6e, 0xef, 0xe5, 0x3e, 0x0f, 0xbd, 0xbd, 0x97, 0x5b, 0xf9, 0x45, 0x7a, 0xee,
	0x35, 0xb8, 0xc8, 0x7d, 0x1e, 0xe1, 0xb9, 0x57, 0xc4, 0xc1, 0x26, 0x6a, 0x6d, 0x9d, 0x47, 0xb9,
	0x76, 0x13, 0x6b, 0x8b, 0x38, 0xd8, 0x44, 0x5d, 0xde, 0x3a, 0x8f, 0x0e, 0xd8, 0x35, 0x07, 0xce,
	0x5a, 0xb9, 0xc7, 0x47, 0xb8, 0xbc, 0x2e, 0x0e, 0x65, 0x42, 0xfa, 0x17, 0x59, 0x53, 0xd0, 0x69,
	0xcc, 0xff, 0xe0, 0x43, 0x08, 0xae, 0x25, 0x00, 0xfc, 0x86, 0xa5, 0x6a, 0xdb, 0x1e, 0x2b, 0xdf,
	0xf5, 0xcc, 0xd7, 0xcf, 0x81, 0x71, 0x06, 0x3a, 0xe7, 0x6c, 0x2a, 0xaa, 0xa7, 0x0a, 0x26, 0xd4,
	0x64, 0xfd, 0x18, 0xe7, 0xec, 0xe2, 0x50, 0x26, 0xd4, 0x35, 0x3c, 0xe1, 0x37, 0x07, 0x3c, 0x4d,
	0xa4, 0xd7, 0x27, 0xb8, 0x86, 0x45, 0x1c, 0x6c, 0xa2, 0x9e, 0x66, 0xe7, 0xbd, 0x76, 0xca, 0x5a,
	0x3c, 0xd7, 0x7f, 0x8a, 0xa7, 0x99, 0x89, 0x81, 0x4f, 0xa0, 0x87, 0x46, 0xad, 0x93, 0xf4, 0xb5,
	0xcb, 0x67, 0x78, 0x68, 0x60, 0x04, 0x5c, 0xb2, 0x5e, 0x45, 0xf3, 0xa2, 0x79, 0x36, 0x8c, 0x03,
	0xa9, 0xff, 0x1c, 0xaf, 0xa2, 0x88, 0x83, 0x4d, 0xb4, 0x0e, 0x9a, 0xa2, 0x1f, 0x87, 0x71, 0x28,
	0x3d, 0xb6, 0xdc, 0x83, 0x86, 0x71, 0x28, 0x13, 0x5a, 0x67, 0x04, 0x65, 0xf5, 0xc4, 0x3d, 0x23,
	0x28, 0x37, 0xbf, 0xc8, 0x1d, 0x89, 0xcd, 0x8b, 0x26, 0xf0, 0xfe, 0x20, 0x52, 0x23, 0xff, 0x0b,
	0xef, 0x48, 0xc4, 0x14, 0x18, 0x23, 0xd7, 0xc3, 0x5f, 0x3e, 0x4f, 0x35, 0xc5, 0x28, 0xd3, 0x2f,
	0xf1, 0xf0, 0xb7, 0x40, 0xf0, 0x4a, 0xac, 0x3c, 0x6d, 0xc3, 0xaf, 0xdc, 0x3c, 0x6d, 0xdb, 0x31,
	0x72, 0xfb, 0x5e, 0x11, 0x24, 0x71, 0x71, 0xaf, 0xf8, 0xda, 0x73, 0xaf, 0xc0, 0x04, 0x28, 0x95,
	0x5a, 0x39, 0xd7, 0x43, 0xd6, 0xc5, 0xc6, 0x55, 0x37, 0x67, 0x8b, 0x02, 0x63, 0xe4, 0x96, 0xf9,
	0x5e, 0xcc, 0xd3, 0xf6, 0xb0, 0x30, 0xff, 0xc6, 0x35, 0xb7, 0x28, 0x30, 0x46, 0x6e, 0xf5, 0xed,
	0xde, 0x6d, 0xaf, 0x70, 0xfe, 0xd6, 0xed, 0x5b, 0x8c, 0x43, 0x99, 0x50, 0x7b, 0x36, 0xb8, 0x00,
	0xce, 0x22, 0xf9, 0x89, 0x03, 0x2c, 0x56, 0xb7, 0xea, 0xef, 0xb0, 0xa7, 0x8b, 0x43, 0x99, 0x50,
	0x7f, 0x32, 0xd4, 0x3a, 0x3c, 0xb8, 0x6a, 0x5e, 0x34, 0x77, 0x99, 0x10, 0x91, 0x4a, 0x73, 0x1b,
	0x7f, 0x32, 0x38, 0x30, 0x94, 0xc8, 0x74, 0xc7, 0x9e, 0xf7, 0xa2, 0x84, 0xb5, 0x5e, 0xbf, 0x39,
	0x8c, 0xdf, 0xaa, 0x89, 0xf1, 0x14, 0x77, 0xac, 0x05, 0x82, 0x57, 0x42, 0xab, 0x64, 0x2a, 0x4d,
	0x92, 0xee, 0x51, 0x98, 0xdd, 0xc3, 0x9e, 0x29, 0x87, 0xe9, 0x2a, 0x14, 0x31, 0xc0, 0x04, 0x3c,
	0x2d, 0x25, 0x47, 0x6a, 0xbe, 0xb7, 0xa6, 0xe5, 0x28, 0x0e, 0x36, 0x51, 0x6b, 0x77, 0x5a, 0xad,
	0x5c, 0xfb, 0x03, 0xd6, 0x16, 0x71, 0xb0, 0x89, 0xd6, 0x3c, 0x41, 0x0e, 0x3f, 0xba, 0xf3, 0x04,
	0xf9, 0xf8, 0x45, 0x7a, 0xde, 0x1e, 0x71, 0xf9, 0x02, 0x1b, 0x39, 0xfd, 0x84, 0xe7, 0x2d, 0x46,
	0xc0, 0x25, 0x5b, 0xbd, 0x67, 0xf8, 0xfc, 0xec, 0xf6, 0x9e, 0xe1, 0x56, 0x26, 0xa4, 0x2d, 0xb2,
	0x81, 0x20, 0x15, 0x95, 0xe7, 0xbf, 0xe8, 0xea, 0xe7, 0xca, 0xf9, 0x21, 0x76, 0x76, 0x59, 0x30,
	0xde, 0x84, 0x32, 0xb2, 0x6e, 0x11, 0x64, 0x2f, 0x14, 0x0f, 0xf9, 0x45, 0x3d, 0x64, 0xc3, 0x7e,
	0x88, 0x41, 0x82, 0xb1, 0x16, 0xf4, 0x0d, 0x59, 0x41, 0x6f, 0x5b, 0x79, 0x41, 0x18, 0x1e, 0xc6,
	0x79, 0x79, 0x7e, 0x55, 0xfe, 0xab, 0xf8, 0x45, 0x6d, 0x32, 0xa0, 0x5c, 0x4c, 0xff, 0x21, 0x8f,
	0xd0, 0x93, 0xbd, 0xfe, 0x2f, 0x94, 0xff, 0x26, 0xce, 0xdf, 0xfb, 0x94, 0xff, 0x33, 0xd2, 0xbf,
	0xc6, 0x1c, 0x33, 0x11, 0x74, 0xa4, 0xf3, 0x6f, 0xf8, 0xd7, 0x98, 0x3c, 0x0a, 0x26, 0xa9, 0xf8,
	0xc0, 0x61, 0x71, 0x20, 0x2f, 0x5b, 0x23, 0xed, 0xef, 0xc6, 0x07, 0x8e, 0x81, 0x81, 0x4f, 0x60,
	0x35, 0x98, 0x0a, 0xe7, 0xc7, 0xfc, 0xa5, 0xdb, 0x60, 0x18, 0x87, 0x32, 0xa1, 0x6e, 0x7b, 0x35,
	0xa3, 0xf2, 0x4b, 0xd9, 0x0e, 0x6e, 0x7b, 0x8c, 0x80, 0x4b, 0x36, 0x3e, 0xd2, 0x83, 0x44, 0xfd,
	0x46, 0xb5, 0x6b, 0x7f, 0xa4, 0x67, 0x71, 0xb0, 0x89, 0xd6, 0xbb, 0xa0, 0xc1, 0xfa, 0x1d, 0xd6,
	0x4b, 0xe2, 0x7c, 0x51, 0x35, 0xf7, 0x5d, 0x60, 0x51, 0x60, 0x8c, 0x5c, 0x97, 0x6b, 0xef, 0x56,
	0xa4, 0x2c, 0x10, 0x39, 0x2c, 0x9d, 0xeb, 0xb8, 0x5c, 0x2e, 0x0e, 0x65, 0x42, 0x3d, 0x66, 0x1b,
	0x5c, 0xec, 0x44, 0x51, 0x72, 0x23, 0x37, 0x48, 0x1a, 0xee, 0xe1, 0x31, 0x6b, 0x81, 0xe0, 0x95,
	0x58, 0xef, 0xee, 0x9d, 0x40, 0x84, 0xd7, 0xa1, 0x08, 0x79, 0x5f, 0xda, 0xed, 0xbb, 0xef, 0x6e,
	0x83, 0x00, 0xa5, 0x52, 0x95, 0x21, 0x17, 0xa3, 0xd8, 0xb0, 0xd8, 0xd3, 0x46, 0x9e, 0xa1, 0x07,
	0x04, 0xaf, 0x84, 0xae, 0x93, 0xc9, 0xf6, 0xb1, 0xd4, 0x1e, 0x28, 0xed, 0xdd, 0x6a, 0x43, 0xfe,
	0x07, 0x59, 0xf0, 0xf2, 0xae, 0xfa, 0x41, 0xf3, 0xe9, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x64,
	0xd0, 0x7b, 0xa7, 0xf0, 0x14, 0x00, 0x00,
}
