// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// C2S消息解析前的key
// 用于区分logic消息和pvp消息
// 默认到logic
// 填了表示session转到pvp
type PrevC2S struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrevC2S) Reset()         { *m = PrevC2S{} }
func (m *PrevC2S) String() string { return proto.CompactTextString(m) }
func (*PrevC2S) ProtoMessage()    {}
func (*PrevC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{0}
}
func (m *PrevC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrevC2S.Unmarshal(m, b)
}
func (m *PrevC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrevC2S.Marshal(b, m, deterministic)
}
func (dst *PrevC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrevC2S.Merge(dst, src)
}
func (m *PrevC2S) XXX_Size() int {
	return xxx_messageInfo_PrevC2S.Size(m)
}
func (m *PrevC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_PrevC2S.DiscardUnknown(m)
}

var xxx_messageInfo_PrevC2S proto.InternalMessageInfo

func (m *PrevC2S) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// 服务器时间
type ServerTime struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Year                 int32    `protobuf:"varint,2,opt,name=year" json:"year,omitempty"`
	Month                int32    `protobuf:"varint,3,opt,name=month" json:"month,omitempty"`
	Day                  int32    `protobuf:"varint,4,opt,name=day" json:"day,omitempty"`
	Hour                 int32    `protobuf:"varint,5,opt,name=hour" json:"hour,omitempty"`
	Minute               int32    `protobuf:"varint,6,opt,name=minute" json:"minute,omitempty"`
	Second               int32    `protobuf:"varint,7,opt,name=second" json:"second,omitempty"`
	Timezone             int32    `protobuf:"varint,8,opt,name=timezone" json:"timezone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerTime) Reset()         { *m = ServerTime{} }
func (m *ServerTime) String() string { return proto.CompactTextString(m) }
func (*ServerTime) ProtoMessage()    {}
func (*ServerTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{1}
}
func (m *ServerTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerTime.Unmarshal(m, b)
}
func (m *ServerTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerTime.Marshal(b, m, deterministic)
}
func (dst *ServerTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerTime.Merge(dst, src)
}
func (m *ServerTime) XXX_Size() int {
	return xxx_messageInfo_ServerTime.Size(m)
}
func (m *ServerTime) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerTime.DiscardUnknown(m)
}

var xxx_messageInfo_ServerTime proto.InternalMessageInfo

func (m *ServerTime) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ServerTime) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *ServerTime) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *ServerTime) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *ServerTime) GetHour() int32 {
	if m != nil {
		return m.Hour
	}
	return 0
}

func (m *ServerTime) GetMinute() int32 {
	if m != nil {
		return m.Minute
	}
	return 0
}

func (m *ServerTime) GetSecond() int32 {
	if m != nil {
		return m.Second
	}
	return 0
}

func (m *ServerTime) GetTimezone() int32 {
	if m != nil {
		return m.Timezone
	}
	return 0
}

type GameItem struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	ObtainTime           int64    `protobuf:"varint,4,opt,name=obtainTime" json:"obtainTime,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameItem) Reset()         { *m = GameItem{} }
func (m *GameItem) String() string { return proto.CompactTextString(m) }
func (*GameItem) ProtoMessage()    {}
func (*GameItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{2}
}
func (m *GameItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameItem.Unmarshal(m, b)
}
func (m *GameItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameItem.Marshal(b, m, deterministic)
}
func (dst *GameItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameItem.Merge(dst, src)
}
func (m *GameItem) XXX_Size() int {
	return xxx_messageInfo_GameItem.Size(m)
}
func (m *GameItem) XXX_DiscardUnknown() {
	xxx_messageInfo_GameItem.DiscardUnknown(m)
}

var xxx_messageInfo_GameItem proto.InternalMessageInfo

func (m *GameItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GameItem) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *GameItem) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GameItem) GetObtainTime() int64 {
	if m != nil {
		return m.ObtainTime
	}
	return 0
}

func (m *GameItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 时间记录
type TimeRecord struct {
	LastSign             int64    `protobuf:"varint,3,opt,name=lastSign" json:"lastSign,omitempty"`
	LastGetPVPResult     int64    `protobuf:"varint,6,opt,name=lastGetPVPResult" json:"lastGetPVPResult,omitempty"`
	LastWeekRec          int64    `protobuf:"varint,7,opt,name=lastWeekRec" json:"lastWeekRec,omitempty"`
	TotalTime            int32    `protobuf:"varint,8,opt,name=totalTime" json:"totalTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeRecord) Reset()         { *m = TimeRecord{} }
func (m *TimeRecord) String() string { return proto.CompactTextString(m) }
func (*TimeRecord) ProtoMessage()    {}
func (*TimeRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{3}
}
func (m *TimeRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeRecord.Unmarshal(m, b)
}
func (m *TimeRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeRecord.Marshal(b, m, deterministic)
}
func (dst *TimeRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeRecord.Merge(dst, src)
}
func (m *TimeRecord) XXX_Size() int {
	return xxx_messageInfo_TimeRecord.Size(m)
}
func (m *TimeRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeRecord.DiscardUnknown(m)
}

var xxx_messageInfo_TimeRecord proto.InternalMessageInfo

func (m *TimeRecord) GetLastSign() int64 {
	if m != nil {
		return m.LastSign
	}
	return 0
}

func (m *TimeRecord) GetLastGetPVPResult() int64 {
	if m != nil {
		return m.LastGetPVPResult
	}
	return 0
}

func (m *TimeRecord) GetLastWeekRec() int64 {
	if m != nil {
		return m.LastWeekRec
	}
	return 0
}

func (m *TimeRecord) GetTotalTime() int32 {
	if m != nil {
		return m.TotalTime
	}
	return 0
}

// 次数记录
type NumberRecord struct {
	Elo                  int32    `protobuf:"varint,1,opt,name=elo" json:"elo,omitempty"`
	NormWin              int32    `protobuf:"varint,2,opt,name=normWin" json:"normWin,omitempty"`
	TotalSignIn          int32    `protobuf:"varint,3,opt,name=totalSignIn" json:"totalSignIn,omitempty"`
	WeekTotalSign        int32    `protobuf:"varint,4,opt,name=weekTotalSign" json:"weekTotalSign,omitempty"`
	WeekGoldGet          int32    `protobuf:"varint,5,opt,name=weekGoldGet" json:"weekGoldGet,omitempty"`
	WeekExpGet           int32    `protobuf:"varint,6,opt,name=weekExpGet" json:"weekExpGet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NumberRecord) Reset()         { *m = NumberRecord{} }
func (m *NumberRecord) String() string { return proto.CompactTextString(m) }
func (*NumberRecord) ProtoMessage()    {}
func (*NumberRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{4}
}
func (m *NumberRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumberRecord.Unmarshal(m, b)
}
func (m *NumberRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumberRecord.Marshal(b, m, deterministic)
}
func (dst *NumberRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumberRecord.Merge(dst, src)
}
func (m *NumberRecord) XXX_Size() int {
	return xxx_messageInfo_NumberRecord.Size(m)
}
func (m *NumberRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_NumberRecord.DiscardUnknown(m)
}

var xxx_messageInfo_NumberRecord proto.InternalMessageInfo

func (m *NumberRecord) GetElo() int32 {
	if m != nil {
		return m.Elo
	}
	return 0
}

func (m *NumberRecord) GetNormWin() int32 {
	if m != nil {
		return m.NormWin
	}
	return 0
}

func (m *NumberRecord) GetTotalSignIn() int32 {
	if m != nil {
		return m.TotalSignIn
	}
	return 0
}

func (m *NumberRecord) GetWeekTotalSign() int32 {
	if m != nil {
		return m.WeekTotalSign
	}
	return 0
}

func (m *NumberRecord) GetWeekGoldGet() int32 {
	if m != nil {
		return m.WeekGoldGet
	}
	return 0
}

func (m *NumberRecord) GetWeekExpGet() int32 {
	if m != nil {
		return m.WeekExpGet
	}
	return 0
}

type WXInfo struct {
	AvatarUrl            string   `protobuf:"bytes,1,opt,name=avatar_url,json=avatarUrl" json:"avatar_url,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city" json:"city,omitempty"`
	Gender               int32    `protobuf:"varint,3,opt,name=gender" json:"gender,omitempty"`
	OpenId               string   `protobuf:"bytes,4,opt,name=open_id,json=openId" json:"open_id,omitempty"`
	Language             string   `protobuf:"bytes,5,opt,name=language" json:"language,omitempty"`
	NickName             string   `protobuf:"bytes,6,opt,name=nick_name,json=nickName" json:"nick_name,omitempty"`
	Province             string   `protobuf:"bytes,7,opt,name=province" json:"province,omitempty"`
	UnionId              string   `protobuf:"bytes,8,opt,name=union_id,json=unionId" json:"union_id,omitempty"`
	Country              string   `protobuf:"bytes,9,opt,name=country" json:"country,omitempty"`
	SessionId            string   `protobuf:"bytes,10,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	Sign                 string   `protobuf:"bytes,11,opt,name=sign" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WXInfo) Reset()         { *m = WXInfo{} }
func (m *WXInfo) String() string { return proto.CompactTextString(m) }
func (*WXInfo) ProtoMessage()    {}
func (*WXInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{5}
}
func (m *WXInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WXInfo.Unmarshal(m, b)
}
func (m *WXInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WXInfo.Marshal(b, m, deterministic)
}
func (dst *WXInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WXInfo.Merge(dst, src)
}
func (m *WXInfo) XXX_Size() int {
	return xxx_messageInfo_WXInfo.Size(m)
}
func (m *WXInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WXInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WXInfo proto.InternalMessageInfo

func (m *WXInfo) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *WXInfo) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *WXInfo) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *WXInfo) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *WXInfo) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *WXInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *WXInfo) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *WXInfo) GetUnionId() string {
	if m != nil {
		return m.UnionId
	}
	return ""
}

func (m *WXInfo) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *WXInfo) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *WXInfo) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

// 玩家主信息
type GamerMain struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid" json:"uid,omitempty"`
	Lsid                 int32    `protobuf:"varint,3,opt,name=lsid" json:"lsid,omitempty"`
	Psid                 int32    `protobuf:"varint,4,opt,name=psid" json:"psid,omitempty"`
	State                int32    `protobuf:"varint,5,opt,name=state" json:"state,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	Level                int32    `protobuf:"varint,7,opt,name=level" json:"level,omitempty"`
	Session              string   `protobuf:"bytes,8,opt,name=session" json:"session,omitempty"`
	Create               int64    `protobuf:"varint,9,opt,name=create" json:"create,omitempty"`
	LastLogin            int64    `protobuf:"varint,10,opt,name=lastLogin" json:"lastLogin,omitempty"`
	LastLogout           int64    `protobuf:"varint,11,opt,name=lastLogout" json:"lastLogout,omitempty"`
	TypeId               int32    `protobuf:"varint,12,opt,name=typeId" json:"typeId,omitempty"`
	Icon                 int32    `protobuf:"varint,13,opt,name=icon" json:"icon,omitempty"`
	Diamond              int32    `protobuf:"varint,14,opt,name=diamond" json:"diamond,omitempty"`
	Exp                  int32    `protobuf:"varint,15,opt,name=exp" json:"exp,omitempty"`
	PvpSession           string   `protobuf:"bytes,16,opt,name=pvpSession" json:"pvpSession,omitempty"`
	Avatar               string   `protobuf:"bytes,17,opt,name=avatar" json:"avatar,omitempty"`
	Energy               int32    `protobuf:"varint,18,opt,name=energy" json:"energy,omitempty"`
	IsNewbie             bool     `protobuf:"varint,19,opt,name=isNewbie" json:"isNewbie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GamerMain) Reset()         { *m = GamerMain{} }
func (m *GamerMain) String() string { return proto.CompactTextString(m) }
func (*GamerMain) ProtoMessage()    {}
func (*GamerMain) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{6}
}
func (m *GamerMain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamerMain.Unmarshal(m, b)
}
func (m *GamerMain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamerMain.Marshal(b, m, deterministic)
}
func (dst *GamerMain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamerMain.Merge(dst, src)
}
func (m *GamerMain) XXX_Size() int {
	return xxx_messageInfo_GamerMain.Size(m)
}
func (m *GamerMain) XXX_DiscardUnknown() {
	xxx_messageInfo_GamerMain.DiscardUnknown(m)
}

var xxx_messageInfo_GamerMain proto.InternalMessageInfo

func (m *GamerMain) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GamerMain) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *GamerMain) GetLsid() int32 {
	if m != nil {
		return m.Lsid
	}
	return 0
}

func (m *GamerMain) GetPsid() int32 {
	if m != nil {
		return m.Psid
	}
	return 0
}

func (m *GamerMain) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *GamerMain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GamerMain) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *GamerMain) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *GamerMain) GetCreate() int64 {
	if m != nil {
		return m.Create
	}
	return 0
}

func (m *GamerMain) GetLastLogin() int64 {
	if m != nil {
		return m.LastLogin
	}
	return 0
}

func (m *GamerMain) GetLastLogout() int64 {
	if m != nil {
		return m.LastLogout
	}
	return 0
}

func (m *GamerMain) GetTypeId() int32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *GamerMain) GetIcon() int32 {
	if m != nil {
		return m.Icon
	}
	return 0
}

func (m *GamerMain) GetDiamond() int32 {
	if m != nil {
		return m.Diamond
	}
	return 0
}

func (m *GamerMain) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *GamerMain) GetPvpSession() string {
	if m != nil {
		return m.PvpSession
	}
	return ""
}

func (m *GamerMain) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *GamerMain) GetEnergy() int32 {
	if m != nil {
		return m.Energy
	}
	return 0
}

func (m *GamerMain) GetIsNewbie() bool {
	if m != nil {
		return m.IsNewbie
	}
	return false
}

type GamerMini struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Level                int32    `protobuf:"varint,3,opt,name=level" json:"level,omitempty"`
	Lsid                 int32    `protobuf:"varint,4,opt,name=lsid" json:"lsid,omitempty"`
	State                int32    `protobuf:"varint,5,opt,name=state" json:"state,omitempty"`
	Avatar               string   `protobuf:"bytes,6,opt,name=avatar" json:"avatar,omitempty"`
	Channel              string   `protobuf:"bytes,7,opt,name=channel" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GamerMini) Reset()         { *m = GamerMini{} }
func (m *GamerMini) String() string { return proto.CompactTextString(m) }
func (*GamerMini) ProtoMessage()    {}
func (*GamerMini) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{7}
}
func (m *GamerMini) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamerMini.Unmarshal(m, b)
}
func (m *GamerMini) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamerMini.Marshal(b, m, deterministic)
}
func (dst *GamerMini) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamerMini.Merge(dst, src)
}
func (m *GamerMini) XXX_Size() int {
	return xxx_messageInfo_GamerMini.Size(m)
}
func (m *GamerMini) XXX_DiscardUnknown() {
	xxx_messageInfo_GamerMini.DiscardUnknown(m)
}

var xxx_messageInfo_GamerMini proto.InternalMessageInfo

func (m *GamerMini) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GamerMini) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GamerMini) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *GamerMini) GetLsid() int32 {
	if m != nil {
		return m.Lsid
	}
	return 0
}

func (m *GamerMini) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *GamerMini) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *GamerMini) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

// 好友请求
type GamerFriendRequest struct {
	Id                   int32      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Msg                  string     `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Time                 int64      `protobuf:"varint,3,opt,name=time" json:"time,omitempty"`
	GamerInfo            *GamerMini `protobuf:"bytes,5,opt,name=gamerInfo" json:"gamerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GamerFriendRequest) Reset()         { *m = GamerFriendRequest{} }
func (m *GamerFriendRequest) String() string { return proto.CompactTextString(m) }
func (*GamerFriendRequest) ProtoMessage()    {}
func (*GamerFriendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{8}
}
func (m *GamerFriendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamerFriendRequest.Unmarshal(m, b)
}
func (m *GamerFriendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamerFriendRequest.Marshal(b, m, deterministic)
}
func (dst *GamerFriendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamerFriendRequest.Merge(dst, src)
}
func (m *GamerFriendRequest) XXX_Size() int {
	return xxx_messageInfo_GamerFriendRequest.Size(m)
}
func (m *GamerFriendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GamerFriendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GamerFriendRequest proto.InternalMessageInfo

func (m *GamerFriendRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GamerFriendRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GamerFriendRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *GamerFriendRequest) GetGamerInfo() *GamerMini {
	if m != nil {
		return m.GamerInfo
	}
	return nil
}

// 拉黑的玩家
type GamerBlack struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GamerBlack) Reset()         { *m = GamerBlack{} }
func (m *GamerBlack) String() string { return proto.CompactTextString(m) }
func (*GamerBlack) ProtoMessage()    {}
func (*GamerBlack) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{9}
}
func (m *GamerBlack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamerBlack.Unmarshal(m, b)
}
func (m *GamerBlack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamerBlack.Marshal(b, m, deterministic)
}
func (dst *GamerBlack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamerBlack.Merge(dst, src)
}
func (m *GamerBlack) XXX_Size() int {
	return xxx_messageInfo_GamerBlack.Size(m)
}
func (m *GamerBlack) XXX_DiscardUnknown() {
	xxx_messageInfo_GamerBlack.DiscardUnknown(m)
}

var xxx_messageInfo_GamerBlack proto.InternalMessageInfo

func (m *GamerBlack) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GamerFriend struct {
	Id                   int32      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Time                 int64      `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	GamerInfo            *GamerMini `protobuf:"bytes,5,opt,name=gamerInfo" json:"gamerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GamerFriend) Reset()         { *m = GamerFriend{} }
func (m *GamerFriend) String() string { return proto.CompactTextString(m) }
func (*GamerFriend) ProtoMessage()    {}
func (*GamerFriend) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{10}
}
func (m *GamerFriend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamerFriend.Unmarshal(m, b)
}
func (m *GamerFriend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamerFriend.Marshal(b, m, deterministic)
}
func (dst *GamerFriend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamerFriend.Merge(dst, src)
}
func (m *GamerFriend) XXX_Size() int {
	return xxx_messageInfo_GamerFriend.Size(m)
}
func (m *GamerFriend) XXX_DiscardUnknown() {
	xxx_messageInfo_GamerFriend.DiscardUnknown(m)
}

var xxx_messageInfo_GamerFriend proto.InternalMessageInfo

func (m *GamerFriend) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GamerFriend) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *GamerFriend) GetGamerInfo() *GamerMini {
	if m != nil {
		return m.GamerInfo
	}
	return nil
}

type ChatData struct {
	From                 int32      `protobuf:"varint,1,opt,name=from" json:"from,omitempty"`
	Time                 int64      `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	Msg                  string     `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
	Channel              int32      `protobuf:"varint,4,opt,name=channel" json:"channel,omitempty"`
	GamerInfo            *GamerMini `protobuf:"bytes,5,opt,name=gamerInfo" json:"gamerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ChatData) Reset()         { *m = ChatData{} }
func (m *ChatData) String() string { return proto.CompactTextString(m) }
func (*ChatData) ProtoMessage()    {}
func (*ChatData) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{11}
}
func (m *ChatData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatData.Unmarshal(m, b)
}
func (m *ChatData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatData.Marshal(b, m, deterministic)
}
func (dst *ChatData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatData.Merge(dst, src)
}
func (m *ChatData) XXX_Size() int {
	return xxx_messageInfo_ChatData.Size(m)
}
func (m *ChatData) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatData.DiscardUnknown(m)
}

var xxx_messageInfo_ChatData proto.InternalMessageInfo

func (m *ChatData) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *ChatData) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ChatData) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ChatData) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *ChatData) GetGamerInfo() *GamerMini {
	if m != nil {
		return m.GamerInfo
	}
	return nil
}

// 邮件
type Mail struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	MailType             MailType    `protobuf:"varint,2,opt,name=mailType,enum=MailType" json:"mailType,omitempty"`
	Time                 int64       `protobuf:"varint,3,opt,name=time" json:"time,omitempty"`
	Theme                string      `protobuf:"bytes,4,opt,name=theme" json:"theme,omitempty"`
	Msg                  string      `protobuf:"bytes,5,opt,name=msg" json:"msg,omitempty"`
	Attachments          []*GameItem `protobuf:"bytes,6,rep,name=attachments" json:"attachments,omitempty"`
	State                MailState   `protobuf:"varint,7,opt,name=state,enum=MailState" json:"state,omitempty"`
	ServerId             int32       `protobuf:"varint,9,opt,name=serverId" json:"serverId,omitempty"`
	SenderId             int32       `protobuf:"varint,10,opt,name=senderId" json:"senderId,omitempty"`
	Level                int32       `protobuf:"varint,11,opt,name=level" json:"level,omitempty"`
	EndTime              int64       `protobuf:"varint,12,opt,name=endTime" json:"endTime,omitempty"`
	IsDel                int32       `protobuf:"varint,13,opt,name=isDel" json:"isDel,omitempty"`
	CfgId                int32       `protobuf:"varint,14,opt,name=cfgId" json:"cfgId,omitempty"`
	Save                 bool        `protobuf:"varint,15,opt,name=save" json:"save,omitempty"`
	GamerInfo            *GamerMini  `protobuf:"bytes,16,opt,name=gamerInfo" json:"gamerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Mail) Reset()         { *m = Mail{} }
func (m *Mail) String() string { return proto.CompactTextString(m) }
func (*Mail) ProtoMessage()    {}
func (*Mail) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{12}
}
func (m *Mail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mail.Unmarshal(m, b)
}
func (m *Mail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mail.Marshal(b, m, deterministic)
}
func (dst *Mail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mail.Merge(dst, src)
}
func (m *Mail) XXX_Size() int {
	return xxx_messageInfo_Mail.Size(m)
}
func (m *Mail) XXX_DiscardUnknown() {
	xxx_messageInfo_Mail.DiscardUnknown(m)
}

var xxx_messageInfo_Mail proto.InternalMessageInfo

func (m *Mail) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Mail) GetMailType() MailType {
	if m != nil {
		return m.MailType
	}
	return MailType_ActivityMail
}

func (m *Mail) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Mail) GetTheme() string {
	if m != nil {
		return m.Theme
	}
	return ""
}

func (m *Mail) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Mail) GetAttachments() []*GameItem {
	if m != nil {
		return m.Attachments
	}
	return nil
}

func (m *Mail) GetState() MailState {
	if m != nil {
		return m.State
	}
	return MailState_MailUnRead
}

func (m *Mail) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *Mail) GetSenderId() int32 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *Mail) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Mail) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Mail) GetIsDel() int32 {
	if m != nil {
		return m.IsDel
	}
	return 0
}

func (m *Mail) GetCfgId() int32 {
	if m != nil {
		return m.CfgId
	}
	return 0
}

func (m *Mail) GetSave() bool {
	if m != nil {
		return m.Save
	}
	return false
}

func (m *Mail) GetGamerInfo() *GamerMini {
	if m != nil {
		return m.GamerInfo
	}
	return nil
}

// ------------------------------------------------bag
type BagItem struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Time                 int64    `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BagItem) Reset()         { *m = BagItem{} }
func (m *BagItem) String() string { return proto.CompactTextString(m) }
func (*BagItem) ProtoMessage()    {}
func (*BagItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{13}
}
func (m *BagItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BagItem.Unmarshal(m, b)
}
func (m *BagItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BagItem.Marshal(b, m, deterministic)
}
func (dst *BagItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BagItem.Merge(dst, src)
}
func (m *BagItem) XXX_Size() int {
	return xxx_messageInfo_BagItem.Size(m)
}
func (m *BagItem) XXX_DiscardUnknown() {
	xxx_messageInfo_BagItem.DiscardUnknown(m)
}

var xxx_messageInfo_BagItem proto.InternalMessageInfo

func (m *BagItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BagItem) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *BagItem) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// ------------------------------------------------hero
type GamerHero struct {
	Lid                  int32    `protobuf:"varint,1,opt,name=lid" json:"lid,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Level                int32    `protobuf:"varint,3,opt,name=level" json:"level,omitempty"`
	Chose                int32    `protobuf:"varint,4,opt,name=chose" json:"chose,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GamerHero) Reset()         { *m = GamerHero{} }
func (m *GamerHero) String() string { return proto.CompactTextString(m) }
func (*GamerHero) ProtoMessage()    {}
func (*GamerHero) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{14}
}
func (m *GamerHero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamerHero.Unmarshal(m, b)
}
func (m *GamerHero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamerHero.Marshal(b, m, deterministic)
}
func (dst *GamerHero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamerHero.Merge(dst, src)
}
func (m *GamerHero) XXX_Size() int {
	return xxx_messageInfo_GamerHero.Size(m)
}
func (m *GamerHero) XXX_DiscardUnknown() {
	xxx_messageInfo_GamerHero.DiscardUnknown(m)
}

var xxx_messageInfo_GamerHero proto.InternalMessageInfo

func (m *GamerHero) GetLid() int32 {
	if m != nil {
		return m.Lid
	}
	return 0
}

func (m *GamerHero) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GamerHero) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *GamerHero) GetChose() int32 {
	if m != nil {
		return m.Chose
	}
	return 0
}

// ---------------------------------------------------
type GamerMatch struct {
	Mini                 *GamerMini `protobuf:"bytes,1,opt,name=mini" json:"mini,omitempty"`
	Ai                   bool       `protobuf:"varint,2,opt,name=ai" json:"ai,omitempty"`
	Pair                 int32      `protobuf:"varint,3,opt,name=pair" json:"pair,omitempty"`
	Hero                 int32      `protobuf:"varint,4,opt,name=hero" json:"hero,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GamerMatch) Reset()         { *m = GamerMatch{} }
func (m *GamerMatch) String() string { return proto.CompactTextString(m) }
func (*GamerMatch) ProtoMessage()    {}
func (*GamerMatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{15}
}
func (m *GamerMatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamerMatch.Unmarshal(m, b)
}
func (m *GamerMatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamerMatch.Marshal(b, m, deterministic)
}
func (dst *GamerMatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamerMatch.Merge(dst, src)
}
func (m *GamerMatch) XXX_Size() int {
	return xxx_messageInfo_GamerMatch.Size(m)
}
func (m *GamerMatch) XXX_DiscardUnknown() {
	xxx_messageInfo_GamerMatch.DiscardUnknown(m)
}

var xxx_messageInfo_GamerMatch proto.InternalMessageInfo

func (m *GamerMatch) GetMini() *GamerMini {
	if m != nil {
		return m.Mini
	}
	return nil
}

func (m *GamerMatch) GetAi() bool {
	if m != nil {
		return m.Ai
	}
	return false
}

func (m *GamerMatch) GetPair() int32 {
	if m != nil {
		return m.Pair
	}
	return 0
}

func (m *GamerMatch) GetHero() int32 {
	if m != nil {
		return m.Hero
	}
	return 0
}

type MatchInfo struct {
	Session              string        `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Time                 int64         `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	Addr                 string        `protobuf:"bytes,3,opt,name=addr" json:"addr,omitempty"`
	FrameDelta           int32         `protobuf:"varint,4,opt,name=frameDelta" json:"frameDelta,omitempty"`
	MinFrameDelta        int32         `protobuf:"varint,5,opt,name=minFrameDelta" json:"minFrameDelta,omitempty"`
	MatchTime            int32         `protobuf:"varint,6,opt,name=matchTime" json:"matchTime,omitempty"`
	InputDelta           int32         `protobuf:"varint,7,opt,name=inputDelta" json:"inputDelta,omitempty"`
	PvpType              PVPType       `protobuf:"varint,8,opt,name=pvpType,enum=PVPType" json:"pvpType,omitempty"`
	ThreadRecv           bool          `protobuf:"varint,9,opt,name=threadRecv" json:"threadRecv,omitempty"`
	Gamers               []*GamerMatch `protobuf:"bytes,100,rep,name=gamers" json:"gamers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MatchInfo) Reset()         { *m = MatchInfo{} }
func (m *MatchInfo) String() string { return proto.CompactTextString(m) }
func (*MatchInfo) ProtoMessage()    {}
func (*MatchInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{16}
}
func (m *MatchInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchInfo.Unmarshal(m, b)
}
func (m *MatchInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchInfo.Marshal(b, m, deterministic)
}
func (dst *MatchInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchInfo.Merge(dst, src)
}
func (m *MatchInfo) XXX_Size() int {
	return xxx_messageInfo_MatchInfo.Size(m)
}
func (m *MatchInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MatchInfo proto.InternalMessageInfo

func (m *MatchInfo) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *MatchInfo) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *MatchInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *MatchInfo) GetFrameDelta() int32 {
	if m != nil {
		return m.FrameDelta
	}
	return 0
}

func (m *MatchInfo) GetMinFrameDelta() int32 {
	if m != nil {
		return m.MinFrameDelta
	}
	return 0
}

func (m *MatchInfo) GetMatchTime() int32 {
	if m != nil {
		return m.MatchTime
	}
	return 0
}

func (m *MatchInfo) GetInputDelta() int32 {
	if m != nil {
		return m.InputDelta
	}
	return 0
}

func (m *MatchInfo) GetPvpType() PVPType {
	if m != nil {
		return m.PvpType
	}
	return PVPType_MINVALID
}

func (m *MatchInfo) GetThreadRecv() bool {
	if m != nil {
		return m.ThreadRecv
	}
	return false
}

func (m *MatchInfo) GetGamers() []*GamerMatch {
	if m != nil {
		return m.Gamers
	}
	return nil
}

type PVPInput struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Yaw                  int32    `protobuf:"varint,2,opt,name=yaw" json:"yaw,omitempty"`
	Btn                  int32    `protobuf:"varint,3,opt,name=btn" json:"btn,omitempty"`
	Pos                  int32    `protobuf:"varint,4,opt,name=pos" json:"pos,omitempty"`
	Talk                 int32    `protobuf:"varint,5,opt,name=talk" json:"talk,omitempty"`
	Frame                int32    `protobuf:"varint,6,opt,name=frame" json:"frame,omitempty"`
	X                    int32    `protobuf:"varint,7,opt,name=x" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,8,opt,name=y" json:"y,omitempty"`
	Time                 int64    `protobuf:"varint,9,opt,name=time" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PVPInput) Reset()         { *m = PVPInput{} }
func (m *PVPInput) String() string { return proto.CompactTextString(m) }
func (*PVPInput) ProtoMessage()    {}
func (*PVPInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{17}
}
func (m *PVPInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PVPInput.Unmarshal(m, b)
}
func (m *PVPInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PVPInput.Marshal(b, m, deterministic)
}
func (dst *PVPInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PVPInput.Merge(dst, src)
}
func (m *PVPInput) XXX_Size() int {
	return xxx_messageInfo_PVPInput.Size(m)
}
func (m *PVPInput) XXX_DiscardUnknown() {
	xxx_messageInfo_PVPInput.DiscardUnknown(m)
}

var xxx_messageInfo_PVPInput proto.InternalMessageInfo

func (m *PVPInput) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PVPInput) GetYaw() int32 {
	if m != nil {
		return m.Yaw
	}
	return 0
}

func (m *PVPInput) GetBtn() int32 {
	if m != nil {
		return m.Btn
	}
	return 0
}

func (m *PVPInput) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *PVPInput) GetTalk() int32 {
	if m != nil {
		return m.Talk
	}
	return 0
}

func (m *PVPInput) GetFrame() int32 {
	if m != nil {
		return m.Frame
	}
	return 0
}

func (m *PVPInput) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *PVPInput) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *PVPInput) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// 逻辑帧
type PVPFrame struct {
	Delta                int32       `protobuf:"varint,1,opt,name=delta" json:"delta,omitempty"`
	Frame                int32       `protobuf:"varint,2,opt,name=frame" json:"frame,omitempty"`
	End                  bool        `protobuf:"varint,3,opt,name=end" json:"end,omitempty"`
	Inputs               []*PVPInput `protobuf:"bytes,100,rep,name=inputs" json:"inputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PVPFrame) Reset()         { *m = PVPFrame{} }
func (m *PVPFrame) String() string { return proto.CompactTextString(m) }
func (*PVPFrame) ProtoMessage()    {}
func (*PVPFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{18}
}
func (m *PVPFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PVPFrame.Unmarshal(m, b)
}
func (m *PVPFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PVPFrame.Marshal(b, m, deterministic)
}
func (dst *PVPFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PVPFrame.Merge(dst, src)
}
func (m *PVPFrame) XXX_Size() int {
	return xxx_messageInfo_PVPFrame.Size(m)
}
func (m *PVPFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_PVPFrame.DiscardUnknown(m)
}

var xxx_messageInfo_PVPFrame proto.InternalMessageInfo

func (m *PVPFrame) GetDelta() int32 {
	if m != nil {
		return m.Delta
	}
	return 0
}

func (m *PVPFrame) GetFrame() int32 {
	if m != nil {
		return m.Frame
	}
	return 0
}

func (m *PVPFrame) GetEnd() bool {
	if m != nil {
		return m.End
	}
	return false
}

func (m *PVPFrame) GetInputs() []*PVPInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

// 帧数据
type PVPFrames struct {
	Frames               []*PVPFrame `protobuf:"bytes,1,rep,name=frames" json:"frames,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PVPFrames) Reset()         { *m = PVPFrames{} }
func (m *PVPFrames) String() string { return proto.CompactTextString(m) }
func (*PVPFrames) ProtoMessage()    {}
func (*PVPFrames) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{19}
}
func (m *PVPFrames) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PVPFrames.Unmarshal(m, b)
}
func (m *PVPFrames) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PVPFrames.Marshal(b, m, deterministic)
}
func (dst *PVPFrames) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PVPFrames.Merge(dst, src)
}
func (m *PVPFrames) XXX_Size() int {
	return xxx_messageInfo_PVPFrames.Size(m)
}
func (m *PVPFrames) XXX_DiscardUnknown() {
	xxx_messageInfo_PVPFrames.DiscardUnknown(m)
}

var xxx_messageInfo_PVPFrames proto.InternalMessageInfo

func (m *PVPFrames) GetFrames() []*PVPFrame {
	if m != nil {
		return m.Frames
	}
	return nil
}

type RankLength struct {
	Id                   int32      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Length               int32      `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	Rank                 int32      `protobuf:"varint,3,opt,name=rank" json:"rank,omitempty"`
	Mini                 *GamerMini `protobuf:"bytes,4,opt,name=mini" json:"mini,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RankLength) Reset()         { *m = RankLength{} }
func (m *RankLength) String() string { return proto.CompactTextString(m) }
func (*RankLength) ProtoMessage()    {}
func (*RankLength) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{20}
}
func (m *RankLength) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankLength.Unmarshal(m, b)
}
func (m *RankLength) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankLength.Marshal(b, m, deterministic)
}
func (dst *RankLength) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankLength.Merge(dst, src)
}
func (m *RankLength) XXX_Size() int {
	return xxx_messageInfo_RankLength.Size(m)
}
func (m *RankLength) XXX_DiscardUnknown() {
	xxx_messageInfo_RankLength.DiscardUnknown(m)
}

var xxx_messageInfo_RankLength proto.InternalMessageInfo

func (m *RankLength) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RankLength) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *RankLength) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *RankLength) GetMini() *GamerMini {
	if m != nil {
		return m.Mini
	}
	return nil
}

// 房间成员信息
type RoomMemInfo struct {
	MiniInfo             *GamerMini `protobuf:"bytes,1,opt,name=miniInfo" json:"miniInfo,omitempty"`
	Hero                 int32      `protobuf:"varint,2,opt,name=hero" json:"hero,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RoomMemInfo) Reset()         { *m = RoomMemInfo{} }
func (m *RoomMemInfo) String() string { return proto.CompactTextString(m) }
func (*RoomMemInfo) ProtoMessage()    {}
func (*RoomMemInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{21}
}
func (m *RoomMemInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomMemInfo.Unmarshal(m, b)
}
func (m *RoomMemInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomMemInfo.Marshal(b, m, deterministic)
}
func (dst *RoomMemInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomMemInfo.Merge(dst, src)
}
func (m *RoomMemInfo) XXX_Size() int {
	return xxx_messageInfo_RoomMemInfo.Size(m)
}
func (m *RoomMemInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomMemInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomMemInfo proto.InternalMessageInfo

func (m *RoomMemInfo) GetMiniInfo() *GamerMini {
	if m != nil {
		return m.MiniInfo
	}
	return nil
}

func (m *RoomMemInfo) GetHero() int32 {
	if m != nil {
		return m.Hero
	}
	return 0
}

// 房间信息
type RoomInfo struct {
	Id                   uint32         `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	OwnerId              int32          `protobuf:"varint,2,opt,name=ownerId" json:"ownerId,omitempty"`
	Type                 PVPType        `protobuf:"varint,3,opt,name=type,enum=PVPType" json:"type,omitempty"`
	Time                 int64          `protobuf:"varint,4,opt,name=time" json:"time,omitempty"`
	Name                 string         `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	State                RoomState      `protobuf:"varint,6,opt,name=state,enum=RoomState" json:"state,omitempty"`
	Members              []*RoomMemInfo `protobuf:"bytes,7,rep,name=members" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RoomInfo) Reset()         { *m = RoomInfo{} }
func (m *RoomInfo) String() string { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()    {}
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{22}
}
func (m *RoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfo.Unmarshal(m, b)
}
func (m *RoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfo.Marshal(b, m, deterministic)
}
func (dst *RoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfo.Merge(dst, src)
}
func (m *RoomInfo) XXX_Size() int {
	return xxx_messageInfo_RoomInfo.Size(m)
}
func (m *RoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfo proto.InternalMessageInfo

func (m *RoomInfo) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RoomInfo) GetOwnerId() int32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *RoomInfo) GetType() PVPType {
	if m != nil {
		return m.Type
	}
	return PVPType_MINVALID
}

func (m *RoomInfo) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *RoomInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoomInfo) GetState() RoomState {
	if m != nil {
		return m.State
	}
	return RoomState_RoomState_None
}

func (m *RoomInfo) GetMembers() []*RoomMemInfo {
	if m != nil {
		return m.Members
	}
	return nil
}

type PVPStateSync struct {
	C2S                  *PVPStateSync_C2S `protobuf:"bytes,1,opt,name=c2s" json:"c2s,omitempty"`
	S2C                  *PVPStateSync_S2C `protobuf:"bytes,2,opt,name=s2c" json:"s2c,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PVPStateSync) Reset()         { *m = PVPStateSync{} }
func (m *PVPStateSync) String() string { return proto.CompactTextString(m) }
func (*PVPStateSync) ProtoMessage()    {}
func (*PVPStateSync) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{23}
}
func (m *PVPStateSync) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PVPStateSync.Unmarshal(m, b)
}
func (m *PVPStateSync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PVPStateSync.Marshal(b, m, deterministic)
}
func (dst *PVPStateSync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PVPStateSync.Merge(dst, src)
}
func (m *PVPStateSync) XXX_Size() int {
	return xxx_messageInfo_PVPStateSync.Size(m)
}
func (m *PVPStateSync) XXX_DiscardUnknown() {
	xxx_messageInfo_PVPStateSync.DiscardUnknown(m)
}

var xxx_messageInfo_PVPStateSync proto.InternalMessageInfo

func (m *PVPStateSync) GetC2S() *PVPStateSync_C2S {
	if m != nil {
		return m.C2S
	}
	return nil
}

func (m *PVPStateSync) GetS2C() *PVPStateSync_S2C {
	if m != nil {
		return m.S2C
	}
	return nil
}

type PVPStateSync_MatchInfo struct {
	Time                 int32                  `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	LeftScore            int32                  `protobuf:"varint,2,opt,name=leftScore" json:"leftScore,omitempty"`
	RightScore           int32                  `protobuf:"varint,3,opt,name=rightScore" json:"rightScore,omitempty"`
	Pillars              []*PVPStateSync_Pillar `protobuf:"bytes,4,rep,name=pillars" json:"pillars,omitempty"`
	Items                []*PVPStateSync_Item   `protobuf:"bytes,5,rep,name=items" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PVPStateSync_MatchInfo) Reset()         { *m = PVPStateSync_MatchInfo{} }
func (m *PVPStateSync_MatchInfo) String() string { return proto.CompactTextString(m) }
func (*PVPStateSync_MatchInfo) ProtoMessage()    {}
func (*PVPStateSync_MatchInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{23, 0}
}
func (m *PVPStateSync_MatchInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PVPStateSync_MatchInfo.Unmarshal(m, b)
}
func (m *PVPStateSync_MatchInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PVPStateSync_MatchInfo.Marshal(b, m, deterministic)
}
func (dst *PVPStateSync_MatchInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PVPStateSync_MatchInfo.Merge(dst, src)
}
func (m *PVPStateSync_MatchInfo) XXX_Size() int {
	return xxx_messageInfo_PVPStateSync_MatchInfo.Size(m)
}
func (m *PVPStateSync_MatchInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PVPStateSync_MatchInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PVPStateSync_MatchInfo proto.InternalMessageInfo

func (m *PVPStateSync_MatchInfo) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PVPStateSync_MatchInfo) GetLeftScore() int32 {
	if m != nil {
		return m.LeftScore
	}
	return 0
}

func (m *PVPStateSync_MatchInfo) GetRightScore() int32 {
	if m != nil {
		return m.RightScore
	}
	return 0
}

func (m *PVPStateSync_MatchInfo) GetPillars() []*PVPStateSync_Pillar {
	if m != nil {
		return m.Pillars
	}
	return nil
}

func (m *PVPStateSync_MatchInfo) GetItems() []*PVPStateSync_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type PVPStateSync_Pillar struct {
	X                    int32    `protobuf:"varint,2,opt,name=x" json:"x,omitempty"`
	H                    int32    `protobuf:"varint,3,opt,name=h" json:"h,omitempty"`
	W                    int32    `protobuf:"varint,4,opt,name=w" json:"w,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PVPStateSync_Pillar) Reset()         { *m = PVPStateSync_Pillar{} }
func (m *PVPStateSync_Pillar) String() string { return proto.CompactTextString(m) }
func (*PVPStateSync_Pillar) ProtoMessage()    {}
func (*PVPStateSync_Pillar) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{23, 1}
}
func (m *PVPStateSync_Pillar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PVPStateSync_Pillar.Unmarshal(m, b)
}
func (m *PVPStateSync_Pillar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PVPStateSync_Pillar.Marshal(b, m, deterministic)
}
func (dst *PVPStateSync_Pillar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PVPStateSync_Pillar.Merge(dst, src)
}
func (m *PVPStateSync_Pillar) XXX_Size() int {
	return xxx_messageInfo_PVPStateSync_Pillar.Size(m)
}
func (m *PVPStateSync_Pillar) XXX_DiscardUnknown() {
	xxx_messageInfo_PVPStateSync_Pillar.DiscardUnknown(m)
}

var xxx_messageInfo_PVPStateSync_Pillar proto.InternalMessageInfo

func (m *PVPStateSync_Pillar) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *PVPStateSync_Pillar) GetH() int32 {
	if m != nil {
		return m.H
	}
	return 0
}

func (m *PVPStateSync_Pillar) GetW() int32 {
	if m != nil {
		return m.W
	}
	return 0
}

type PVPStateSync_Item struct {
	Type                 int32    `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	X                    int32    `protobuf:"varint,2,opt,name=x" json:"x,omitempty"`
	H                    int32    `protobuf:"varint,3,opt,name=h" json:"h,omitempty"`
	Index                int32    `protobuf:"varint,4,opt,name=index" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PVPStateSync_Item) Reset()         { *m = PVPStateSync_Item{} }
func (m *PVPStateSync_Item) String() string { return proto.CompactTextString(m) }
func (*PVPStateSync_Item) ProtoMessage()    {}
func (*PVPStateSync_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{23, 2}
}
func (m *PVPStateSync_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PVPStateSync_Item.Unmarshal(m, b)
}
func (m *PVPStateSync_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PVPStateSync_Item.Marshal(b, m, deterministic)
}
func (dst *PVPStateSync_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PVPStateSync_Item.Merge(dst, src)
}
func (m *PVPStateSync_Item) XXX_Size() int {
	return xxx_messageInfo_PVPStateSync_Item.Size(m)
}
func (m *PVPStateSync_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_PVPStateSync_Item.DiscardUnknown(m)
}

var xxx_messageInfo_PVPStateSync_Item proto.InternalMessageInfo

func (m *PVPStateSync_Item) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *PVPStateSync_Item) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *PVPStateSync_Item) GetH() int32 {
	if m != nil {
		return m.H
	}
	return 0
}

func (m *PVPStateSync_Item) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type PVPStateSync_CheckPoint struct {
	RunTime              int32    `protobuf:"varint,1,opt,name=runTime" json:"runTime,omitempty"`
	LastX                int32    `protobuf:"varint,2,opt,name=lastX" json:"lastX,omitempty"`
	LastY                int32    `protobuf:"varint,3,opt,name=lastY" json:"lastY,omitempty"`
	LastIndex            int32    `protobuf:"varint,4,opt,name=lastIndex" json:"lastIndex,omitempty"`
	NextIndex            int32    `protobuf:"varint,5,opt,name=nextIndex" json:"nextIndex,omitempty"`
	BeginTime            int32    `protobuf:"varint,6,opt,name=beginTime" json:"beginTime,omitempty"`
	ClientTime           int32    `protobuf:"varint,7,opt,name=clientTime" json:"clientTime,omitempty"`
	NextX                int32    `protobuf:"varint,8,opt,name=nextX" json:"nextX,omitempty"`
	NextY                int32    `protobuf:"varint,9,opt,name=nextY" json:"nextY,omitempty"`
	MinY                 int32    `protobuf:"varint,10,opt,name=minY" json:"minY,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PVPStateSync_CheckPoint) Reset()         { *m = PVPStateSync_CheckPoint{} }
func (m *PVPStateSync_CheckPoint) String() string { return proto.CompactTextString(m) }
func (*PVPStateSync_CheckPoint) ProtoMessage()    {}
func (*PVPStateSync_CheckPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{23, 3}
}
func (m *PVPStateSync_CheckPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PVPStateSync_CheckPoint.Unmarshal(m, b)
}
func (m *PVPStateSync_CheckPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PVPStateSync_CheckPoint.Marshal(b, m, deterministic)
}
func (dst *PVPStateSync_CheckPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PVPStateSync_CheckPoint.Merge(dst, src)
}
func (m *PVPStateSync_CheckPoint) XXX_Size() int {
	return xxx_messageInfo_PVPStateSync_CheckPoint.Size(m)
}
func (m *PVPStateSync_CheckPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_PVPStateSync_CheckPoint.DiscardUnknown(m)
}

var xxx_messageInfo_PVPStateSync_CheckPoint proto.InternalMessageInfo

func (m *PVPStateSync_CheckPoint) GetRunTime() int32 {
	if m != nil {
		return m.RunTime
	}
	return 0
}

func (m *PVPStateSync_CheckPoint) GetLastX() int32 {
	if m != nil {
		return m.LastX
	}
	return 0
}

func (m *PVPStateSync_CheckPoint) GetLastY() int32 {
	if m != nil {
		return m.LastY
	}
	return 0
}

func (m *PVPStateSync_CheckPoint) GetLastIndex() int32 {
	if m != nil {
		return m.LastIndex
	}
	return 0
}

func (m *PVPStateSync_CheckPoint) GetNextIndex() int32 {
	if m != nil {
		return m.NextIndex
	}
	return 0
}

func (m *PVPStateSync_CheckPoint) GetBeginTime() int32 {
	if m != nil {
		return m.BeginTime
	}
	return 0
}

func (m *PVPStateSync_CheckPoint) GetClientTime() int32 {
	if m != nil {
		return m.ClientTime
	}
	return 0
}

func (m *PVPStateSync_CheckPoint) GetNextX() int32 {
	if m != nil {
		return m.NextX
	}
	return 0
}

func (m *PVPStateSync_CheckPoint) GetNextY() int32 {
	if m != nil {
		return m.NextY
	}
	return 0
}

func (m *PVPStateSync_CheckPoint) GetMinY() int32 {
	if m != nil {
		return m.MinY
	}
	return 0
}

type PVPStateSync_GamerEnter struct {
	Pos                  int32    `protobuf:"varint,1,opt,name=pos" json:"pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PVPStateSync_GamerEnter) Reset()         { *m = PVPStateSync_GamerEnter{} }
func (m *PVPStateSync_GamerEnter) String() string { return proto.CompactTextString(m) }
func (*PVPStateSync_GamerEnter) ProtoMessage()    {}
func (*PVPStateSync_GamerEnter) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{23, 4}
}
func (m *PVPStateSync_GamerEnter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PVPStateSync_GamerEnter.Unmarshal(m, b)
}
func (m *PVPStateSync_GamerEnter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PVPStateSync_GamerEnter.Marshal(b, m, deterministic)
}
func (dst *PVPStateSync_GamerEnter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PVPStateSync_GamerEnter.Merge(dst, src)
}
func (m *PVPStateSync_GamerEnter) XXX_Size() int {
	return xxx_messageInfo_PVPStateSync_GamerEnter.Size(m)
}
func (m *PVPStateSync_GamerEnter) XXX_DiscardUnknown() {
	xxx_messageInfo_PVPStateSync_GamerEnter.DiscardUnknown(m)
}

var xxx_messageInfo_PVPStateSync_GamerEnter proto.InternalMessageInfo

func (m *PVPStateSync_GamerEnter) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

type PVPStateSync_GamerInfo struct {
	Pos                  int32                    `protobuf:"varint,1,opt,name=pos" json:"pos,omitempty"`
	Score                int32                    `protobuf:"varint,2,opt,name=score" json:"score,omitempty"`
	Cp                   *PVPStateSync_CheckPoint `protobuf:"bytes,3,opt,name=cp" json:"cp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PVPStateSync_GamerInfo) Reset()         { *m = PVPStateSync_GamerInfo{} }
func (m *PVPStateSync_GamerInfo) String() string { return proto.CompactTextString(m) }
func (*PVPStateSync_GamerInfo) ProtoMessage()    {}
func (*PVPStateSync_GamerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{23, 5}
}
func (m *PVPStateSync_GamerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PVPStateSync_GamerInfo.Unmarshal(m, b)
}
func (m *PVPStateSync_GamerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PVPStateSync_GamerInfo.Marshal(b, m, deterministic)
}
func (dst *PVPStateSync_GamerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PVPStateSync_GamerInfo.Merge(dst, src)
}
func (m *PVPStateSync_GamerInfo) XXX_Size() int {
	return xxx_messageInfo_PVPStateSync_GamerInfo.Size(m)
}
func (m *PVPStateSync_GamerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PVPStateSync_GamerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PVPStateSync_GamerInfo proto.InternalMessageInfo

func (m *PVPStateSync_GamerInfo) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *PVPStateSync_GamerInfo) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *PVPStateSync_GamerInfo) GetCp() *PVPStateSync_CheckPoint {
	if m != nil {
		return m.Cp
	}
	return nil
}

type PVPStateSync_Jump struct {
	Pos                  int32    `protobuf:"varint,1,opt,name=pos" json:"pos,omitempty"`
	Vx                   int32    `protobuf:"varint,2,opt,name=vx" json:"vx,omitempty"`
	Vy                   int32    `protobuf:"varint,3,opt,name=vy" json:"vy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PVPStateSync_Jump) Reset()         { *m = PVPStateSync_Jump{} }
func (m *PVPStateSync_Jump) String() string { return proto.CompactTextString(m) }
func (*PVPStateSync_Jump) ProtoMessage()    {}
func (*PVPStateSync_Jump) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{23, 6}
}
func (m *PVPStateSync_Jump) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PVPStateSync_Jump.Unmarshal(m, b)
}
func (m *PVPStateSync_Jump) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PVPStateSync_Jump.Marshal(b, m, deterministic)
}
func (dst *PVPStateSync_Jump) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PVPStateSync_Jump.Merge(dst, src)
}
func (m *PVPStateSync_Jump) XXX_Size() int {
	return xxx_messageInfo_PVPStateSync_Jump.Size(m)
}
func (m *PVPStateSync_Jump) XXX_DiscardUnknown() {
	xxx_messageInfo_PVPStateSync_Jump.DiscardUnknown(m)
}

var xxx_messageInfo_PVPStateSync_Jump proto.InternalMessageInfo

func (m *PVPStateSync_Jump) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *PVPStateSync_Jump) GetVx() int32 {
	if m != nil {
		return m.Vx
	}
	return 0
}

func (m *PVPStateSync_Jump) GetVy() int32 {
	if m != nil {
		return m.Vy
	}
	return 0
}

type PVPStateSync_Result struct {
	Mvp                  int32    `protobuf:"varint,1,opt,name=mvp" json:"mvp,omitempty"`
	Timeout              bool     `protobuf:"varint,2,opt,name=timeout" json:"timeout,omitempty"`
	Scores               []int32  `protobuf:"varint,3,rep,packed,name=scores" json:"scores,omitempty"`
	Icons                []int32  `protobuf:"varint,4,rep,packed,name=icons" json:"icons,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PVPStateSync_Result) Reset()         { *m = PVPStateSync_Result{} }
func (m *PVPStateSync_Result) String() string { return proto.CompactTextString(m) }
func (*PVPStateSync_Result) ProtoMessage()    {}
func (*PVPStateSync_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{23, 7}
}
func (m *PVPStateSync_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PVPStateSync_Result.Unmarshal(m, b)
}
func (m *PVPStateSync_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PVPStateSync_Result.Marshal(b, m, deterministic)
}
func (dst *PVPStateSync_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PVPStateSync_Result.Merge(dst, src)
}
func (m *PVPStateSync_Result) XXX_Size() int {
	return xxx_messageInfo_PVPStateSync_Result.Size(m)
}
func (m *PVPStateSync_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_PVPStateSync_Result.DiscardUnknown(m)
}

var xxx_messageInfo_PVPStateSync_Result proto.InternalMessageInfo

func (m *PVPStateSync_Result) GetMvp() int32 {
	if m != nil {
		return m.Mvp
	}
	return 0
}

func (m *PVPStateSync_Result) GetTimeout() bool {
	if m != nil {
		return m.Timeout
	}
	return false
}

func (m *PVPStateSync_Result) GetScores() []int32 {
	if m != nil {
		return m.Scores
	}
	return nil
}

func (m *PVPStateSync_Result) GetIcons() []int32 {
	if m != nil {
		return m.Icons
	}
	return nil
}

type PVPStateSync_C2S struct {
	Jump                 *PVPStateSync_Jump       `protobuf:"bytes,1,opt,name=jump" json:"jump,omitempty"`
	Enter                *PVPStateSync_GamerEnter `protobuf:"bytes,5,opt,name=enter" json:"enter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PVPStateSync_C2S) Reset()         { *m = PVPStateSync_C2S{} }
func (m *PVPStateSync_C2S) String() string { return proto.CompactTextString(m) }
func (*PVPStateSync_C2S) ProtoMessage()    {}
func (*PVPStateSync_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{23, 8}
}
func (m *PVPStateSync_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PVPStateSync_C2S.Unmarshal(m, b)
}
func (m *PVPStateSync_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PVPStateSync_C2S.Marshal(b, m, deterministic)
}
func (dst *PVPStateSync_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PVPStateSync_C2S.Merge(dst, src)
}
func (m *PVPStateSync_C2S) XXX_Size() int {
	return xxx_messageInfo_PVPStateSync_C2S.Size(m)
}
func (m *PVPStateSync_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_PVPStateSync_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_PVPStateSync_C2S proto.InternalMessageInfo

func (m *PVPStateSync_C2S) GetJump() *PVPStateSync_Jump {
	if m != nil {
		return m.Jump
	}
	return nil
}

func (m *PVPStateSync_C2S) GetEnter() *PVPStateSync_GamerEnter {
	if m != nil {
		return m.Enter
	}
	return nil
}

type PVPStateSync_S2C struct {
	MatchInfo            *PVPStateSync_MatchInfo    `protobuf:"bytes,1,opt,name=matchInfo" json:"matchInfo,omitempty"`
	Result               *PVPStateSync_Result       `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
	GamerInfo            []*PVPStateSync_GamerInfo  `protobuf:"bytes,3,rep,name=gamerInfo" json:"gamerInfo,omitempty"`
	GamerEnter           []*PVPStateSync_GamerEnter `protobuf:"bytes,4,rep,name=gamerEnter" json:"gamerEnter,omitempty"`
	Jump                 *PVPStateSync_Jump         `protobuf:"bytes,5,opt,name=jump" json:"jump,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *PVPStateSync_S2C) Reset()         { *m = PVPStateSync_S2C{} }
func (m *PVPStateSync_S2C) String() string { return proto.CompactTextString(m) }
func (*PVPStateSync_S2C) ProtoMessage()    {}
func (*PVPStateSync_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{23, 9}
}
func (m *PVPStateSync_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PVPStateSync_S2C.Unmarshal(m, b)
}
func (m *PVPStateSync_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PVPStateSync_S2C.Marshal(b, m, deterministic)
}
func (dst *PVPStateSync_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PVPStateSync_S2C.Merge(dst, src)
}
func (m *PVPStateSync_S2C) XXX_Size() int {
	return xxx_messageInfo_PVPStateSync_S2C.Size(m)
}
func (m *PVPStateSync_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_PVPStateSync_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_PVPStateSync_S2C proto.InternalMessageInfo

func (m *PVPStateSync_S2C) GetMatchInfo() *PVPStateSync_MatchInfo {
	if m != nil {
		return m.MatchInfo
	}
	return nil
}

func (m *PVPStateSync_S2C) GetResult() *PVPStateSync_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *PVPStateSync_S2C) GetGamerInfo() []*PVPStateSync_GamerInfo {
	if m != nil {
		return m.GamerInfo
	}
	return nil
}

func (m *PVPStateSync_S2C) GetGamerEnter() []*PVPStateSync_GamerEnter {
	if m != nil {
		return m.GamerEnter
	}
	return nil
}

func (m *PVPStateSync_S2C) GetJump() *PVPStateSync_Jump {
	if m != nil {
		return m.Jump
	}
	return nil
}

type PVPResult struct {
	Kills                []int32              `protobuf:"varint,1,rep,packed,name=kills" json:"kills,omitempty"`
	Time                 int64                `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	Gone                 []int32              `protobuf:"varint,3,rep,packed,name=gone" json:"gone,omitempty"`
	Version              int32                `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`
	SResult              *PVPStateSync_Result `protobuf:"bytes,5,opt,name=sResult" json:"sResult,omitempty"`
	MatchInfo            *MatchInfo           `protobuf:"bytes,101,opt,name=matchInfo" json:"matchInfo,omitempty"`
	Frames               []*PVPFrame          `protobuf:"bytes,102,rep,name=frames" json:"frames,omitempty"`
	Md5                  string               `protobuf:"bytes,103,opt,name=md5" json:"md5,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PVPResult) Reset()         { *m = PVPResult{} }
func (m *PVPResult) String() string { return proto.CompactTextString(m) }
func (*PVPResult) ProtoMessage()    {}
func (*PVPResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{24}
}
func (m *PVPResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PVPResult.Unmarshal(m, b)
}
func (m *PVPResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PVPResult.Marshal(b, m, deterministic)
}
func (dst *PVPResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PVPResult.Merge(dst, src)
}
func (m *PVPResult) XXX_Size() int {
	return xxx_messageInfo_PVPResult.Size(m)
}
func (m *PVPResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PVPResult.DiscardUnknown(m)
}

var xxx_messageInfo_PVPResult proto.InternalMessageInfo

func (m *PVPResult) GetKills() []int32 {
	if m != nil {
		return m.Kills
	}
	return nil
}

func (m *PVPResult) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PVPResult) GetGone() []int32 {
	if m != nil {
		return m.Gone
	}
	return nil
}

func (m *PVPResult) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *PVPResult) GetSResult() *PVPStateSync_Result {
	if m != nil {
		return m.SResult
	}
	return nil
}

func (m *PVPResult) GetMatchInfo() *MatchInfo {
	if m != nil {
		return m.MatchInfo
	}
	return nil
}

func (m *PVPResult) GetFrames() []*PVPFrame {
	if m != nil {
		return m.Frames
	}
	return nil
}

func (m *PVPResult) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

// 通用抽奖信息
type Gashapon struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	ExtractNum           int32    `protobuf:"varint,2,opt,name=extractNum" json:"extractNum,omitempty"`
	FreeNum              int32    `protobuf:"varint,3,opt,name=freeNum" json:"freeNum,omitempty"`
	NextFreeTime         int64    `protobuf:"varint,4,opt,name=nextFreeTime" json:"nextFreeTime,omitempty"`
	StartTime            int64    `protobuf:"varint,5,opt,name=startTime" json:"startTime,omitempty"`
	EndTime              int64    `protobuf:"varint,6,opt,name=endTime" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gashapon) Reset()         { *m = Gashapon{} }
func (m *Gashapon) String() string { return proto.CompactTextString(m) }
func (*Gashapon) ProtoMessage()    {}
func (*Gashapon) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{25}
}
func (m *Gashapon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gashapon.Unmarshal(m, b)
}
func (m *Gashapon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gashapon.Marshal(b, m, deterministic)
}
func (dst *Gashapon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gashapon.Merge(dst, src)
}
func (m *Gashapon) XXX_Size() int {
	return xxx_messageInfo_Gashapon.Size(m)
}
func (m *Gashapon) XXX_DiscardUnknown() {
	xxx_messageInfo_Gashapon.DiscardUnknown(m)
}

var xxx_messageInfo_Gashapon proto.InternalMessageInfo

func (m *Gashapon) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Gashapon) GetExtractNum() int32 {
	if m != nil {
		return m.ExtractNum
	}
	return 0
}

func (m *Gashapon) GetFreeNum() int32 {
	if m != nil {
		return m.FreeNum
	}
	return 0
}

func (m *Gashapon) GetNextFreeTime() int64 {
	if m != nil {
		return m.NextFreeTime
	}
	return 0
}

func (m *Gashapon) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Gashapon) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type CountActivity struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	CurrentDay           int32    `protobuf:"varint,2,opt,name=currentDay" json:"currentDay,omitempty"`
	AlreadyGetDay        int32    `protobuf:"varint,3,opt,name=alreadyGetDay" json:"alreadyGetDay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountActivity) Reset()         { *m = CountActivity{} }
func (m *CountActivity) String() string { return proto.CompactTextString(m) }
func (*CountActivity) ProtoMessage()    {}
func (*CountActivity) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_e2f064821d72f4be, []int{26}
}
func (m *CountActivity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountActivity.Unmarshal(m, b)
}
func (m *CountActivity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountActivity.Marshal(b, m, deterministic)
}
func (dst *CountActivity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountActivity.Merge(dst, src)
}
func (m *CountActivity) XXX_Size() int {
	return xxx_messageInfo_CountActivity.Size(m)
}
func (m *CountActivity) XXX_DiscardUnknown() {
	xxx_messageInfo_CountActivity.DiscardUnknown(m)
}

var xxx_messageInfo_CountActivity proto.InternalMessageInfo

func (m *CountActivity) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CountActivity) GetCurrentDay() int32 {
	if m != nil {
		return m.CurrentDay
	}
	return 0
}

func (m *CountActivity) GetAlreadyGetDay() int32 {
	if m != nil {
		return m.AlreadyGetDay
	}
	return 0
}

func init() {
	proto.RegisterType((*PrevC2S)(nil), "PrevC2S")
	proto.RegisterType((*ServerTime)(nil), "ServerTime")
	proto.RegisterType((*GameItem)(nil), "GameItem")
	proto.RegisterType((*TimeRecord)(nil), "TimeRecord")
	proto.RegisterType((*NumberRecord)(nil), "NumberRecord")
	proto.RegisterType((*WXInfo)(nil), "WXInfo")
	proto.RegisterType((*GamerMain)(nil), "GamerMain")
	proto.RegisterType((*GamerMini)(nil), "GamerMini")
	proto.RegisterType((*GamerFriendRequest)(nil), "GamerFriendRequest")
	proto.RegisterType((*GamerBlack)(nil), "GamerBlack")
	proto.RegisterType((*GamerFriend)(nil), "GamerFriend")
	proto.RegisterType((*ChatData)(nil), "ChatData")
	proto.RegisterType((*Mail)(nil), "Mail")
	proto.RegisterType((*BagItem)(nil), "BagItem")
	proto.RegisterType((*GamerHero)(nil), "GamerHero")
	proto.RegisterType((*GamerMatch)(nil), "GamerMatch")
	proto.RegisterType((*MatchInfo)(nil), "MatchInfo")
	proto.RegisterType((*PVPInput)(nil), "PVPInput")
	proto.RegisterType((*PVPFrame)(nil), "PVPFrame")
	proto.RegisterType((*PVPFrames)(nil), "PVPFrames")
	proto.RegisterType((*RankLength)(nil), "RankLength")
	proto.RegisterType((*RoomMemInfo)(nil), "RoomMemInfo")
	proto.RegisterType((*RoomInfo)(nil), "RoomInfo")
	proto.RegisterType((*PVPStateSync)(nil), "PVPStateSync")
	proto.RegisterType((*PVPStateSync_MatchInfo)(nil), "PVPStateSync.MatchInfo")
	proto.RegisterType((*PVPStateSync_Pillar)(nil), "PVPStateSync.Pillar")
	proto.RegisterType((*PVPStateSync_Item)(nil), "PVPStateSync.Item")
	proto.RegisterType((*PVPStateSync_CheckPoint)(nil), "PVPStateSync.CheckPoint")
	proto.RegisterType((*PVPStateSync_GamerEnter)(nil), "PVPStateSync.GamerEnter")
	proto.RegisterType((*PVPStateSync_GamerInfo)(nil), "PVPStateSync.GamerInfo")
	proto.RegisterType((*PVPStateSync_Jump)(nil), "PVPStateSync.Jump")
	proto.RegisterType((*PVPStateSync_Result)(nil), "PVPStateSync.Result")
	proto.RegisterType((*PVPStateSync_C2S)(nil), "PVPStateSync.C2S")
	proto.RegisterType((*PVPStateSync_S2C)(nil), "PVPStateSync.S2C")
	proto.RegisterType((*PVPResult)(nil), "PVPResult")
	proto.RegisterType((*Gashapon)(nil), "Gashapon")
	proto.RegisterType((*CountActivity)(nil), "CountActivity")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_common_e2f064821d72f4be) }

var fileDescriptor_common_e2f064821d72f4be = []byte{
	// 2204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0xcf, 0x8f, 0xdc, 0x48,
	0xf5, 0x97, 0xdb, 0xfd, 0xf3, 0xcd, 0x24, 0xdf, 0x59, 0x7f, 0xa3, 0x5d, 0xd3, 0x1b, 0xa2, 0xc1,
	0x0b, 0xd1, 0x08, 0x50, 0x1f, 0x1a, 0x45, 0xda, 0x2b, 0x3b, 0xd9, 0x0c, 0x8d, 0x92, 0xa8, 0x55,
	0x1d, 0xf2, 0x43, 0x68, 0x15, 0xd5, 0xd8, 0x35, 0xdd, 0x45, 0xdb, 0x65, 0x63, 0x57, 0xf7, 0x4c,
	0x73, 0xe5, 0xc2, 0x81, 0x23, 0x27, 0x6e, 0x1c, 0x38, 0xc0, 0x89, 0x1b, 0x12, 0xe7, 0x15, 0x12,
	0xff, 0x0e, 0x7f, 0x01, 0x7a, 0xaf, 0xaa, 0x6c, 0xf7, 0x4c, 0x27, 0xd2, 0xde, 0xde, 0xe7, 0xbd,
	0x72, 0xd5, 0xfb, 0xfd, 0xaa, 0x0c, 0xc7, 0x71, 0x9e, 0x65, 0xb9, 0x9a, 0x14, 0x65, 0xae, 0xf3,
	0x71, 0x10, 0xe7, 0xaa, 0xd2, 0xef, 0x13, 0x71, 0x25, 0x95, 0x30, 0xbc, 0xe8, 0x73, 0x18, 0xcc,
	0x4b, 0xb1, 0x3d, 0x9f, 0x2e, 0x82, 0x13, 0xf0, 0xd7, 0x62, 0x17, 0x7a, 0xa7, 0xde, 0xd9, 0x88,
	0x21, 0x19, 0xfd, 0xdb, 0x03, 0x58, 0x88, 0x72, 0x2b, 0xca, 0x57, 0x32, 0x13, 0xc1, 0x43, 0x18,
	0x69, 0x99, 0x89, 0x4a, 0xf3, 0xac, 0xa0, 0x65, 0x3e, 0x6b, 0x18, 0x41, 0x00, 0xdd, 0x9d, 0xe0,
	0x65, 0xd8, 0x39, 0xf5, 0xce, 0x7a, 0x8c, 0xe8, 0xe0, 0x01, 0xf4, 0xb2, 0x5c, 0xe9, 0x55, 0xe8,
	0x13, 0xd3, 0x00, 0x3c, 0x28, 0xe1, 0xbb, 0xb0, 0x4b, 0x3c, 0x24, 0xf1, 0xdb, 0x55, 0xbe, 0x29,
	0xc3, 0x9e, 0xf9, 0x16, 0xe9, 0xe0, 0x53, 0xe8, 0x67, 0x52, 0x6d, 0xb4, 0x08, 0xfb, 0xc4, 0xb5,
	0x08, 0xf9, 0x95, 0x88, 0x73, 0x95, 0x84, 0x03, 0xc3, 0x37, 0x28, 0x18, 0xc3, 0x10, 0x95, 0xf9,
	0x5d, 0xae, 0x44, 0x38, 0x24, 0x49, 0x8d, 0xa3, 0x1b, 0x18, 0x5e, 0xf0, 0x4c, 0xcc, 0xb4, 0xc8,
	0x82, 0xfb, 0xd0, 0x91, 0x09, 0xa9, 0xdf, 0x63, 0x1d, 0x99, 0xe0, 0xd9, 0x7a, 0x57, 0x08, 0xa7,
	0x37, 0xd2, 0xa8, 0x77, 0x9c, 0x6f, 0x94, 0x76, 0x7a, 0x13, 0x08, 0x1e, 0x01, 0xe4, 0x97, 0x9a,
	0x4b, 0x85, 0xde, 0x20, 0xf5, 0x7d, 0xd6, 0xe2, 0xe0, 0x4e, 0x8a, 0x67, 0x82, 0xac, 0x18, 0x31,
	0xa2, 0xa3, 0x3f, 0x79, 0x00, 0x28, 0x64, 0x22, 0xce, 0x4b, 0x52, 0x32, 0xe5, 0x95, 0x5e, 0xc8,
	0xa5, 0xa2, 0xbd, 0x7d, 0x56, 0xe3, 0xe0, 0xc7, 0x70, 0x82, 0xf4, 0x85, 0xd0, 0xf3, 0xd7, 0x73,
	0x26, 0xaa, 0x4d, 0xaa, 0xc9, 0x74, 0x9f, 0xdd, 0xe1, 0x07, 0xa7, 0x70, 0x84, 0xbc, 0x37, 0x42,
	0xac, 0x99, 0x88, 0xc9, 0x13, 0x3e, 0x6b, 0xb3, 0x28, 0x58, 0xb9, 0xe6, 0x29, 0xe9, 0x6a, 0xfc,
	0xd1, 0x30, 0xa2, 0x6f, 0x3d, 0x38, 0x7e, 0xb9, 0xc9, 0x2e, 0x45, 0x69, 0x15, 0x3b, 0x01, 0x5f,
	0xa4, 0xb9, 0x75, 0x0b, 0x92, 0x41, 0x08, 0x03, 0x95, 0x97, 0xd9, 0x1b, 0xa9, 0xac, 0x6b, 0x1c,
	0xc4, 0xc3, 0x69, 0x27, 0xd4, 0x7a, 0xa6, 0xac, 0x8f, 0xda, 0xac, 0xe0, 0x87, 0x70, 0xef, 0x5a,
	0x88, 0xf5, 0x2b, 0xc7, 0xb2, 0xb1, 0xde, 0x67, 0xe2, 0x3e, 0xc8, 0xb8, 0xc8, 0xd3, 0xe4, 0x42,
	0x68, 0x1b, 0xfc, 0x36, 0x0b, 0x3d, 0x8e, 0xf0, 0xeb, 0x9b, 0x02, 0x17, 0x98, 0x3c, 0x68, 0x71,
	0xa2, 0xbf, 0x75, 0xa0, 0xff, 0xe6, 0xed, 0x4c, 0x5d, 0xe5, 0xc1, 0xf7, 0x01, 0xf8, 0x96, 0x6b,
	0x5e, 0xbe, 0xdf, 0x94, 0xa9, 0x4d, 0xe2, 0x91, 0xe1, 0xfc, 0xaa, 0x4c, 0x31, 0x36, 0xb1, 0xd4,
	0x3b, 0x32, 0x65, 0xc4, 0x88, 0xc6, 0x4c, 0x5a, 0x0a, 0x95, 0x88, 0xd2, 0x9a, 0x60, 0x51, 0xf0,
	0x19, 0x0c, 0xf2, 0x42, 0xa8, 0xf7, 0x32, 0x21, 0xbd, 0x47, 0xac, 0x8f, 0x70, 0x66, 0xa3, 0xa7,
	0x96, 0x1b, 0xbe, 0x74, 0x41, 0xae, 0x71, 0xf0, 0x39, 0x8c, 0x94, 0x8c, 0xd7, 0xef, 0x29, 0x03,
	0xfa, 0x46, 0x88, 0x8c, 0x97, 0x3c, 0x13, 0xf8, 0x61, 0x51, 0xe6, 0x5b, 0xa9, 0x62, 0x41, 0xb1,
	0x1a, 0xb1, 0x1a, 0x07, 0xdf, 0x83, 0xe1, 0x46, 0xc9, 0x9c, 0x8e, 0x1b, 0x92, 0x6c, 0x40, 0x78,
	0x96, 0x60, 0x08, 0x28, 0xf3, 0xca, 0x5d, 0x38, 0x32, 0x12, 0x0b, 0xd1, 0xda, 0x4a, 0x54, 0x95,
	0xfd, 0x0c, 0x8c, 0xb5, 0x96, 0x33, 0xa3, 0x9c, 0xae, 0xd0, 0xed, 0x47, 0xc6, 0x5a, 0xa4, 0xa3,
	0xff, 0xf8, 0x30, 0xc2, 0x22, 0x28, 0x5f, 0x70, 0xa9, 0xee, 0x54, 0xc1, 0x09, 0xf8, 0x1b, 0x99,
	0x58, 0xf7, 0x20, 0x89, 0x7b, 0xa4, 0x95, 0x4c, 0xac, 0x6f, 0x88, 0x46, 0x5e, 0x51, 0x59, 0xb7,
	0xf4, 0x18, 0xd1, 0x58, 0x2b, 0x95, 0xe6, 0x5a, 0xd8, 0xf8, 0x19, 0x50, 0xd7, 0x42, 0xbf, 0xa9,
	0x05, 0x5c, 0x99, 0x8a, 0xad, 0x48, 0x6d, 0xe1, 0x1a, 0x80, 0x46, 0x5a, 0xc5, 0x9d, 0xf9, 0x16,
	0x62, 0x7c, 0xe2, 0x52, 0xe0, 0xd6, 0x23, 0xca, 0x6f, 0x8b, 0x30, 0xb5, 0x31, 0xd3, 0x9f, 0xe7,
	0x4b, 0xa9, 0xc8, 0x76, 0x9f, 0x35, 0x0c, 0xcc, 0x19, 0x0b, 0xf2, 0x8d, 0x26, 0x0f, 0xf8, 0xac,
	0xc5, 0xc1, 0x5d, 0xb1, 0xc6, 0x67, 0x49, 0x78, 0x6c, 0xa2, 0x6e, 0x10, 0x6a, 0x2c, 0xe3, 0x5c,
	0x85, 0xf7, 0x8c, 0x6d, 0x48, 0xa3, 0x6e, 0x89, 0xe4, 0x19, 0x36, 0x9b, 0xfb, 0xa6, 0x06, 0x2c,
	0xa4, 0x7a, 0xb9, 0x29, 0xc2, 0xff, 0xb3, 0xf5, 0x72, 0x53, 0xe0, 0xb9, 0xc5, 0xb6, 0x58, 0x58,
	0x53, 0x4e, 0xc8, 0x94, 0x16, 0x07, 0xcf, 0x35, 0xe9, 0x18, 0x7e, 0x62, 0x92, 0xca, 0x20, 0xe4,
	0x0b, 0x25, 0xca, 0xe5, 0x2e, 0x0c, 0x8c, 0x3e, 0x06, 0x61, 0xce, 0xc8, 0xea, 0xa5, 0xb8, 0xbe,
	0x94, 0x22, 0xfc, 0xff, 0x53, 0xef, 0x6c, 0xc8, 0x6a, 0x1c, 0xfd, 0xc5, 0x73, 0xb1, 0x94, 0x4a,
	0x1e, 0xea, 0x68, 0xe4, 0xfb, 0xce, 0x21, 0xdf, 0xfb, 0x6d, 0xdf, 0xbb, 0x18, 0x77, 0x5b, 0x31,
	0x3e, 0x1c, 0xcf, 0x46, 0xfb, 0xfe, 0x9e, 0xf6, 0x98, 0xa2, 0x2b, 0xae, 0x94, 0x8d, 0x2a, 0xa6,
	0xa8, 0x81, 0x91, 0x86, 0x80, 0x54, 0x7c, 0x56, 0x4a, 0xa1, 0x12, 0x26, 0x7e, 0xbb, 0x11, 0x95,
	0x3e, 0x94, 0x77, 0x59, 0xb5, 0x74, 0x79, 0x97, 0x55, 0x4b, 0xea, 0xc7, 0xd8, 0xb3, 0x4c, 0x7b,
	0x24, 0x3a, 0x38, 0x83, 0xd1, 0x12, 0xf7, 0xc2, 0x4a, 0x27, 0xbd, 0x8e, 0xa6, 0x30, 0xa9, 0x1d,
	0xc0, 0x1a, 0x61, 0xf4, 0x10, 0x80, 0xf8, 0x5f, 0xa5, 0x3c, 0x5e, 0xdf, 0x3e, 0x2d, 0xfa, 0x35,
	0x1c, 0xb5, 0x74, 0x3a, 0x38, 0x0a, 0xa4, 0x75, 0xdc, 0x77, 0x3f, 0xfa, 0x0f, 0x1e, 0x0c, 0xcf,
	0x57, 0x5c, 0x3f, 0xe5, 0x9a, 0xe3, 0x56, 0x57, 0x65, 0x9e, 0xd9, 0xcd, 0x89, 0x3e, 0xb8, 0xbd,
	0xb5, 0xdf, 0x6f, 0xec, 0x6f, 0x79, 0xd4, 0x84, 0xc5, 0xc1, 0xef, 0xa0, 0xca, 0x9f, 0x7d, 0xe8,
	0xbe, 0xe0, 0x32, 0x6d, 0x59, 0x38, 0x22, 0x0b, 0x7f, 0x04, 0xc3, 0x8c, 0xcb, 0xf4, 0x95, 0x1b,
	0x78, 0xf7, 0xa7, 0xa3, 0xc9, 0x0b, 0xcb, 0x60, 0xb5, 0xe8, 0x60, 0x0c, 0x1e, 0x40, 0x4f, 0xaf,
	0x84, 0x1d, 0x7c, 0x23, 0x66, 0x80, 0xd3, 0xbf, 0xd7, 0xe8, 0xff, 0x13, 0x38, 0xe2, 0x5a, 0xf3,
	0x78, 0x95, 0x09, 0xa5, 0xab, 0xb0, 0x7f, 0xea, 0x9f, 0x1d, 0x4d, 0x47, 0x13, 0x37, 0x7f, 0x59,
	0x5b, 0x1a, 0x9c, 0xba, 0x64, 0x1b, 0x90, 0x32, 0x40, 0xca, 0x2c, 0x90, 0xe3, 0x12, 0x6f, 0x0c,
	0xc3, 0x8a, 0xae, 0x20, 0xb3, 0x84, 0xda, 0x40, 0x8f, 0xd5, 0xd8, 0xc8, 0xb0, 0x65, 0xcf, 0x4c,
	0x0f, 0x24, 0x99, 0xc1, 0x4d, 0xc2, 0x1f, 0xdd, 0x6a, 0x36, 0x42, 0x25, 0x34, 0x13, 0x8f, 0xc9,
	0x36, 0x07, 0x71, 0xbd, 0xac, 0x9e, 0x8a, 0xd4, 0xd6, 0xbf, 0x01, 0x74, 0x11, 0xb8, 0x5a, 0xce,
	0x5c, 0xf9, 0x1b, 0x40, 0xed, 0x95, 0x6f, 0x05, 0x55, 0xff, 0x90, 0x11, 0xbd, 0x1f, 0x9c, 0x93,
	0x8f, 0x05, 0xe7, 0x1c, 0x06, 0x5f, 0xf1, 0xe5, 0x07, 0xef, 0x22, 0xb7, 0x33, 0xe4, 0xe0, 0x5d,
	0x24, 0x7a, 0x67, 0x1b, 0xc0, 0x2f, 0x44, 0x99, 0x63, 0x10, 0xd2, 0x7a, 0x1f, 0x24, 0xed, 0xc6,
	0x9d, 0x7a, 0xe3, 0xc3, 0xe5, 0x8f, 0x5b, 0xaf, 0xf2, 0x4a, 0xd8, 0x44, 0x33, 0x20, 0x4a, 0x6c,
	0x09, 0xbd, 0xe0, 0x3a, 0x5e, 0x05, 0x8f, 0xa0, 0x9b, 0x49, 0x25, 0x69, 0xf3, 0x7d, 0x93, 0x88,
	0x8f, 0x27, 0x71, 0x49, 0x27, 0x0d, 0x59, 0x87, 0x4b, 0x1a, 0x11, 0x5c, 0xba, 0x91, 0x4a, 0x34,
	0x5d, 0xef, 0x44, 0x99, 0xbb, 0x36, 0x83, 0x74, 0xf4, 0xaf, 0x0e, 0x8c, 0xe8, 0x04, 0x9a, 0xde,
	0xad, 0x21, 0xe0, 0xed, 0x0f, 0x81, 0x43, 0x2e, 0x09, 0xa0, 0xcb, 0x93, 0xa4, 0xb4, 0x55, 0x43,
	0x34, 0xb6, 0xdf, 0xab, 0x92, 0x67, 0xe2, 0xa9, 0x48, 0x35, 0xb7, 0x27, 0xb5, 0x38, 0x78, 0x25,
	0xc9, 0xa4, 0x7a, 0xd6, 0x2c, 0x31, 0xed, 0x6d, 0x9f, 0x89, 0xa3, 0x25, 0x43, 0xa5, 0x28, 0x43,
	0xcc, 0x7d, 0xa3, 0x61, 0xe0, 0x19, 0x52, 0x15, 0x1b, 0x6d, 0x36, 0x30, 0x53, 0xac, 0xc5, 0x09,
	0x22, 0x18, 0x14, 0xdb, 0x82, 0x8a, 0x6b, 0x48, 0xf9, 0x3c, 0x9c, 0xcc, 0x5f, 0xcf, 0xa9, 0xb6,
	0x9c, 0x00, 0xf7, 0xd0, 0xab, 0x52, 0xf0, 0x84, 0x89, 0x78, 0x4b, 0x19, 0x3d, 0x64, 0x2d, 0x4e,
	0xf0, 0x05, 0xf4, 0x29, 0x55, 0xaa, 0x30, 0xa1, 0xca, 0x39, 0x9a, 0x34, 0xc1, 0x60, 0x56, 0x14,
	0xfd, 0xdd, 0x83, 0xe1, 0xfc, 0xf5, 0x7c, 0x86, 0x47, 0x1f, 0x6a, 0xa9, 0x3b, 0x7e, 0x6d, 0x83,
	0x8f, 0x24, 0x72, 0x2e, 0xb5, 0xbb, 0xa8, 0x21, 0x89, 0x9c, 0x22, 0xaf, 0xdc, 0x15, 0xbc, 0xc8,
	0x2b, 0xf2, 0x33, 0x4f, 0xd7, 0xee, 0x0a, 0x8e, 0x34, 0xe6, 0x07, 0x79, 0xd0, 0x7a, 0xc2, 0x80,
	0xe0, 0x18, 0xbc, 0x1b, 0x6b, 0xbc, 0x77, 0x83, 0x68, 0x67, 0xef, 0x97, 0xde, 0xae, 0x8e, 0xd6,
	0xa8, 0x89, 0x56, 0xb4, 0x26, 0x5d, 0xc9, 0xc9, 0xb8, 0x63, 0x42, 0xce, 0x33, 0xea, 0x1a, 0xd0,
	0x9c, 0xd3, 0x69, 0x9f, 0x83, 0x23, 0x56, 0x99, 0xfb, 0xc7, 0x90, 0x21, 0x19, 0xfc, 0x00, 0xfa,
	0xe4, 0x6d, 0xe7, 0x9b, 0xd1, 0xc4, 0x39, 0x81, 0x59, 0x41, 0x34, 0x81, 0x91, 0x3b, 0xac, 0xc2,
	0xf5, 0xb4, 0x55, 0x15, 0x7a, 0xcd, 0x7a, 0x92, 0x31, 0x2b, 0x88, 0x56, 0x00, 0x8c, 0xab, 0xf5,
	0x73, 0xa1, 0x96, 0x7a, 0x75, 0xc7, 0x95, 0x9f, 0x42, 0x3f, 0x25, 0x89, 0xd5, 0xcc, 0x22, 0x34,
	0xb3, 0xe4, 0x6a, 0xed, 0x92, 0x1c, 0xe9, 0xba, 0x50, 0xba, 0x87, 0x0b, 0x25, 0x9a, 0xc1, 0x11,
	0xcb, 0xf3, 0xec, 0x85, 0xc8, 0x28, 0xe3, 0x1f, 0xc3, 0x10, 0xd9, 0xd4, 0x2e, 0xee, 0xd6, 0x56,
	0x2d, 0xab, 0x6b, 0xa7, 0xd3, 0xaa, 0x9d, 0x6f, 0x3d, 0x18, 0xe2, 0x5e, 0xb4, 0xa0, 0xd1, 0xf9,
	0x1e, 0xe9, 0x1c, 0xc2, 0x20, 0xbf, 0x56, 0xd4, 0x13, 0xed, 0xbd, 0xdd, 0xc2, 0xe0, 0xa1, 0x7d,
	0xe9, 0xf8, 0xb7, 0x72, 0xd3, 0xbc, 0x79, 0x5c, 0xe8, 0xba, 0xfb, 0x85, 0x76, 0xfb, 0x45, 0xd3,
	0xb4, 0xec, 0xbe, 0x6d, 0xd9, 0xa8, 0xc9, 0x5e, 0xcb, 0x7e, 0x0c, 0x83, 0x4c, 0xe0, 0xdb, 0xa2,
	0x0a, 0x07, 0xe4, 0xf7, 0xe3, 0x49, 0xcb, 0x72, 0xe6, 0x84, 0xd1, 0x5f, 0x01, 0x8e, 0xe7, 0xaf,
	0xe7, 0xf4, 0xed, 0x62, 0xa7, 0xe2, 0xe0, 0x0b, 0xf0, 0xe3, 0x69, 0x65, 0xdd, 0xf1, 0xc9, 0xa4,
	0x2d, 0x9b, 0x9c, 0x4f, 0x17, 0x0c, 0xa5, 0xb8, 0xa8, 0x9a, 0xc6, 0x64, 0xdb, 0x9d, 0x45, 0x8b,
	0xe9, 0x39, 0x43, 0xe9, 0xf8, 0x9f, 0x5e, 0xbb, 0xbb, 0x38, 0xd3, 0xec, 0x30, 0xd6, 0xf6, 0x31,
	0x9b, 0x8a, 0x2b, 0xbd, 0x88, 0xf3, 0xd2, 0xe5, 0x5d, 0xc3, 0xc0, 0x2a, 0x2d, 0xe5, 0x72, 0x65,
	0xc5, 0x26, 0xcc, 0x2d, 0x4e, 0x30, 0x81, 0x41, 0x21, 0xd3, 0x94, 0x97, 0x58, 0x43, 0x68, 0xe2,
	0x83, 0x7d, 0x45, 0xe6, 0x24, 0x64, 0x6e, 0x51, 0x70, 0x06, 0x3d, 0xa9, 0x45, 0x56, 0x85, 0x3d,
	0x5a, 0x1d, 0xec, 0xaf, 0xa6, 0xb9, 0x68, 0x16, 0x8c, 0xa7, 0xd0, 0x37, 0x1f, 0x9b, 0x3a, 0xeb,
	0xb4, 0xea, 0xcc, 0x3d, 0xa3, 0xbd, 0x15, 0xa2, 0x6b, 0x5b, 0xbd, 0xde, 0xf5, 0xf8, 0x39, 0x74,
	0x69, 0x9c, 0xb8, 0xa7, 0xac, 0xd7, 0x7a, 0xca, 0x7e, 0x6c, 0x17, 0x9c, 0x79, 0x2a, 0x11, 0x37,
	0xae, 0xff, 0x13, 0x18, 0xff, 0xb1, 0x03, 0x70, 0xbe, 0x12, 0xf1, 0x7a, 0x9e, 0x4b, 0xa5, 0x31,
	0x9f, 0xca, 0x8d, 0x79, 0xf2, 0x9a, 0x7d, 0x1d, 0xa4, 0xa1, 0xc2, 0x2b, 0xfd, 0xd6, 0x95, 0x2d,
	0x01, 0xc7, 0x7d, 0x57, 0x8f, 0x1a, 0x04, 0xee, 0xce, 0x3e, 0x6b, 0x1d, 0xd7, 0x30, 0x50, 0xaa,
	0xc4, 0x8d, 0x95, 0x9a, 0x0e, 0xd4, 0x30, 0x50, 0x7a, 0x29, 0x96, 0xf6, 0xd9, 0x6d, 0x9b, 0x72,
	0xcd, 0xc0, 0x50, 0xc5, 0xa9, 0x14, 0x4a, 0x93, 0xd8, 0x36, 0xe5, 0x86, 0x83, 0xfa, 0xe0, 0x56,
	0x6f, 0x6d, 0x93, 0x32, 0xc0, 0x71, 0xdf, 0xd9, 0x3b, 0x85, 0x01, 0xe8, 0xc0, 0x4c, 0xaa, 0x77,
	0xf6, 0x32, 0x41, 0xf4, 0xf8, 0x91, 0x1d, 0x87, 0x5f, 0x2b, 0x2d, 0x4a, 0xd7, 0x38, 0xbd, 0xba,
	0x71, 0x8e, 0xbf, 0xb1, 0x93, 0x98, 0x32, 0xed, 0x8e, 0x98, 0xae, 0xd3, 0xad, 0x1c, 0x33, 0x20,
	0x38, 0x83, 0x4e, 0x5c, 0x90, 0x87, 0x8e, 0xa6, 0xe1, 0xad, 0x44, 0xaf, 0x5d, 0xcf, 0x3a, 0x71,
	0x31, 0xfe, 0x12, 0xba, 0xbf, 0xdc, 0x64, 0xc5, 0x81, 0x9d, 0xef, 0x43, 0x67, 0xeb, 0x42, 0xdb,
	0xd9, 0xde, 0x10, 0xde, 0x59, 0xaf, 0x77, 0xb6, 0xbb, 0xf1, 0x25, 0xf4, 0xed, 0xdf, 0x02, 0xbc,
	0xa4, 0x6d, 0x0b, 0xf7, 0x6d, 0xb6, 0x2d, 0x30, 0xa8, 0x58, 0x05, 0xf8, 0x42, 0x32, 0xa3, 0xdb,
	0x41, 0xfa, 0xbd, 0x82, 0x2a, 0x56, 0xa1, 0x7f, 0xea, 0xd3, 0xef, 0x15, 0x42, 0x94, 0x2b, 0x71,
	0xae, 0x4c, 0xbe, 0x63, 0xae, 0x20, 0x18, 0x7f, 0x03, 0xfe, 0xf9, 0x74, 0x11, 0x3c, 0x86, 0xee,
	0x6f, 0x36, 0xf6, 0xa7, 0xd0, 0x9d, 0xec, 0x46, 0xf5, 0x19, 0xc9, 0x83, 0x09, 0xf4, 0x04, 0xba,
	0xd1, 0xde, 0x5e, 0x6f, 0x59, 0xde, 0xb8, 0x99, 0x99, 0x65, 0xe3, 0xdf, 0x77, 0xc0, 0x5f, 0x4c,
	0xcf, 0x83, 0x27, 0x76, 0x2c, 0xb7, 0xba, 0xe5, 0x67, 0xfb, 0xdf, 0xd6, 0xc5, 0xce, 0x9a, 0x95,
	0xc1, 0x4f, 0xa1, 0x5f, 0x9a, 0xff, 0x28, 0xa6, 0x5b, 0xdc, 0x2a, 0x52, 0xe3, 0x1d, 0x66, 0xd7,
	0xe0, 0x21, 0xcd, 0x0d, 0xce, 0xa7, 0x3a, 0xfd, 0xec, 0x80, 0x82, 0xe6, 0x90, 0x7a, 0x65, 0xf0,
	0x25, 0xc0, 0xb2, 0x56, 0xdc, 0x76, 0x83, 0x0f, 0x1b, 0xd6, 0x5a, 0x5b, 0x7b, 0xad, 0xf7, 0x71,
	0xaf, 0x45, 0xff, 0xf5, 0x68, 0xa8, 0xd9, 0x60, 0x3e, 0x80, 0xde, 0x5a, 0xa6, 0xa9, 0x99, 0x69,
	0x3d, 0x66, 0xc0, 0x87, 0xae, 0x49, 0xcb, 0x5c, 0x09, 0x1b, 0x48, 0xa2, 0x31, 0xf0, 0x5b, 0x51,
	0xd2, 0x45, 0xcb, 0xbe, 0x2e, 0x2c, 0xc4, 0x96, 0x56, 0xd9, 0xbf, 0x4e, 0xbd, 0x8f, 0x78, 0xcb,
	0x2d, 0xc2, 0x0b, 0x6f, 0x13, 0x13, 0x61, 0x27, 0xd8, 0xc1, 0x30, 0x34, 0x63, 0xf8, 0xea, 0x03,
	0x63, 0x98, 0x32, 0x34, 0x79, 0x12, 0x2e, 0xed, 0x33, 0x22, 0x79, 0x12, 0xfd, 0xc3, 0x83, 0xe1,
	0x05, 0xaf, 0x56, 0xbc, 0xc8, 0xef, 0xfe, 0xad, 0x78, 0x04, 0x20, 0x6e, 0x74, 0xc9, 0x63, 0xfd,
	0x72, 0x93, 0xd9, 0x12, 0x68, 0x71, 0xd0, 0xca, 0xab, 0x52, 0x08, 0x14, 0x9a, 0x7a, 0x70, 0x30,
	0x88, 0xe0, 0x18, 0x4b, 0xfd, 0x59, 0x29, 0x44, 0xeb, 0x2f, 0xde, 0x1e, 0x0f, 0xfb, 0x4d, 0xa5,
	0x79, 0x69, 0x1a, 0x4a, 0xcf, 0xfc, 0x5f, 0xa8, 0x19, 0xed, 0x27, 0x44, 0x7f, 0xef, 0x09, 0x11,
	0x09, 0xb8, 0x77, 0x8e, 0x97, 0xf3, 0x9f, 0xc7, 0x5a, 0x6e, 0xa5, 0xde, 0x1d, 0x52, 0x3b, 0xde,
	0x94, 0xa5, 0x50, 0xfa, 0x29, 0xdf, 0x39, 0xb5, 0x1b, 0x0e, 0xde, 0x51, 0x79, 0x8a, 0x37, 0xc1,
	0xdd, 0x85, 0xa0, 0x25, 0x46, 0xf9, 0x7d, 0xe6, 0x65, 0x9f, 0xfe, 0xdc, 0xfe, 0xec, 0x7f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xbe, 0xbb, 0x6a, 0xe2, 0xdd, 0x15, 0x00, 0x00,
}
