// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inner.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InnerGamerLogout struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	LoginOhter           bool     `protobuf:"varint,2,opt,name=loginOhter" json:"loginOhter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerGamerLogout) Reset()         { *m = InnerGamerLogout{} }
func (m *InnerGamerLogout) String() string { return proto.CompactTextString(m) }
func (*InnerGamerLogout) ProtoMessage()    {}
func (*InnerGamerLogout) Descriptor() ([]byte, []int) {
	return fileDescriptor_inner_e74f80514ec10ac8, []int{0}
}
func (m *InnerGamerLogout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerGamerLogout.Unmarshal(m, b)
}
func (m *InnerGamerLogout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerGamerLogout.Marshal(b, m, deterministic)
}
func (dst *InnerGamerLogout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerGamerLogout.Merge(dst, src)
}
func (m *InnerGamerLogout) XXX_Size() int {
	return xxx_messageInfo_InnerGamerLogout.Size(m)
}
func (m *InnerGamerLogout) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerGamerLogout.DiscardUnknown(m)
}

var xxx_messageInfo_InnerGamerLogout proto.InternalMessageInfo

func (m *InnerGamerLogout) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InnerGamerLogout) GetLoginOhter() bool {
	if m != nil {
		return m.LoginOhter
	}
	return false
}

type InnerNewGamerFriendReq struct {
	Gid                  int32    `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Oid                  int32    `protobuf:"varint,2,opt,name=oid" json:"oid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerNewGamerFriendReq) Reset()         { *m = InnerNewGamerFriendReq{} }
func (m *InnerNewGamerFriendReq) String() string { return proto.CompactTextString(m) }
func (*InnerNewGamerFriendReq) ProtoMessage()    {}
func (*InnerNewGamerFriendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_inner_e74f80514ec10ac8, []int{1}
}
func (m *InnerNewGamerFriendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerNewGamerFriendReq.Unmarshal(m, b)
}
func (m *InnerNewGamerFriendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerNewGamerFriendReq.Marshal(b, m, deterministic)
}
func (dst *InnerNewGamerFriendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerNewGamerFriendReq.Merge(dst, src)
}
func (m *InnerNewGamerFriendReq) XXX_Size() int {
	return xxx_messageInfo_InnerNewGamerFriendReq.Size(m)
}
func (m *InnerNewGamerFriendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerNewGamerFriendReq.DiscardUnknown(m)
}

var xxx_messageInfo_InnerNewGamerFriendReq proto.InternalMessageInfo

func (m *InnerNewGamerFriendReq) GetGid() int32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *InnerNewGamerFriendReq) GetOid() int32 {
	if m != nil {
		return m.Oid
	}
	return 0
}

type InnerNewGamerFriend struct {
	Gid                  int32    `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Oid                  int32    `protobuf:"varint,2,opt,name=oid" json:"oid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerNewGamerFriend) Reset()         { *m = InnerNewGamerFriend{} }
func (m *InnerNewGamerFriend) String() string { return proto.CompactTextString(m) }
func (*InnerNewGamerFriend) ProtoMessage()    {}
func (*InnerNewGamerFriend) Descriptor() ([]byte, []int) {
	return fileDescriptor_inner_e74f80514ec10ac8, []int{2}
}
func (m *InnerNewGamerFriend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerNewGamerFriend.Unmarshal(m, b)
}
func (m *InnerNewGamerFriend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerNewGamerFriend.Marshal(b, m, deterministic)
}
func (dst *InnerNewGamerFriend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerNewGamerFriend.Merge(dst, src)
}
func (m *InnerNewGamerFriend) XXX_Size() int {
	return xxx_messageInfo_InnerNewGamerFriend.Size(m)
}
func (m *InnerNewGamerFriend) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerNewGamerFriend.DiscardUnknown(m)
}

var xxx_messageInfo_InnerNewGamerFriend proto.InternalMessageInfo

func (m *InnerNewGamerFriend) GetGid() int32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *InnerNewGamerFriend) GetOid() int32 {
	if m != nil {
		return m.Oid
	}
	return 0
}

type InnerDelGamerFriend struct {
	Gid                  int32    `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Oid                  int32    `protobuf:"varint,2,opt,name=oid" json:"oid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerDelGamerFriend) Reset()         { *m = InnerDelGamerFriend{} }
func (m *InnerDelGamerFriend) String() string { return proto.CompactTextString(m) }
func (*InnerDelGamerFriend) ProtoMessage()    {}
func (*InnerDelGamerFriend) Descriptor() ([]byte, []int) {
	return fileDescriptor_inner_e74f80514ec10ac8, []int{3}
}
func (m *InnerDelGamerFriend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerDelGamerFriend.Unmarshal(m, b)
}
func (m *InnerDelGamerFriend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerDelGamerFriend.Marshal(b, m, deterministic)
}
func (dst *InnerDelGamerFriend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerDelGamerFriend.Merge(dst, src)
}
func (m *InnerDelGamerFriend) XXX_Size() int {
	return xxx_messageInfo_InnerDelGamerFriend.Size(m)
}
func (m *InnerDelGamerFriend) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerDelGamerFriend.DiscardUnknown(m)
}

var xxx_messageInfo_InnerDelGamerFriend proto.InternalMessageInfo

func (m *InnerDelGamerFriend) GetGid() int32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *InnerDelGamerFriend) GetOid() int32 {
	if m != nil {
		return m.Oid
	}
	return 0
}

type InnerNewGamerChat struct {
	Gid                  int32     `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Chat                 *ChatData `protobuf:"bytes,2,opt,name=chat" json:"chat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *InnerNewGamerChat) Reset()         { *m = InnerNewGamerChat{} }
func (m *InnerNewGamerChat) String() string { return proto.CompactTextString(m) }
func (*InnerNewGamerChat) ProtoMessage()    {}
func (*InnerNewGamerChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_inner_e74f80514ec10ac8, []int{4}
}
func (m *InnerNewGamerChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerNewGamerChat.Unmarshal(m, b)
}
func (m *InnerNewGamerChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerNewGamerChat.Marshal(b, m, deterministic)
}
func (dst *InnerNewGamerChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerNewGamerChat.Merge(dst, src)
}
func (m *InnerNewGamerChat) XXX_Size() int {
	return xxx_messageInfo_InnerNewGamerChat.Size(m)
}
func (m *InnerNewGamerChat) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerNewGamerChat.DiscardUnknown(m)
}

var xxx_messageInfo_InnerNewGamerChat proto.InternalMessageInfo

func (m *InnerNewGamerChat) GetGid() int32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *InnerNewGamerChat) GetChat() *ChatData {
	if m != nil {
		return m.Chat
	}
	return nil
}

type InnerNewPVPResult struct {
	Gid                  int32    `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerNewPVPResult) Reset()         { *m = InnerNewPVPResult{} }
func (m *InnerNewPVPResult) String() string { return proto.CompactTextString(m) }
func (*InnerNewPVPResult) ProtoMessage()    {}
func (*InnerNewPVPResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_inner_e74f80514ec10ac8, []int{5}
}
func (m *InnerNewPVPResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerNewPVPResult.Unmarshal(m, b)
}
func (m *InnerNewPVPResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerNewPVPResult.Marshal(b, m, deterministic)
}
func (dst *InnerNewPVPResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerNewPVPResult.Merge(dst, src)
}
func (m *InnerNewPVPResult) XXX_Size() int {
	return xxx_messageInfo_InnerNewPVPResult.Size(m)
}
func (m *InnerNewPVPResult) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerNewPVPResult.DiscardUnknown(m)
}

var xxx_messageInfo_InnerNewPVPResult proto.InternalMessageInfo

func (m *InnerNewPVPResult) GetGid() int32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

type InnerMatchOk struct {
	Gid                  int32      `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	MatchInfo            *MatchInfo `protobuf:"bytes,2,opt,name=matchInfo" json:"matchInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InnerMatchOk) Reset()         { *m = InnerMatchOk{} }
func (m *InnerMatchOk) String() string { return proto.CompactTextString(m) }
func (*InnerMatchOk) ProtoMessage()    {}
func (*InnerMatchOk) Descriptor() ([]byte, []int) {
	return fileDescriptor_inner_e74f80514ec10ac8, []int{6}
}
func (m *InnerMatchOk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerMatchOk.Unmarshal(m, b)
}
func (m *InnerMatchOk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerMatchOk.Marshal(b, m, deterministic)
}
func (dst *InnerMatchOk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerMatchOk.Merge(dst, src)
}
func (m *InnerMatchOk) XXX_Size() int {
	return xxx_messageInfo_InnerMatchOk.Size(m)
}
func (m *InnerMatchOk) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerMatchOk.DiscardUnknown(m)
}

var xxx_messageInfo_InnerMatchOk proto.InternalMessageInfo

func (m *InnerMatchOk) GetGid() int32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *InnerMatchOk) GetMatchInfo() *MatchInfo {
	if m != nil {
		return m.MatchInfo
	}
	return nil
}

type InnerGetModelData struct {
	Gid                  int32    `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Typ                  int32    `protobuf:"varint,2,opt,name=typ" json:"typ,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerGetModelData) Reset()         { *m = InnerGetModelData{} }
func (m *InnerGetModelData) String() string { return proto.CompactTextString(m) }
func (*InnerGetModelData) ProtoMessage()    {}
func (*InnerGetModelData) Descriptor() ([]byte, []int) {
	return fileDescriptor_inner_e74f80514ec10ac8, []int{7}
}
func (m *InnerGetModelData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerGetModelData.Unmarshal(m, b)
}
func (m *InnerGetModelData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerGetModelData.Marshal(b, m, deterministic)
}
func (dst *InnerGetModelData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerGetModelData.Merge(dst, src)
}
func (m *InnerGetModelData) XXX_Size() int {
	return xxx_messageInfo_InnerGetModelData.Size(m)
}
func (m *InnerGetModelData) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerGetModelData.DiscardUnknown(m)
}

var xxx_messageInfo_InnerGetModelData proto.InternalMessageInfo

func (m *InnerGetModelData) GetGid() int32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *InnerGetModelData) GetTyp() int32 {
	if m != nil {
		return m.Typ
	}
	return 0
}

type InnerNewGamerMail struct {
	Gid                  int32    `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Mail                 *Mail    `protobuf:"bytes,2,opt,name=mail" json:"mail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerNewGamerMail) Reset()         { *m = InnerNewGamerMail{} }
func (m *InnerNewGamerMail) String() string { return proto.CompactTextString(m) }
func (*InnerNewGamerMail) ProtoMessage()    {}
func (*InnerNewGamerMail) Descriptor() ([]byte, []int) {
	return fileDescriptor_inner_e74f80514ec10ac8, []int{8}
}
func (m *InnerNewGamerMail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerNewGamerMail.Unmarshal(m, b)
}
func (m *InnerNewGamerMail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerNewGamerMail.Marshal(b, m, deterministic)
}
func (dst *InnerNewGamerMail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerNewGamerMail.Merge(dst, src)
}
func (m *InnerNewGamerMail) XXX_Size() int {
	return xxx_messageInfo_InnerNewGamerMail.Size(m)
}
func (m *InnerNewGamerMail) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerNewGamerMail.DiscardUnknown(m)
}

var xxx_messageInfo_InnerNewGamerMail proto.InternalMessageInfo

func (m *InnerNewGamerMail) GetGid() int32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *InnerNewGamerMail) GetMail() *Mail {
	if m != nil {
		return m.Mail
	}
	return nil
}

type InnerGamerExitPVP struct {
	Gid                  int32    `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerGamerExitPVP) Reset()         { *m = InnerGamerExitPVP{} }
func (m *InnerGamerExitPVP) String() string { return proto.CompactTextString(m) }
func (*InnerGamerExitPVP) ProtoMessage()    {}
func (*InnerGamerExitPVP) Descriptor() ([]byte, []int) {
	return fileDescriptor_inner_e74f80514ec10ac8, []int{9}
}
func (m *InnerGamerExitPVP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerGamerExitPVP.Unmarshal(m, b)
}
func (m *InnerGamerExitPVP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerGamerExitPVP.Marshal(b, m, deterministic)
}
func (dst *InnerGamerExitPVP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerGamerExitPVP.Merge(dst, src)
}
func (m *InnerGamerExitPVP) XXX_Size() int {
	return xxx_messageInfo_InnerGamerExitPVP.Size(m)
}
func (m *InnerGamerExitPVP) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerGamerExitPVP.DiscardUnknown(m)
}

var xxx_messageInfo_InnerGamerExitPVP proto.InternalMessageInfo

func (m *InnerGamerExitPVP) GetGid() int32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

type Inner struct {
	GamerLogout          *InnerGamerLogout       `protobuf:"bytes,1,opt,name=gamerLogout" json:"gamerLogout,omitempty"`
	NewFriendReq         *InnerNewGamerFriendReq `protobuf:"bytes,2,opt,name=newFriendReq" json:"newFriendReq,omitempty"`
	NewFriend            *InnerNewGamerFriend    `protobuf:"bytes,3,opt,name=newFriend" json:"newFriend,omitempty"`
	NewChat              *InnerNewGamerChat      `protobuf:"bytes,4,opt,name=newChat" json:"newChat,omitempty"`
	NewPVPResult         *InnerNewPVPResult      `protobuf:"bytes,5,opt,name=newPVPResult" json:"newPVPResult,omitempty"`
	MatchOk              *InnerMatchOk           `protobuf:"bytes,6,opt,name=matchOk" json:"matchOk,omitempty"`
	DelFriend            *InnerDelGamerFriend    `protobuf:"bytes,7,opt,name=delFriend" json:"delFriend,omitempty"`
	GetModelData         *InnerGetModelData      `protobuf:"bytes,8,opt,name=getModelData" json:"getModelData,omitempty"`
	NewGamerMail         *InnerNewGamerMail      `protobuf:"bytes,9,opt,name=newGamerMail" json:"newGamerMail,omitempty"`
	GamerExitPVP         *InnerGamerExitPVP      `protobuf:"bytes,10,opt,name=gamerExitPVP" json:"gamerExitPVP,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Inner) Reset()         { *m = Inner{} }
func (m *Inner) String() string { return proto.CompactTextString(m) }
func (*Inner) ProtoMessage()    {}
func (*Inner) Descriptor() ([]byte, []int) {
	return fileDescriptor_inner_e74f80514ec10ac8, []int{10}
}
func (m *Inner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inner.Unmarshal(m, b)
}
func (m *Inner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inner.Marshal(b, m, deterministic)
}
func (dst *Inner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inner.Merge(dst, src)
}
func (m *Inner) XXX_Size() int {
	return xxx_messageInfo_Inner.Size(m)
}
func (m *Inner) XXX_DiscardUnknown() {
	xxx_messageInfo_Inner.DiscardUnknown(m)
}

var xxx_messageInfo_Inner proto.InternalMessageInfo

func (m *Inner) GetGamerLogout() *InnerGamerLogout {
	if m != nil {
		return m.GamerLogout
	}
	return nil
}

func (m *Inner) GetNewFriendReq() *InnerNewGamerFriendReq {
	if m != nil {
		return m.NewFriendReq
	}
	return nil
}

func (m *Inner) GetNewFriend() *InnerNewGamerFriend {
	if m != nil {
		return m.NewFriend
	}
	return nil
}

func (m *Inner) GetNewChat() *InnerNewGamerChat {
	if m != nil {
		return m.NewChat
	}
	return nil
}

func (m *Inner) GetNewPVPResult() *InnerNewPVPResult {
	if m != nil {
		return m.NewPVPResult
	}
	return nil
}

func (m *Inner) GetMatchOk() *InnerMatchOk {
	if m != nil {
		return m.MatchOk
	}
	return nil
}

func (m *Inner) GetDelFriend() *InnerDelGamerFriend {
	if m != nil {
		return m.DelFriend
	}
	return nil
}

func (m *Inner) GetGetModelData() *InnerGetModelData {
	if m != nil {
		return m.GetModelData
	}
	return nil
}

func (m *Inner) GetNewGamerMail() *InnerNewGamerMail {
	if m != nil {
		return m.NewGamerMail
	}
	return nil
}

func (m *Inner) GetGamerExitPVP() *InnerGamerExitPVP {
	if m != nil {
		return m.GamerExitPVP
	}
	return nil
}

func init() {
	proto.RegisterType((*InnerGamerLogout)(nil), "InnerGamerLogout")
	proto.RegisterType((*InnerNewGamerFriendReq)(nil), "InnerNewGamerFriendReq")
	proto.RegisterType((*InnerNewGamerFriend)(nil), "InnerNewGamerFriend")
	proto.RegisterType((*InnerDelGamerFriend)(nil), "InnerDelGamerFriend")
	proto.RegisterType((*InnerNewGamerChat)(nil), "InnerNewGamerChat")
	proto.RegisterType((*InnerNewPVPResult)(nil), "InnerNewPVPResult")
	proto.RegisterType((*InnerMatchOk)(nil), "InnerMatchOk")
	proto.RegisterType((*InnerGetModelData)(nil), "InnerGetModelData")
	proto.RegisterType((*InnerNewGamerMail)(nil), "InnerNewGamerMail")
	proto.RegisterType((*InnerGamerExitPVP)(nil), "InnerGamerExitPVP")
	proto.RegisterType((*Inner)(nil), "Inner")
}

func init() { proto.RegisterFile("inner.proto", fileDescriptor_inner_e74f80514ec10ac8) }

var fileDescriptor_inner_e74f80514ec10ac8 = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x4f, 0x6f, 0x13, 0x31,
	0x10, 0xc5, 0x95, 0x34, 0xdb, 0x34, 0x93, 0x80, 0x5a, 0x83, 0xc0, 0x20, 0x81, 0xaa, 0x95, 0x10,
	0x39, 0xa0, 0x3d, 0xa4, 0x12, 0x08, 0xc1, 0x01, 0x41, 0xa0, 0x2a, 0x22, 0x34, 0x9a, 0x43, 0xef,
	0x4b, 0xd6, 0x6c, 0x2c, 0x76, 0xed, 0xb0, 0xb8, 0x0a, 0xfd, 0x26, 0x7c, 0x5c, 0xe4, 0xe9, 0xfe,
	0xb1, 0x53, 0x5f, 0x72, 0xcb, 0xce, 0xfc, 0xde, 0xcc, 0x3c, 0xf9, 0x29, 0x30, 0x96, 0x4a, 0x89,
	0x2a, 0xd9, 0x54, 0xda, 0xe8, 0xa7, 0x93, 0x95, 0x2e, 0x4b, 0xad, 0x6e, 0xbf, 0xe2, 0x8f, 0x70,
	0x7c, 0x61, 0x9b, 0xe7, 0x69, 0x29, 0xaa, 0x6f, 0x3a, 0xd7, 0xd7, 0x86, 0xdd, 0x87, 0xbe, 0xcc,
	0x78, 0xef, 0xb4, 0x37, 0x8d, 0xb0, 0x2f, 0x33, 0xf6, 0x1c, 0xa0, 0xd0, 0xb9, 0x54, 0x97, 0x6b,
	0x23, 0x2a, 0xde, 0x3f, 0xed, 0x4d, 0x8f, 0xd0, 0xa9, 0xc4, 0xef, 0xe1, 0x11, 0xcd, 0xf8, 0x2e,
	0xb6, 0x34, 0xe6, 0x4b, 0x25, 0x85, 0xca, 0x50, 0xfc, 0x66, 0xc7, 0x70, 0x90, 0xb7, 0xa3, 0xec,
	0x4f, 0x5b, 0xd1, 0x32, 0xa3, 0x21, 0x11, 0xda, 0x9f, 0xf1, 0x5b, 0x78, 0x10, 0x50, 0xef, 0x25,
	0x9d, 0x8b, 0x62, 0x5f, 0xe9, 0x1c, 0x4e, 0xbc, 0xad, 0x9f, 0xd6, 0xa9, 0x09, 0x08, 0x9f, 0xc1,
	0x60, 0xb5, 0x4e, 0x0d, 0x29, 0xc7, 0xb3, 0x51, 0x62, 0xb1, 0x79, 0x6a, 0x52, 0xa4, 0x72, 0xfc,
	0xa2, 0x9b, 0xb2, 0xbc, 0x5a, 0xa2, 0xf8, 0x73, 0x5d, 0x04, 0xa6, 0xc4, 0x5f, 0x61, 0x42, 0xd8,
	0x22, 0x35, 0xab, 0xf5, 0xe5, 0xaf, 0xc0, 0x9e, 0x29, 0x8c, 0x4a, 0xdb, 0xbc, 0x50, 0x3f, 0x75,
	0xbd, 0x0c, 0x92, 0x45, 0x53, 0xc1, 0xae, 0x19, 0xbf, 0xa9, 0x57, 0x9e, 0x0b, 0xb3, 0xd0, 0x99,
	0x28, 0xec, 0x35, 0x61, 0xc7, 0xe6, 0x66, 0xd3, 0x38, 0x36, 0x37, 0x9b, 0xf8, 0xc3, 0x8e, 0xe3,
	0x45, 0x2a, 0x8b, 0x80, 0xf0, 0x09, 0x0c, 0xca, 0x54, 0x16, 0xf5, 0x11, 0x51, 0x62, 0x31, 0xa4,
	0x52, 0xeb, 0x96, 0xe4, 0x9f, 0xff, 0x4a, 0xb3, 0xbc, 0x5a, 0x06, 0xdc, 0xfe, 0x1b, 0x40, 0x44,
	0x1c, 0x3b, 0x83, 0x71, 0xde, 0xe5, 0x8a, 0x98, 0xf1, 0xec, 0x24, 0xd9, 0x0d, 0x1c, 0xba, 0x14,
	0x7b, 0x07, 0x13, 0x25, 0xb6, 0x6d, 0x86, 0xea, 0x43, 0x1e, 0x27, 0xe1, 0x88, 0xa1, 0x07, 0xb3,
	0x19, 0x8c, 0xda, 0x6f, 0x7e, 0x40, 0xca, 0x87, 0x41, 0x65, 0x87, 0xb1, 0x57, 0x30, 0x54, 0x62,
	0x6b, 0x5f, 0x96, 0x0f, 0x48, 0xc1, 0x92, 0x3b, 0xd1, 0xc0, 0x06, 0x61, 0xaf, 0xe9, 0xbc, 0xf6,
	0xb5, 0x79, 0xb4, 0x23, 0x69, 0x3b, 0xe8, 0x71, 0xec, 0x25, 0x0c, 0xcb, 0xdb, 0xe7, 0xe7, 0x87,
	0x24, 0xb9, 0x97, 0xb8, 0x99, 0xc0, 0xa6, 0x6b, 0x2d, 0x64, 0xa2, 0xa8, 0x2d, 0x0c, 0x5d, 0x0b,
	0x7e, 0xcc, 0xb1, 0xc3, 0xec, 0x51, 0xb9, 0x93, 0x07, 0x7e, 0xe4, 0x1e, 0xe5, 0x26, 0x05, 0x3d,
	0xae, 0x36, 0xd3, 0xc6, 0x81, 0x8f, 0x42, 0xfe, 0x29, 0x01, 0x1e, 0x47, 0xfb, 0x9c, 0x10, 0x70,
	0xf0, 0xf6, 0x39, 0x1d, 0xf4, 0xb8, 0x1f, 0x87, 0xf4, 0xa7, 0x73, 0xf6, 0x3f, 0x00, 0x00, 0xff,
	0xff, 0x0b, 0x8b, 0x21, 0xa7, 0x91, 0x04, 0x00, 0x00,
}
