// Code generated by protoc-gen-go. DO NOT EDIT.
// source: redis_notify.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RedisNotifyGamerLogin struct {
	Psid                 int32    `protobuf:"varint,1,opt,name=psid" json:"psid,omitempty"`
	Gid                  int32    `protobuf:"varint,2,opt,name=gid" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisNotifyGamerLogin) Reset()         { *m = RedisNotifyGamerLogin{} }
func (m *RedisNotifyGamerLogin) String() string { return proto.CompactTextString(m) }
func (*RedisNotifyGamerLogin) ProtoMessage()    {}
func (*RedisNotifyGamerLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_redis_notify_48bba7c0900d81d8, []int{0}
}
func (m *RedisNotifyGamerLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisNotifyGamerLogin.Unmarshal(m, b)
}
func (m *RedisNotifyGamerLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisNotifyGamerLogin.Marshal(b, m, deterministic)
}
func (dst *RedisNotifyGamerLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisNotifyGamerLogin.Merge(dst, src)
}
func (m *RedisNotifyGamerLogin) XXX_Size() int {
	return xxx_messageInfo_RedisNotifyGamerLogin.Size(m)
}
func (m *RedisNotifyGamerLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisNotifyGamerLogin.DiscardUnknown(m)
}

var xxx_messageInfo_RedisNotifyGamerLogin proto.InternalMessageInfo

func (m *RedisNotifyGamerLogin) GetPsid() int32 {
	if m != nil {
		return m.Psid
	}
	return 0
}

func (m *RedisNotifyGamerLogin) GetGid() int32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

type RedisNotifyGamerLogout struct {
	Psid                 int32    `protobuf:"varint,1,opt,name=psid" json:"psid,omitempty"`
	Gid                  int32    `protobuf:"varint,2,opt,name=gid" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisNotifyGamerLogout) Reset()         { *m = RedisNotifyGamerLogout{} }
func (m *RedisNotifyGamerLogout) String() string { return proto.CompactTextString(m) }
func (*RedisNotifyGamerLogout) ProtoMessage()    {}
func (*RedisNotifyGamerLogout) Descriptor() ([]byte, []int) {
	return fileDescriptor_redis_notify_48bba7c0900d81d8, []int{1}
}
func (m *RedisNotifyGamerLogout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisNotifyGamerLogout.Unmarshal(m, b)
}
func (m *RedisNotifyGamerLogout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisNotifyGamerLogout.Marshal(b, m, deterministic)
}
func (dst *RedisNotifyGamerLogout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisNotifyGamerLogout.Merge(dst, src)
}
func (m *RedisNotifyGamerLogout) XXX_Size() int {
	return xxx_messageInfo_RedisNotifyGamerLogout.Size(m)
}
func (m *RedisNotifyGamerLogout) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisNotifyGamerLogout.DiscardUnknown(m)
}

var xxx_messageInfo_RedisNotifyGamerLogout proto.InternalMessageInfo

func (m *RedisNotifyGamerLogout) GetPsid() int32 {
	if m != nil {
		return m.Psid
	}
	return 0
}

func (m *RedisNotifyGamerLogout) GetGid() int32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

type RedisNotifyNewLogicArea struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisNotifyNewLogicArea) Reset()         { *m = RedisNotifyNewLogicArea{} }
func (m *RedisNotifyNewLogicArea) String() string { return proto.CompactTextString(m) }
func (*RedisNotifyNewLogicArea) ProtoMessage()    {}
func (*RedisNotifyNewLogicArea) Descriptor() ([]byte, []int) {
	return fileDescriptor_redis_notify_48bba7c0900d81d8, []int{2}
}
func (m *RedisNotifyNewLogicArea) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisNotifyNewLogicArea.Unmarshal(m, b)
}
func (m *RedisNotifyNewLogicArea) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisNotifyNewLogicArea.Marshal(b, m, deterministic)
}
func (dst *RedisNotifyNewLogicArea) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisNotifyNewLogicArea.Merge(dst, src)
}
func (m *RedisNotifyNewLogicArea) XXX_Size() int {
	return xxx_messageInfo_RedisNotifyNewLogicArea.Size(m)
}
func (m *RedisNotifyNewLogicArea) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisNotifyNewLogicArea.DiscardUnknown(m)
}

var xxx_messageInfo_RedisNotifyNewLogicArea proto.InternalMessageInfo

func (m *RedisNotifyNewLogicArea) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RedisNotifyNewGamer struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisNotifyNewGamer) Reset()         { *m = RedisNotifyNewGamer{} }
func (m *RedisNotifyNewGamer) String() string { return proto.CompactTextString(m) }
func (*RedisNotifyNewGamer) ProtoMessage()    {}
func (*RedisNotifyNewGamer) Descriptor() ([]byte, []int) {
	return fileDescriptor_redis_notify_48bba7c0900d81d8, []int{3}
}
func (m *RedisNotifyNewGamer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisNotifyNewGamer.Unmarshal(m, b)
}
func (m *RedisNotifyNewGamer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisNotifyNewGamer.Marshal(b, m, deterministic)
}
func (dst *RedisNotifyNewGamer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisNotifyNewGamer.Merge(dst, src)
}
func (m *RedisNotifyNewGamer) XXX_Size() int {
	return xxx_messageInfo_RedisNotifyNewGamer.Size(m)
}
func (m *RedisNotifyNewGamer) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisNotifyNewGamer.DiscardUnknown(m)
}

var xxx_messageInfo_RedisNotifyNewGamer proto.InternalMessageInfo

func (m *RedisNotifyNewGamer) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RedisNotifyGamerUpdate struct {
	Psid                 int32    `protobuf:"varint,1,opt,name=psid" json:"psid,omitempty"`
	Gid                  int32    `protobuf:"varint,2,opt,name=gid" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisNotifyGamerUpdate) Reset()         { *m = RedisNotifyGamerUpdate{} }
func (m *RedisNotifyGamerUpdate) String() string { return proto.CompactTextString(m) }
func (*RedisNotifyGamerUpdate) ProtoMessage()    {}
func (*RedisNotifyGamerUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_redis_notify_48bba7c0900d81d8, []int{4}
}
func (m *RedisNotifyGamerUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisNotifyGamerUpdate.Unmarshal(m, b)
}
func (m *RedisNotifyGamerUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisNotifyGamerUpdate.Marshal(b, m, deterministic)
}
func (dst *RedisNotifyGamerUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisNotifyGamerUpdate.Merge(dst, src)
}
func (m *RedisNotifyGamerUpdate) XXX_Size() int {
	return xxx_messageInfo_RedisNotifyGamerUpdate.Size(m)
}
func (m *RedisNotifyGamerUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisNotifyGamerUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_RedisNotifyGamerUpdate proto.InternalMessageInfo

func (m *RedisNotifyGamerUpdate) GetPsid() int32 {
	if m != nil {
		return m.Psid
	}
	return 0
}

func (m *RedisNotifyGamerUpdate) GetGid() int32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

type RedisNotifyNewGamerFriendReq struct {
	Gid                  int32    `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Oid                  int32    `protobuf:"varint,2,opt,name=oid" json:"oid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisNotifyNewGamerFriendReq) Reset()         { *m = RedisNotifyNewGamerFriendReq{} }
func (m *RedisNotifyNewGamerFriendReq) String() string { return proto.CompactTextString(m) }
func (*RedisNotifyNewGamerFriendReq) ProtoMessage()    {}
func (*RedisNotifyNewGamerFriendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_redis_notify_48bba7c0900d81d8, []int{5}
}
func (m *RedisNotifyNewGamerFriendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisNotifyNewGamerFriendReq.Unmarshal(m, b)
}
func (m *RedisNotifyNewGamerFriendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisNotifyNewGamerFriendReq.Marshal(b, m, deterministic)
}
func (dst *RedisNotifyNewGamerFriendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisNotifyNewGamerFriendReq.Merge(dst, src)
}
func (m *RedisNotifyNewGamerFriendReq) XXX_Size() int {
	return xxx_messageInfo_RedisNotifyNewGamerFriendReq.Size(m)
}
func (m *RedisNotifyNewGamerFriendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisNotifyNewGamerFriendReq.DiscardUnknown(m)
}

var xxx_messageInfo_RedisNotifyNewGamerFriendReq proto.InternalMessageInfo

func (m *RedisNotifyNewGamerFriendReq) GetGid() int32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *RedisNotifyNewGamerFriendReq) GetOid() int32 {
	if m != nil {
		return m.Oid
	}
	return 0
}

type RedisNotifyNewGamerFriend struct {
	Gid                  int32    `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Oid                  int32    `protobuf:"varint,2,opt,name=oid" json:"oid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisNotifyNewGamerFriend) Reset()         { *m = RedisNotifyNewGamerFriend{} }
func (m *RedisNotifyNewGamerFriend) String() string { return proto.CompactTextString(m) }
func (*RedisNotifyNewGamerFriend) ProtoMessage()    {}
func (*RedisNotifyNewGamerFriend) Descriptor() ([]byte, []int) {
	return fileDescriptor_redis_notify_48bba7c0900d81d8, []int{6}
}
func (m *RedisNotifyNewGamerFriend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisNotifyNewGamerFriend.Unmarshal(m, b)
}
func (m *RedisNotifyNewGamerFriend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisNotifyNewGamerFriend.Marshal(b, m, deterministic)
}
func (dst *RedisNotifyNewGamerFriend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisNotifyNewGamerFriend.Merge(dst, src)
}
func (m *RedisNotifyNewGamerFriend) XXX_Size() int {
	return xxx_messageInfo_RedisNotifyNewGamerFriend.Size(m)
}
func (m *RedisNotifyNewGamerFriend) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisNotifyNewGamerFriend.DiscardUnknown(m)
}

var xxx_messageInfo_RedisNotifyNewGamerFriend proto.InternalMessageInfo

func (m *RedisNotifyNewGamerFriend) GetGid() int32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *RedisNotifyNewGamerFriend) GetOid() int32 {
	if m != nil {
		return m.Oid
	}
	return 0
}

type RedisNotifyNewGamerChat struct {
	Gid                  int32    `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisNotifyNewGamerChat) Reset()         { *m = RedisNotifyNewGamerChat{} }
func (m *RedisNotifyNewGamerChat) String() string { return proto.CompactTextString(m) }
func (*RedisNotifyNewGamerChat) ProtoMessage()    {}
func (*RedisNotifyNewGamerChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_redis_notify_48bba7c0900d81d8, []int{7}
}
func (m *RedisNotifyNewGamerChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisNotifyNewGamerChat.Unmarshal(m, b)
}
func (m *RedisNotifyNewGamerChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisNotifyNewGamerChat.Marshal(b, m, deterministic)
}
func (dst *RedisNotifyNewGamerChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisNotifyNewGamerChat.Merge(dst, src)
}
func (m *RedisNotifyNewGamerChat) XXX_Size() int {
	return xxx_messageInfo_RedisNotifyNewGamerChat.Size(m)
}
func (m *RedisNotifyNewGamerChat) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisNotifyNewGamerChat.DiscardUnknown(m)
}

var xxx_messageInfo_RedisNotifyNewGamerChat proto.InternalMessageInfo

func (m *RedisNotifyNewGamerChat) GetGid() int32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *RedisNotifyNewGamerChat) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type RedisNotifyNewWorldChat struct {
	Server               int32    `protobuf:"varint,1,opt,name=server" json:"server,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisNotifyNewWorldChat) Reset()         { *m = RedisNotifyNewWorldChat{} }
func (m *RedisNotifyNewWorldChat) String() string { return proto.CompactTextString(m) }
func (*RedisNotifyNewWorldChat) ProtoMessage()    {}
func (*RedisNotifyNewWorldChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_redis_notify_48bba7c0900d81d8, []int{8}
}
func (m *RedisNotifyNewWorldChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisNotifyNewWorldChat.Unmarshal(m, b)
}
func (m *RedisNotifyNewWorldChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisNotifyNewWorldChat.Marshal(b, m, deterministic)
}
func (dst *RedisNotifyNewWorldChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisNotifyNewWorldChat.Merge(dst, src)
}
func (m *RedisNotifyNewWorldChat) XXX_Size() int {
	return xxx_messageInfo_RedisNotifyNewWorldChat.Size(m)
}
func (m *RedisNotifyNewWorldChat) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisNotifyNewWorldChat.DiscardUnknown(m)
}

var xxx_messageInfo_RedisNotifyNewWorldChat proto.InternalMessageInfo

func (m *RedisNotifyNewWorldChat) GetServer() int32 {
	if m != nil {
		return m.Server
	}
	return 0
}

func (m *RedisNotifyNewWorldChat) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type RedisNotifyNewWorldMail struct {
	Server               int32    `protobuf:"varint,1,opt,name=server" json:"server,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisNotifyNewWorldMail) Reset()         { *m = RedisNotifyNewWorldMail{} }
func (m *RedisNotifyNewWorldMail) String() string { return proto.CompactTextString(m) }
func (*RedisNotifyNewWorldMail) ProtoMessage()    {}
func (*RedisNotifyNewWorldMail) Descriptor() ([]byte, []int) {
	return fileDescriptor_redis_notify_48bba7c0900d81d8, []int{9}
}
func (m *RedisNotifyNewWorldMail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisNotifyNewWorldMail.Unmarshal(m, b)
}
func (m *RedisNotifyNewWorldMail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisNotifyNewWorldMail.Marshal(b, m, deterministic)
}
func (dst *RedisNotifyNewWorldMail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisNotifyNewWorldMail.Merge(dst, src)
}
func (m *RedisNotifyNewWorldMail) XXX_Size() int {
	return xxx_messageInfo_RedisNotifyNewWorldMail.Size(m)
}
func (m *RedisNotifyNewWorldMail) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisNotifyNewWorldMail.DiscardUnknown(m)
}

var xxx_messageInfo_RedisNotifyNewWorldMail proto.InternalMessageInfo

func (m *RedisNotifyNewWorldMail) GetServer() int32 {
	if m != nil {
		return m.Server
	}
	return 0
}

func (m *RedisNotifyNewWorldMail) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type RedisNotifyNewPVPResult struct {
	Gid                  int32    `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisNotifyNewPVPResult) Reset()         { *m = RedisNotifyNewPVPResult{} }
func (m *RedisNotifyNewPVPResult) String() string { return proto.CompactTextString(m) }
func (*RedisNotifyNewPVPResult) ProtoMessage()    {}
func (*RedisNotifyNewPVPResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_redis_notify_48bba7c0900d81d8, []int{10}
}
func (m *RedisNotifyNewPVPResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisNotifyNewPVPResult.Unmarshal(m, b)
}
func (m *RedisNotifyNewPVPResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisNotifyNewPVPResult.Marshal(b, m, deterministic)
}
func (dst *RedisNotifyNewPVPResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisNotifyNewPVPResult.Merge(dst, src)
}
func (m *RedisNotifyNewPVPResult) XXX_Size() int {
	return xxx_messageInfo_RedisNotifyNewPVPResult.Size(m)
}
func (m *RedisNotifyNewPVPResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisNotifyNewPVPResult.DiscardUnknown(m)
}

var xxx_messageInfo_RedisNotifyNewPVPResult proto.InternalMessageInfo

func (m *RedisNotifyNewPVPResult) GetGid() int32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

type RedisNotifyDelGamerFriend struct {
	Gid                  int32    `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Oid                  int32    `protobuf:"varint,2,opt,name=oid" json:"oid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisNotifyDelGamerFriend) Reset()         { *m = RedisNotifyDelGamerFriend{} }
func (m *RedisNotifyDelGamerFriend) String() string { return proto.CompactTextString(m) }
func (*RedisNotifyDelGamerFriend) ProtoMessage()    {}
func (*RedisNotifyDelGamerFriend) Descriptor() ([]byte, []int) {
	return fileDescriptor_redis_notify_48bba7c0900d81d8, []int{11}
}
func (m *RedisNotifyDelGamerFriend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisNotifyDelGamerFriend.Unmarshal(m, b)
}
func (m *RedisNotifyDelGamerFriend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisNotifyDelGamerFriend.Marshal(b, m, deterministic)
}
func (dst *RedisNotifyDelGamerFriend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisNotifyDelGamerFriend.Merge(dst, src)
}
func (m *RedisNotifyDelGamerFriend) XXX_Size() int {
	return xxx_messageInfo_RedisNotifyDelGamerFriend.Size(m)
}
func (m *RedisNotifyDelGamerFriend) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisNotifyDelGamerFriend.DiscardUnknown(m)
}

var xxx_messageInfo_RedisNotifyDelGamerFriend proto.InternalMessageInfo

func (m *RedisNotifyDelGamerFriend) GetGid() int32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *RedisNotifyDelGamerFriend) GetOid() int32 {
	if m != nil {
		return m.Oid
	}
	return 0
}

type RedisNotifyNewGamerMail struct {
	Gid                  int32    `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisNotifyNewGamerMail) Reset()         { *m = RedisNotifyNewGamerMail{} }
func (m *RedisNotifyNewGamerMail) String() string { return proto.CompactTextString(m) }
func (*RedisNotifyNewGamerMail) ProtoMessage()    {}
func (*RedisNotifyNewGamerMail) Descriptor() ([]byte, []int) {
	return fileDescriptor_redis_notify_48bba7c0900d81d8, []int{12}
}
func (m *RedisNotifyNewGamerMail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisNotifyNewGamerMail.Unmarshal(m, b)
}
func (m *RedisNotifyNewGamerMail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisNotifyNewGamerMail.Marshal(b, m, deterministic)
}
func (dst *RedisNotifyNewGamerMail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisNotifyNewGamerMail.Merge(dst, src)
}
func (m *RedisNotifyNewGamerMail) XXX_Size() int {
	return xxx_messageInfo_RedisNotifyNewGamerMail.Size(m)
}
func (m *RedisNotifyNewGamerMail) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisNotifyNewGamerMail.DiscardUnknown(m)
}

var xxx_messageInfo_RedisNotifyNewGamerMail proto.InternalMessageInfo

func (m *RedisNotifyNewGamerMail) GetGid() int32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *RedisNotifyNewGamerMail) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type RedisNotifyAccessToken struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken" json:"accessToken,omitempty"`
	NextUpdateTime       int64    `protobuf:"varint,2,opt,name=nextUpdateTime" json:"nextUpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisNotifyAccessToken) Reset()         { *m = RedisNotifyAccessToken{} }
func (m *RedisNotifyAccessToken) String() string { return proto.CompactTextString(m) }
func (*RedisNotifyAccessToken) ProtoMessage()    {}
func (*RedisNotifyAccessToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_redis_notify_48bba7c0900d81d8, []int{13}
}
func (m *RedisNotifyAccessToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisNotifyAccessToken.Unmarshal(m, b)
}
func (m *RedisNotifyAccessToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisNotifyAccessToken.Marshal(b, m, deterministic)
}
func (dst *RedisNotifyAccessToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisNotifyAccessToken.Merge(dst, src)
}
func (m *RedisNotifyAccessToken) XXX_Size() int {
	return xxx_messageInfo_RedisNotifyAccessToken.Size(m)
}
func (m *RedisNotifyAccessToken) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisNotifyAccessToken.DiscardUnknown(m)
}

var xxx_messageInfo_RedisNotifyAccessToken proto.InternalMessageInfo

func (m *RedisNotifyAccessToken) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *RedisNotifyAccessToken) GetNextUpdateTime() int64 {
	if m != nil {
		return m.NextUpdateTime
	}
	return 0
}

type RedisNotify struct {
	GamerLogin           *RedisNotifyGamerLogin        `protobuf:"bytes,1,opt,name=gamerLogin" json:"gamerLogin,omitempty"`
	GamerLogout          *RedisNotifyGamerLogout       `protobuf:"bytes,2,opt,name=gamerLogout" json:"gamerLogout,omitempty"`
	NewLogicArea         *RedisNotifyNewLogicArea      `protobuf:"bytes,3,opt,name=newLogicArea" json:"newLogicArea,omitempty"`
	NewGamer             *RedisNotifyNewGamer          `protobuf:"bytes,4,opt,name=newGamer" json:"newGamer,omitempty"`
	GamerUpdate          *RedisNotifyGamerUpdate       `protobuf:"bytes,5,opt,name=gamerUpdate" json:"gamerUpdate,omitempty"`
	NewFriendReq         *RedisNotifyNewGamerFriendReq `protobuf:"bytes,6,opt,name=newFriendReq" json:"newFriendReq,omitempty"`
	NewFriend            *RedisNotifyNewGamerFriend    `protobuf:"bytes,7,opt,name=newFriend" json:"newFriend,omitempty"`
	NewGamerChat         *RedisNotifyNewGamerChat      `protobuf:"bytes,8,opt,name=newGamerChat" json:"newGamerChat,omitempty"`
	NewWorldChat         *RedisNotifyNewWorldChat      `protobuf:"bytes,9,opt,name=newWorldChat" json:"newWorldChat,omitempty"`
	NewWorldMail         *RedisNotifyNewWorldMail      `protobuf:"bytes,10,opt,name=newWorldMail" json:"newWorldMail,omitempty"`
	NewPVPResult         *RedisNotifyNewPVPResult      `protobuf:"bytes,11,opt,name=newPVPResult" json:"newPVPResult,omitempty"`
	DelFriend            *RedisNotifyDelGamerFriend    `protobuf:"bytes,12,opt,name=delFriend" json:"delFriend,omitempty"`
	NewGamerMail         *RedisNotifyNewGamerMail      `protobuf:"bytes,13,opt,name=newGamerMail" json:"newGamerMail,omitempty"`
	AccessToken          *RedisNotifyAccessToken       `protobuf:"bytes,14,opt,name=accessToken" json:"accessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *RedisNotify) Reset()         { *m = RedisNotify{} }
func (m *RedisNotify) String() string { return proto.CompactTextString(m) }
func (*RedisNotify) ProtoMessage()    {}
func (*RedisNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_redis_notify_48bba7c0900d81d8, []int{14}
}
func (m *RedisNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisNotify.Unmarshal(m, b)
}
func (m *RedisNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisNotify.Marshal(b, m, deterministic)
}
func (dst *RedisNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisNotify.Merge(dst, src)
}
func (m *RedisNotify) XXX_Size() int {
	return xxx_messageInfo_RedisNotify.Size(m)
}
func (m *RedisNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisNotify.DiscardUnknown(m)
}

var xxx_messageInfo_RedisNotify proto.InternalMessageInfo

func (m *RedisNotify) GetGamerLogin() *RedisNotifyGamerLogin {
	if m != nil {
		return m.GamerLogin
	}
	return nil
}

func (m *RedisNotify) GetGamerLogout() *RedisNotifyGamerLogout {
	if m != nil {
		return m.GamerLogout
	}
	return nil
}

func (m *RedisNotify) GetNewLogicArea() *RedisNotifyNewLogicArea {
	if m != nil {
		return m.NewLogicArea
	}
	return nil
}

func (m *RedisNotify) GetNewGamer() *RedisNotifyNewGamer {
	if m != nil {
		return m.NewGamer
	}
	return nil
}

func (m *RedisNotify) GetGamerUpdate() *RedisNotifyGamerUpdate {
	if m != nil {
		return m.GamerUpdate
	}
	return nil
}

func (m *RedisNotify) GetNewFriendReq() *RedisNotifyNewGamerFriendReq {
	if m != nil {
		return m.NewFriendReq
	}
	return nil
}

func (m *RedisNotify) GetNewFriend() *RedisNotifyNewGamerFriend {
	if m != nil {
		return m.NewFriend
	}
	return nil
}

func (m *RedisNotify) GetNewGamerChat() *RedisNotifyNewGamerChat {
	if m != nil {
		return m.NewGamerChat
	}
	return nil
}

func (m *RedisNotify) GetNewWorldChat() *RedisNotifyNewWorldChat {
	if m != nil {
		return m.NewWorldChat
	}
	return nil
}

func (m *RedisNotify) GetNewWorldMail() *RedisNotifyNewWorldMail {
	if m != nil {
		return m.NewWorldMail
	}
	return nil
}

func (m *RedisNotify) GetNewPVPResult() *RedisNotifyNewPVPResult {
	if m != nil {
		return m.NewPVPResult
	}
	return nil
}

func (m *RedisNotify) GetDelFriend() *RedisNotifyDelGamerFriend {
	if m != nil {
		return m.DelFriend
	}
	return nil
}

func (m *RedisNotify) GetNewGamerMail() *RedisNotifyNewGamerMail {
	if m != nil {
		return m.NewGamerMail
	}
	return nil
}

func (m *RedisNotify) GetAccessToken() *RedisNotifyAccessToken {
	if m != nil {
		return m.AccessToken
	}
	return nil
}

func init() {
	proto.RegisterType((*RedisNotifyGamerLogin)(nil), "RedisNotifyGamerLogin")
	proto.RegisterType((*RedisNotifyGamerLogout)(nil), "RedisNotifyGamerLogout")
	proto.RegisterType((*RedisNotifyNewLogicArea)(nil), "RedisNotifyNewLogicArea")
	proto.RegisterType((*RedisNotifyNewGamer)(nil), "RedisNotifyNewGamer")
	proto.RegisterType((*RedisNotifyGamerUpdate)(nil), "RedisNotifyGamerUpdate")
	proto.RegisterType((*RedisNotifyNewGamerFriendReq)(nil), "RedisNotifyNewGamerFriendReq")
	proto.RegisterType((*RedisNotifyNewGamerFriend)(nil), "RedisNotifyNewGamerFriend")
	proto.RegisterType((*RedisNotifyNewGamerChat)(nil), "RedisNotifyNewGamerChat")
	proto.RegisterType((*RedisNotifyNewWorldChat)(nil), "RedisNotifyNewWorldChat")
	proto.RegisterType((*RedisNotifyNewWorldMail)(nil), "RedisNotifyNewWorldMail")
	proto.RegisterType((*RedisNotifyNewPVPResult)(nil), "RedisNotifyNewPVPResult")
	proto.RegisterType((*RedisNotifyDelGamerFriend)(nil), "RedisNotifyDelGamerFriend")
	proto.RegisterType((*RedisNotifyNewGamerMail)(nil), "RedisNotifyNewGamerMail")
	proto.RegisterType((*RedisNotifyAccessToken)(nil), "RedisNotifyAccessToken")
	proto.RegisterType((*RedisNotify)(nil), "RedisNotify")
}

func init() { proto.RegisterFile("redis_notify.proto", fileDescriptor_redis_notify_48bba7c0900d81d8) }

var fileDescriptor_redis_notify_48bba7c0900d81d8 = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x6b, 0x6b, 0x13, 0x41,
	0x14, 0x25, 0x8f, 0xc6, 0xe6, 0x6e, 0x0d, 0x32, 0x6a, 0x32, 0x8a, 0x42, 0x59, 0x50, 0x14, 0x61,
	0x91, 0x0a, 0x62, 0xc1, 0x07, 0xf1, 0xf9, 0x45, 0x4b, 0xb9, 0x54, 0xfd, 0x28, 0xdb, 0xcc, 0x18,
	0x07, 0xb7, 0x3b, 0x71, 0x76, 0xeb, 0xe3, 0x77, 0xfa, 0x87, 0x64, 0x6f, 0xd6, 0xd9, 0x99, 0x64,
	0xb6, 0xa4, 0xd0, 0x6f, 0x33, 0xf7, 0x9e, 0x73, 0xee, 0xdd, 0xc3, 0x1c, 0x16, 0x98, 0x91, 0x42,
	0x15, 0x5f, 0x72, 0x5d, 0xaa, 0xaf, 0x7f, 0x92, 0x85, 0xd1, 0xa5, 0x8e, 0x9f, 0xc1, 0x75, 0xac,
	0xaa, 0x07, 0x54, 0x7c, 0x97, 0x9e, 0x48, 0xf3, 0x5e, 0xcf, 0x55, 0xce, 0x18, 0xf4, 0x17, 0x85,
	0x12, 0xbc, 0xb3, 0xdb, 0xb9, 0xb7, 0x85, 0x74, 0x66, 0x57, 0xa0, 0x37, 0x57, 0x82, 0x77, 0xa9,
	0x54, 0x1d, 0xe3, 0xe7, 0x30, 0x0e, 0xd0, 0xf5, 0x69, 0xb9, 0x21, 0xff, 0x3e, 0x4c, 0x1c, 0xfe,
	0x81, 0xfc, 0x55, 0x0d, 0x9f, 0x4d, 0x8d, 0x4c, 0xd9, 0x08, 0xba, 0x96, 0xde, 0x55, 0x22, 0xbe,
	0x03, 0x57, 0x7d, 0x28, 0x4d, 0x5b, 0x83, 0x05, 0x36, 0xfa, 0xb8, 0x10, 0x69, 0x29, 0x37, 0xdc,
	0xe8, 0x25, 0xdc, 0x0a, 0x8c, 0x79, 0x6b, 0x94, 0xcc, 0x05, 0xca, 0x1f, 0xff, 0x19, 0x1d, 0xcb,
	0xa8, 0x2a, 0xba, 0xd1, 0xd0, 0x4a, 0xc4, 0x2f, 0xe0, 0x46, 0xab, 0xc6, 0x86, 0x02, 0x93, 0x80,
	0xc0, 0xab, 0x6f, 0x69, 0x19, 0xa0, 0x33, 0xe8, 0x8b, 0xb4, 0x4c, 0x89, 0x3f, 0x44, 0x3a, 0xc7,
	0x6f, 0x56, 0x05, 0x3e, 0x6b, 0x93, 0x09, 0x12, 0x18, 0xc3, 0xa0, 0x90, 0xe6, 0xa7, 0x34, 0xb5,
	0x46, 0x7d, 0x3b, 0x87, 0xcc, 0x87, 0x54, 0x65, 0xe7, 0x92, 0x79, 0xb0, 0x2a, 0x73, 0xf8, 0xe9,
	0x10, 0x65, 0x71, 0x9a, 0x05, 0x3e, 0x67, 0xc5, 0xbc, 0xd7, 0x32, 0xbb, 0x18, 0xf3, 0x68, 0xe9,
	0xcd, 0xcc, 0x3b, 0xf6, 0x9e, 0xd0, 0x74, 0x36, 0x93, 0x45, 0x71, 0xa4, 0xbf, 0xcb, 0x9c, 0xed,
	0x42, 0x94, 0x36, 0x57, 0xd2, 0x19, 0xa2, 0x5b, 0x62, 0x77, 0x61, 0x94, 0xcb, 0xdf, 0xe5, 0xf2,
	0xc9, 0x1d, 0xa9, 0x13, 0x49, 0xca, 0x3d, 0x5c, 0xa9, 0xc6, 0x7f, 0x07, 0x10, 0x39, 0x43, 0xd8,
	0x63, 0x80, 0xb9, 0x0d, 0x1f, 0x09, 0x47, 0x7b, 0xe3, 0x24, 0x18, 0x4d, 0x74, 0x90, 0x6c, 0x1f,
	0xa2, 0x79, 0x93, 0x3a, 0x1a, 0x16, 0xed, 0x4d, 0x92, 0x70, 0x28, 0xd1, 0xc5, 0xb2, 0xa7, 0xb0,
	0x93, 0x3b, 0x81, 0xe3, 0x3d, 0xe2, 0xf2, 0xa4, 0x25, 0x90, 0xe8, 0xa1, 0xd9, 0x43, 0xd8, 0xce,
	0x6b, 0x6b, 0x79, 0x9f, 0x98, 0xd7, 0x92, 0x80, 0xed, 0x68, 0x51, 0x76, 0xd5, 0xa5, 0x0b, 0x7c,
	0xab, 0x65, 0xd5, 0x65, 0x1b, 0x5d, 0x2c, 0x9b, 0xd2, 0xaa, 0x36, 0x84, 0x7c, 0x40, 0xdc, 0xdb,
	0xc9, 0x59, 0x49, 0x45, 0x8f, 0xc2, 0x9e, 0xc0, 0xd0, 0xde, 0xf9, 0x25, 0xe2, 0xdf, 0x3c, 0x83,
	0xdf, 0x80, 0x6b, 0x9f, 0x6c, 0x02, 0xf9, 0x76, 0xd0, 0x27, 0xdb, 0x47, 0x0f, 0x5d, 0xb3, 0x6d,
	0xfc, 0xf8, 0x30, 0xc8, 0xb6, 0x7d, 0xf4, 0xd0, 0x2e, 0xbb, 0x7a, 0xc0, 0x1c, 0xda, 0xd9, 0x55,
	0x1f, 0x3d, 0x74, 0xcd, 0xb6, 0x61, 0xe3, 0x51, 0x90, 0x6d, 0xfb, 0xe8, 0xa1, 0x2b, 0xc7, 0x84,
	0xcc, 0x6a, 0xc7, 0x76, 0xd6, 0x1d, 0xf3, 0xa3, 0x89, 0x0d, 0xd8, 0x75, 0x8c, 0xb6, 0xbe, 0xdc,
	0xee, 0x98, 0xdd, 0xba, 0x09, 0xe9, 0xbe, 0x1f, 0xb2, 0xd1, 0xfa, 0x3b, 0x71, 0x22, 0xe9, 0xa5,
	0xef, 0x78, 0x40, 0x3f, 0xb5, 0x47, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x04, 0xb7, 0xa6, 0x5e,
	0xea, 0x06, 0x00, 0x00,
}
