// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServerHello struct {
	Info                 *ServerInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Mss                  []string    `protobuf:"bytes,2,rep,name=mss" json:"mss,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ServerHello) Reset()         { *m = ServerHello{} }
func (m *ServerHello) String() string { return proto.CompactTextString(m) }
func (*ServerHello) ProtoMessage()    {}
func (*ServerHello) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_b348f1a917968e3b, []int{0}
}
func (m *ServerHello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerHello.Unmarshal(m, b)
}
func (m *ServerHello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerHello.Marshal(b, m, deterministic)
}
func (dst *ServerHello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerHello.Merge(dst, src)
}
func (m *ServerHello) XXX_Size() int {
	return xxx_messageInfo_ServerHello.Size(m)
}
func (m *ServerHello) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerHello.DiscardUnknown(m)
}

var xxx_messageInfo_ServerHello proto.InternalMessageInfo

func (m *ServerHello) GetInfo() *ServerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ServerHello) GetMss() []string {
	if m != nil {
		return m.Mss
	}
	return nil
}

// RPC通知玩家消息
type GamerNotify struct {
	Ids                  []int32  `protobuf:"varint,1,rep,packed,name=ids" json:"ids,omitempty"`
	S2C                  *S2C     `protobuf:"bytes,2,opt,name=s2c" json:"s2c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GamerNotify) Reset()         { *m = GamerNotify{} }
func (m *GamerNotify) String() string { return proto.CompactTextString(m) }
func (*GamerNotify) ProtoMessage()    {}
func (*GamerNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_b348f1a917968e3b, []int{1}
}
func (m *GamerNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamerNotify.Unmarshal(m, b)
}
func (m *GamerNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamerNotify.Marshal(b, m, deterministic)
}
func (dst *GamerNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamerNotify.Merge(dst, src)
}
func (m *GamerNotify) XXX_Size() int {
	return xxx_messageInfo_GamerNotify.Size(m)
}
func (m *GamerNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_GamerNotify.DiscardUnknown(m)
}

var xxx_messageInfo_GamerNotify proto.InternalMessageInfo

func (m *GamerNotify) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *GamerNotify) GetS2C() *S2C {
	if m != nil {
		return m.S2C
	}
	return nil
}

// 合并链路消息
type GamerNotifyList struct {
	Data                 []*GamerNotify `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GamerNotifyList) Reset()         { *m = GamerNotifyList{} }
func (m *GamerNotifyList) String() string { return proto.CompactTextString(m) }
func (*GamerNotifyList) ProtoMessage()    {}
func (*GamerNotifyList) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_b348f1a917968e3b, []int{2}
}
func (m *GamerNotifyList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamerNotifyList.Unmarshal(m, b)
}
func (m *GamerNotifyList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamerNotifyList.Marshal(b, m, deterministic)
}
func (dst *GamerNotifyList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamerNotifyList.Merge(dst, src)
}
func (m *GamerNotifyList) XXX_Size() int {
	return xxx_messageInfo_GamerNotifyList.Size(m)
}
func (m *GamerNotifyList) XXX_DiscardUnknown() {
	xxx_messageInfo_GamerNotifyList.DiscardUnknown(m)
}

var xxx_messageInfo_GamerNotifyList proto.InternalMessageInfo

func (m *GamerNotifyList) GetData() []*GamerNotify {
	if m != nil {
		return m.Data
	}
	return nil
}

// RPC通知玩家消息
type GamerExitPVP struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GamerExitPVP) Reset()         { *m = GamerExitPVP{} }
func (m *GamerExitPVP) String() string { return proto.CompactTextString(m) }
func (*GamerExitPVP) ProtoMessage()    {}
func (*GamerExitPVP) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_b348f1a917968e3b, []int{3}
}
func (m *GamerExitPVP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamerExitPVP.Unmarshal(m, b)
}
func (m *GamerExitPVP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamerExitPVP.Marshal(b, m, deterministic)
}
func (dst *GamerExitPVP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamerExitPVP.Merge(dst, src)
}
func (m *GamerExitPVP) XXX_Size() int {
	return xxx_messageInfo_GamerExitPVP.Size(m)
}
func (m *GamerExitPVP) XXX_DiscardUnknown() {
	xxx_messageInfo_GamerExitPVP.DiscardUnknown(m)
}

var xxx_messageInfo_GamerExitPVP proto.InternalMessageInfo

func (m *GamerExitPVP) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RPC struct {
	Id                   int32                      `protobuf:"varint,2000,opt,name=id" json:"id,omitempty"`
	ServerHello          *ServerHello               `protobuf:"bytes,2001,opt,name=serverHello" json:"serverHello,omitempty"`
	GamerNotify          *GamerNotify               `protobuf:"bytes,2002,opt,name=gamerNotify" json:"gamerNotify,omitempty"`
	GamerNotifyList      *GamerNotifyList           `protobuf:"bytes,2003,opt,name=gamerNotifyList" json:"gamerNotifyList,omitempty"`
	GamerExitPVP         *GamerExitPVP              `protobuf:"bytes,2004,opt,name=gamerExitPVP" json:"gamerExitPVP,omitempty"`
	TestChatC2S          *GamerTestChatC2S          `protobuf:"bytes,1,opt,name=testChatC2S" json:"testChatC2S,omitempty"`
	TestChatS2C          *GamerTestChatS2C          `protobuf:"bytes,2,opt,name=testChatS2C" json:"testChatS2C,omitempty"`
	MatchC2S             *GamerMatchC2S             `protobuf:"bytes,3,opt,name=matchC2S" json:"matchC2S,omitempty"`
	MatchS2C             *GamerMatchS2C             `protobuf:"bytes,4,opt,name=matchS2C" json:"matchS2C,omitempty"`
	CheckPVPBattleC2S    *GamerCheckPVPBattleC2S    `protobuf:"bytes,7,opt,name=checkPVPBattleC2S" json:"checkPVPBattleC2S,omitempty"`
	CheckPVPBattleS2C    *GamerCheckPVPBattleS2C    `protobuf:"bytes,8,opt,name=checkPVPBattleS2C" json:"checkPVPBattleS2C,omitempty"`
	GamerNewRoomC2S      *GamerNewRoomC2S           `protobuf:"bytes,9,opt,name=gamerNewRoomC2S" json:"gamerNewRoomC2S,omitempty"`
	GamerNewRoomS2C      *GamerNewRoomS2C           `protobuf:"bytes,10,opt,name=gamerNewRoomS2C" json:"gamerNewRoomS2C,omitempty"`
	GamerAddRoomC2S      *GamerAddRoomC2S           `protobuf:"bytes,11,opt,name=gamerAddRoomC2S" json:"gamerAddRoomC2S,omitempty"`
	GamerAddRoomS2C      *GamerAddRoomS2C           `protobuf:"bytes,12,opt,name=gamerAddRoomS2C" json:"gamerAddRoomS2C,omitempty"`
	GamerLeaveRoomC2S    *GamerLeaveRoomC2S         `protobuf:"bytes,13,opt,name=gamerLeaveRoomC2S" json:"gamerLeaveRoomC2S,omitempty"`
	GamerLeaveRoomS2C    *GamerLeaveRoomS2C         `protobuf:"bytes,14,opt,name=gamerLeaveRoomS2C" json:"gamerLeaveRoomS2C,omitempty"`
	GamerPVPStateSyncC2S *GamerPVPStateSyncC2S      `protobuf:"bytes,15,opt,name=gamerPVPStateSyncC2S" json:"gamerPVPStateSyncC2S,omitempty"`
	GamerPVPStateSyncS2C *GamerPVPStateSyncS2C      `protobuf:"bytes,16,opt,name=gamerPVPStateSyncS2C" json:"gamerPVPStateSyncS2C,omitempty"`
	CancelMatchC2S       *GamerCancelMatchC2S       `protobuf:"bytes,17,opt,name=cancelMatchC2S" json:"cancelMatchC2S,omitempty"`
	CancelMatchS2C       *GamerCancelMatchS2C       `protobuf:"bytes,18,opt,name=cancelMatchS2C" json:"cancelMatchS2C,omitempty"`
	RoomListC2S          *RoomListC2S               `protobuf:"bytes,19,opt,name=roomListC2S" json:"roomListC2S,omitempty"`
	RoomListS2C          *RoomListS2C               `protobuf:"bytes,20,opt,name=roomListS2C" json:"roomListS2C,omitempty"`
	ChangeReadyC2S       *GamerChangeReadyInRoomC2S `protobuf:"bytes,21,opt,name=ChangeReadyC2S" json:"ChangeReadyC2S,omitempty"`
	ChangeReadyS2C       *GamerChangeReadyInRoomS2C `protobuf:"bytes,22,opt,name=ChangeReadyS2C" json:"ChangeReadyS2C,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RPC) Reset()         { *m = RPC{} }
func (m *RPC) String() string { return proto.CompactTextString(m) }
func (*RPC) ProtoMessage()    {}
func (*RPC) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_b348f1a917968e3b, []int{4}
}
func (m *RPC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPC.Unmarshal(m, b)
}
func (m *RPC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPC.Marshal(b, m, deterministic)
}
func (dst *RPC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPC.Merge(dst, src)
}
func (m *RPC) XXX_Size() int {
	return xxx_messageInfo_RPC.Size(m)
}
func (m *RPC) XXX_DiscardUnknown() {
	xxx_messageInfo_RPC.DiscardUnknown(m)
}

var xxx_messageInfo_RPC proto.InternalMessageInfo

func (m *RPC) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RPC) GetServerHello() *ServerHello {
	if m != nil {
		return m.ServerHello
	}
	return nil
}

func (m *RPC) GetGamerNotify() *GamerNotify {
	if m != nil {
		return m.GamerNotify
	}
	return nil
}

func (m *RPC) GetGamerNotifyList() *GamerNotifyList {
	if m != nil {
		return m.GamerNotifyList
	}
	return nil
}

func (m *RPC) GetGamerExitPVP() *GamerExitPVP {
	if m != nil {
		return m.GamerExitPVP
	}
	return nil
}

func (m *RPC) GetTestChatC2S() *GamerTestChatC2S {
	if m != nil {
		return m.TestChatC2S
	}
	return nil
}

func (m *RPC) GetTestChatS2C() *GamerTestChatS2C {
	if m != nil {
		return m.TestChatS2C
	}
	return nil
}

func (m *RPC) GetMatchC2S() *GamerMatchC2S {
	if m != nil {
		return m.MatchC2S
	}
	return nil
}

func (m *RPC) GetMatchS2C() *GamerMatchS2C {
	if m != nil {
		return m.MatchS2C
	}
	return nil
}

func (m *RPC) GetCheckPVPBattleC2S() *GamerCheckPVPBattleC2S {
	if m != nil {
		return m.CheckPVPBattleC2S
	}
	return nil
}

func (m *RPC) GetCheckPVPBattleS2C() *GamerCheckPVPBattleS2C {
	if m != nil {
		return m.CheckPVPBattleS2C
	}
	return nil
}

func (m *RPC) GetGamerNewRoomC2S() *GamerNewRoomC2S {
	if m != nil {
		return m.GamerNewRoomC2S
	}
	return nil
}

func (m *RPC) GetGamerNewRoomS2C() *GamerNewRoomS2C {
	if m != nil {
		return m.GamerNewRoomS2C
	}
	return nil
}

func (m *RPC) GetGamerAddRoomC2S() *GamerAddRoomC2S {
	if m != nil {
		return m.GamerAddRoomC2S
	}
	return nil
}

func (m *RPC) GetGamerAddRoomS2C() *GamerAddRoomS2C {
	if m != nil {
		return m.GamerAddRoomS2C
	}
	return nil
}

func (m *RPC) GetGamerLeaveRoomC2S() *GamerLeaveRoomC2S {
	if m != nil {
		return m.GamerLeaveRoomC2S
	}
	return nil
}

func (m *RPC) GetGamerLeaveRoomS2C() *GamerLeaveRoomS2C {
	if m != nil {
		return m.GamerLeaveRoomS2C
	}
	return nil
}

func (m *RPC) GetGamerPVPStateSyncC2S() *GamerPVPStateSyncC2S {
	if m != nil {
		return m.GamerPVPStateSyncC2S
	}
	return nil
}

func (m *RPC) GetGamerPVPStateSyncS2C() *GamerPVPStateSyncS2C {
	if m != nil {
		return m.GamerPVPStateSyncS2C
	}
	return nil
}

func (m *RPC) GetCancelMatchC2S() *GamerCancelMatchC2S {
	if m != nil {
		return m.CancelMatchC2S
	}
	return nil
}

func (m *RPC) GetCancelMatchS2C() *GamerCancelMatchS2C {
	if m != nil {
		return m.CancelMatchS2C
	}
	return nil
}

func (m *RPC) GetRoomListC2S() *RoomListC2S {
	if m != nil {
		return m.RoomListC2S
	}
	return nil
}

func (m *RPC) GetRoomListS2C() *RoomListS2C {
	if m != nil {
		return m.RoomListS2C
	}
	return nil
}

func (m *RPC) GetChangeReadyC2S() *GamerChangeReadyInRoomC2S {
	if m != nil {
		return m.ChangeReadyC2S
	}
	return nil
}

func (m *RPC) GetChangeReadyS2C() *GamerChangeReadyInRoomS2C {
	if m != nil {
		return m.ChangeReadyS2C
	}
	return nil
}

func init() {
	proto.RegisterType((*ServerHello)(nil), "ServerHello")
	proto.RegisterType((*GamerNotify)(nil), "GamerNotify")
	proto.RegisterType((*GamerNotifyList)(nil), "GamerNotifyList")
	proto.RegisterType((*GamerExitPVP)(nil), "GamerExitPVP")
	proto.RegisterType((*RPC)(nil), "RPC")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_rpc_b348f1a917968e3b) }

var fileDescriptor_rpc_b348f1a917968e3b = []byte{
	// 620 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x95, 0xdf, 0x8e, 0x93, 0x40,
	0x14, 0xc6, 0xd3, 0xd2, 0xd5, 0xed, 0xc0, 0xd2, 0x76, 0xec, 0xae, 0x64, 0x2f, 0xb4, 0xe9, 0x55,
	0xe3, 0x05, 0x26, 0xf4, 0xc2, 0x44, 0xbd, 0x58, 0x97, 0x6c, 0xb4, 0xc9, 0x6a, 0xc8, 0x60, 0x7a,
	0x6b, 0x46, 0x98, 0xb6, 0xc4, 0x16, 0x36, 0x30, 0xae, 0xf6, 0x89, 0x7c, 0x1d, 0xff, 0x3d, 0x90,
	0x39, 0xc3, 0xbf, 0xe9, 0x40, 0xbd, 0x83, 0x73, 0xbe, 0xdf, 0xf7, 0x9d, 0xd3, 0x01, 0x8a, 0xfa,
	0xe9, 0x5d, 0x60, 0xdf, 0xa5, 0x09, 0x4f, 0x2e, 0x8d, 0x8c, 0xa5, 0xf7, 0x2c, 0x2d, 0xef, 0x82,
	0x6d, 0xc4, 0x62, 0x5e, 0xdc, 0x99, 0xf4, 0x2b, 0x4f, 0x3e, 0x65, 0x4e, 0xa1, 0x9d, 0x5e, 0x21,
	0xdd, 0x17, 0xea, 0x77, 0x6c, 0xbb, 0x4d, 0xf0, 0x53, 0xd4, 0x8b, 0xe2, 0x55, 0x62, 0x75, 0x26,
	0x9d, 0x99, 0xee, 0xe8, 0x76, 0xde, 0x5b, 0xc4, 0xab, 0x84, 0x88, 0x06, 0x1e, 0x22, 0x6d, 0x97,
	0x65, 0x56, 0x77, 0xa2, 0xcd, 0xfa, 0x04, 0x2e, 0xa7, 0x2f, 0x90, 0xfe, 0x96, 0xee, 0x58, 0xfa,
	0x21, 0xe1, 0xd1, 0x6a, 0x0f, 0x82, 0x28, 0xcc, 0xac, 0xce, 0x44, 0x9b, 0x9d, 0x10, 0xb8, 0xc4,
	0x17, 0x48, 0xcb, 0x9c, 0xc0, 0xea, 0x0a, 0xcb, 0x9e, 0xed, 0x3b, 0x2e, 0x81, 0xc2, 0x74, 0x8e,
	0x06, 0x12, 0x78, 0x1b, 0x65, 0x1c, 0x4f, 0x50, 0x2f, 0xa4, 0x9c, 0x0a, 0x5a, 0x77, 0x0c, 0x5b,
	0xea, 0x13, 0xd1, 0x99, 0x3e, 0x41, 0x86, 0x28, 0xde, 0x7c, 0x8f, 0xb8, 0xb7, 0xf4, 0xb0, 0x89,
	0xba, 0x51, 0x28, 0xc6, 0x3d, 0x21, 0xdd, 0x28, 0x9c, 0xfe, 0xd0, 0x91, 0x46, 0x3c, 0x17, 0x0f,
	0x44, 0xfd, 0xe7, 0xa0, 0x6c, 0xe0, 0xe7, 0x48, 0xcf, 0xea, 0x45, 0xad, 0x5f, 0x03, 0x31, 0x8e,
	0x61, 0x4b, 0xdb, 0x13, 0x59, 0x01, 0xc0, 0xba, 0x8e, 0xb7, 0x7e, 0x97, 0x80, 0x3c, 0x93, 0xac,
	0xc0, 0xaf, 0xd0, 0x60, 0x7d, 0xb8, 0x8f, 0xf5, 0x27, 0x87, 0x86, 0xb6, 0xb2, 0x28, 0x51, 0x95,
	0xd8, 0x41, 0xc6, 0x5a, 0xda, 0xcb, 0xfa, 0x9b, 0x93, 0x67, 0xb6, 0xbc, 0x2d, 0x39, 0xd0, 0xe0,
	0x39, 0xd2, 0x39, 0xcb, 0xb8, 0xbb, 0xa1, 0xdc, 0x75, 0xfc, 0xe2, 0xcc, 0x46, 0x39, 0xf1, 0xb1,
	0x6e, 0x10, 0x59, 0x25, 0x43, 0xbe, 0xe3, 0x16, 0xa7, 0xa2, 0x40, 0x70, 0x44, 0xb2, 0x0a, 0x3f,
	0x43, 0xa7, 0x3b, 0xca, 0x83, 0x0d, 0xc4, 0x68, 0x82, 0x30, 0x73, 0xe2, 0x7d, 0x51, 0x25, 0x55,
	0xbf, 0xd2, 0x82, 0x7b, 0xaf, 0xa1, 0x05, 0xeb, 0xaa, 0x8f, 0x6f, 0xd0, 0x28, 0xd8, 0xb0, 0xe0,
	0x8b, 0xb7, 0xf4, 0xae, 0x29, 0xe7, 0x5b, 0x06, 0x01, 0x0f, 0x05, 0xf4, 0x38, 0x87, 0x5c, 0xb5,
	0x4d, 0x9a, 0x44, 0xd3, 0x06, 0xb2, 0x4f, 0x8f, 0xdb, 0xc0, 0x10, 0x4d, 0x02, 0xbf, 0x2c, 0x0f,
	0x90, 0x7d, 0x23, 0x49, 0xb2, 0x83, 0x59, 0xfa, 0x07, 0xe7, 0x57, 0xd5, 0x89, 0x2a, 0x54, 0x59,
	0x18, 0x00, 0xb5, 0xb0, 0x90, 0xac, 0x0a, 0x2b, 0xf6, 0x4d, 0x18, 0x96, 0xb9, 0xba, 0xcc, 0xd6,
	0x75, 0xa2, 0x0a, 0x55, 0x16, 0x72, 0x8d, 0x16, 0xb6, 0xce, 0xad, 0x0b, 0xf8, 0x0a, 0x8d, 0x44,
	0xe9, 0x96, 0xd1, 0x7b, 0x56, 0x26, 0x9f, 0x09, 0x1a, 0xe7, 0xb4, 0xdc, 0x21, 0x4d, 0x71, 0xd3,
	0x01, 0xf2, 0xcd, 0x56, 0x07, 0xf1, 0x9b, 0x37, 0xc4, 0x78, 0x81, 0xc6, 0xa2, 0xe8, 0x2d, 0x3d,
	0x9f, 0x53, 0xce, 0xfc, 0x7d, 0x1c, 0xc0, 0x18, 0xf9, 0xe3, 0x7f, 0x9e, 0x9b, 0x28, 0x4d, 0xd2,
	0x8a, 0xb4, 0x5a, 0xc1, 0x3c, 0xc3, 0x63, 0x56, 0x30, 0x52, 0x2b, 0x82, 0x5f, 0x23, 0x33, 0xa0,
	0x71, 0xc0, 0xb6, 0xe5, 0xf3, 0x6d, 0x8d, 0x84, 0xc9, 0xb8, 0x78, 0x9a, 0x0e, 0x7a, 0x44, 0xd1,
	0x2a, 0x34, 0x8c, 0x80, 0x8f, 0xd0, 0x30, 0x81, 0xa2, 0xc5, 0x36, 0xd2, 0xd3, 0x24, 0xd9, 0xc1,
	0x57, 0x01, 0x82, 0x1f, 0x15, 0x9f, 0x1d, 0x52, 0xd7, 0x88, 0x2c, 0x90, 0xf5, 0x10, 0x35, 0x56,
	0xf4, 0xe2, 0x5d, 0x96, 0x04, 0xf8, 0x1a, 0x99, 0xee, 0x86, 0xc6, 0x6b, 0x46, 0x18, 0x0d, 0xf7,
	0x10, 0x71, 0x2e, 0x90, 0xcb, 0xf2, 0x4d, 0xa9, 0x7a, 0x8b, 0xb8, 0x3c, 0x7a, 0x85, 0x50, 0x3c,
	0x20, 0xf6, 0xe2, 0xbf, 0x1e, 0x62, 0xcf, 0x43, 0xe2, 0xf3, 0x03, 0xf1, 0x07, 0x34, 0xff, 0x17,
	0x00, 0x00, 0xff, 0xff, 0xc6, 0xe9, 0xd8, 0x7c, 0xb9, 0x06, 0x00, 0x00,
}
